### ISSUE TITLE
Remove the global search bar

### ISSUE THREAD

**Issue by lexiwitch** [geeksforsocialchange/PlaceCal#1003]
At the moment there is a global search bar, see:

![image](https://user-images.githubusercontent.com/92374839/156172738-1bed605d-c9af-4b54-bc5d-95ab3b6a23e5.png)

We should either make it do something (maybe, show all references to $term across all entities that we have (like, searching `sutton` would fuzzy search for `sutton` and return a neighbourhoods section, a sites section, etc. all with `sutton` somewhere in the resulting models)), or remove it

**Comment by aaaaargZombies** [comment]
## verified

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/5e89d9ba-fe53-4560-b627-088ff1490416)
