### ISSUE TITLE
Implement events that happen in service areas

### ISSUE THREAD

**Issue by ivankocienski** [geeksforsocialchange/PlaceCal#1009]
For this milestone: When looking for events that happen in a site's neighbourhood set, select events by address (as before) but also include events that have service areas (in the sites neighbourhood set).

Note: Events must have an address that is either set explicitly by the user or they pull that address from their place (partner) field.

**Comment by kimadactyl** [comment]
A site should show an event if any of the following are true:

- is the event address in the site scope?
- is the event host in the site scope?
- are any of the event host's service areas in the site scope?

**Comment by ivankocienski** [comment]
By event host you mean partner?
