### ISSUE TITLE
Find a better way to handle adding new calendar formats

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1013]
**Is your feature request related to a problem? Please describe.**

Currently, every calendar format has to be added to the codebase itself with a valid regex URL.

This makes sense for the big generic providers like Google, Outlook, Meetup etc.

It makes less sense when adding individual custom iCal feeds such as supplied through wordpress themes, API feeds and the like.

Before we begin adding a load more calendar feeds we should probably review if there's a better way to do this.

**Comment by kimadactyl** [comment]
See also #1012

**Comment by ivankocienski** [comment]
I don't think there exists a better way of doing this. Events come from many sources and need to be funneled into a Calendar and Event structure. So there needs to exist code that validates that we know how to parse a source and code that does the actual extraction and normalization.

Unless there is a gem for this or we are willing to use a SaaS I believe that's about the nature of the beast.

There could be opportunities for refactoring or rearranging this complex code so it is apart from the main rails model code?

**Comment by kimadactyl** [comment]
yeah i was thinking more a refactor. like the way the regex thing works now is kinda ugly. 

was also wondering if more of this logic would be in the database? it feels kinda bad security wise to just share endpoint info for custom sources too

**Comment by kimadactyl** [comment]
Now covered by other tickets
