### ISSUE TITLE
Sites can filter by tags

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1029]
**Is your feature request related to a problem? Please describe.**

The GMSC and Trans DIm site and API feed needs to filter down to just partners tagged GMSC / Trans DImension

**Describe the solution you'd like**

The Site edit page allows people to select a tag that restricts the partners and events that show up on both these locations

**Comment by alexandria-gfsc** [comment]
Prematurely closed :)
