### ISSUE TITLE
Stop CI / staging complaining if we merge too fast

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1032]
If you merge two PRs right after each other, the CI complains

```
Pushing to Dokku Host
ECDSA host key for IP address 'XX.XX.XX.XX' not in list of known hosts.
remote:  !     placecal currently has a deploy lock in place. Exiting...        
remote:  !     Run 'apps:unlock' to release the existing deploy lock        
To ssh://placecal-staging.org:PORT/placecal
 ! [remote rejected] COMMIT_ID -> main (pre-receive hook declined)
error: failed to push some refs to 'ssh://dokku@placecal-staging.org:PORT/placecal'
```

**Comment by katjam** [comment]
@geeksforsocialchange/developers is this something we have any control over or should we close as a won't fix. I feel like we've improved workflow since this was raised.

**Comment by ivan-kocienski-gfsc** [comment]
It doesn't seem to me like something we'd have direct control over.

Unless there is a check we can run in the workflow that tests if a deploy is already happening?

**Comment by ivan-kocienski-gfsc** [comment]
Although having said that I just found [this](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) which looks like a start for such a thing

**Comment by ivan-kocienski-gfsc** [comment]
There is also [documentation](https://docs.github.com/en/actions/using-jobs/using-concurrency) about concurrency that may be helpful

**Comment by ivan-kocienski-gfsc** [comment]
In conversation with the team we concluded that this is not causing enough problems (yet) to warrant a hard fix. We will just be mindful that at the times we are submitting a lot of PRs quickly that the CI deploy may fail (and we will be notified).
