### ISSUE TITLE
Figure out why select2 is buggy on pages where you have both single select elements and multi select elements

### ISSUE THREAD

**Issue by alexandria-gfsc** [geeksforsocialchange/PlaceCal#1046]
Currently we have many pages that display select2 single select items. This is fine... until you attempt to add a multiple select2 node.

In most of the pages where we have single select2 items, we have the following Javascript:
```
        // Attach select2 to the current select2 nodes
        $('.select2').each(function () { $(this).select2({ multiple: false }); });
```

This means that select 2 is applied to all items with a select2 class on them. Duplicating this for a different tag like `select2multi` causes it to fail. 

The current workaround is checkboxes, however this will become infeasible as the checkboxes become more numerous. Find a solution / workaround and apply it where needed.

**Comment by kimadactyl** [comment]
i think if you give each select2 input a different class and run the .select2 method on each individually it should work. it's likely that it's using class name internally to keep track of the state for each one.

**Comment by alexandria-gfsc** [comment]
Yeah! The solution I went with when I posted this (So I can tag the PR fixing it) was to add another class for `multi-select` and check the presence of it when creating `.select2` items, which cleans up the code a little from what it would have been otherwise:

```
        $('.select2').each(function () {
          multiple = $(this).hasClass('multi-select');
          $(this).select2({ multiple: multiple });
        });
```
