### ISSUE TITLE
PlaceCal localhost user setup requires u.accept_invitation! or it continually thinks that you have not accepted the mail

### ISSUE THREAD

**Issue by lexiwitch** [geeksforsocialchange/PlaceCal#1056]
From Ivan while on call:

> You have to use `u.accept_invitation!` or it doesn't think you have accepted the mail and loops infinitely

This shouldn't happen, and didn't/doesn't happen for me! So it is weirdness that should be investigated :)

**Comment by katjam** [comment]
@ivan-kocienski-gfsc is this still a thing that causes problems?

**Comment by ivan-kocienski-gfsc** [comment]
The seeds come with users pre-built and this is not necessary for those accounts (looks like the readme process does run the seeds).

For locally built users this still must occur (or you have to open the link from the dev log window)

So I think it can be closed
