### ISSUE TITLE
Check we have proper database indexes

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1057]
I think this has really slipped and could prob use a thorough review

**Comment by alexandria-gfsc** [comment]
All fields of `schema.rb` have ids except for: 

```
  create_table "collections_events", id: false, force: :cascade do |t|
  create_table "sites_supporters", id: false, force: :cascade do |t|
```

These are legacy join tables and we can put off adding IDs on them until we start dealing with `Collections` or `Supporters` (Both of them need a bit of a rejig)
