### ISSUE TITLE
Review and properly document user roles

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1063]
Roles we've been discussing recently:

- [ ] root
- [ ] global moderator -- root minus stuff like slug and site config
- [ ] citizen
- [ ] editor -- global editor for news stuff
- [ ] developer -- can access API 

We should have a think if these are bools or enums properly, one more more scales, and if theres anything else we're forgetting.

**Comment by ivankocienski** [comment]
@kimadactyl too vague, not implementable by developers ("We should have a think...")
