### ISSUE TITLE
address and areasServiced data not consistant

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1079]
**Describe the bug**
The frontend relies on data for address & service being standardised - if we sometimes get empty strings or prepended spaces, we accidentally will display them as string values. 
![image](https://user-images.githubusercontent.com/861172/159749417-abdbb235-d50f-4910-abd2-cc8c6c21c1da.png)

**To Reproduce**
- Example of badly formatted `postalCode`: Yellowbird Age Friendly (id 17) & New Hope Fellowship Church (id 49)
- maybe related Query Partner id 17 and get "message": "no implicit conversion of nil into String",
- Example of empty string for `abbreviatedName` Partner (id 145)

**Expected behavior**
- We expect `address` to contain a `postalCode` field with a UK post code formatted as "AB1 2GT" with a space between the area & district, but sometimes there is a prepended space.

- We expect `areasServed` to contain a list of service areas that contain `name` and maybe an `abbreviatedName` sometimes the abbreviated name is recorded as an empty string rather than `null`

**Screenshots**
![image](https://user-images.githubusercontent.com/861172/159747091-9ec6137f-545a-41d2-9dfe-195a42790639.png)
![image](https://user-images.githubusercontent.com/861172/159749664-c6edbc99-18f8-4f6d-8714-831ecc2d2deb.png)

**Comment by kimadactyl** [comment]
this is done but not deploying for Reasons currently!

**Comment by ivankocienski** [comment]
These have now been implemented and run on local, staging and production
