### ISSUE TITLE
Simplify and reconsider factories

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1083]
The factories are causing us a lot of grief at the moment due to some sloppy scoping. Lots of the test logic is effectively just inside factory files which isnt great.

These should be simplified and more of the logic put in the setup blocks for each individual test.

**Comment by katjam** [comment]
@geeksforsocialchange/developers is this still an issue or have we made some improvements as part of the neighbourhood work?

**Comment by ivan-kocienski-gfsc** [comment]
I think so.

We still use fixtures and factory bot at the same time.

Neighbourhoods are validated and built in a messy way and the tests have to work around this.

Partners could be looked at (but may be okay).

Sites could be looked at (but may be okay).

Users may be okay.

Calendars could be looked at (but may be okay).

**Comment by katjam** [comment]
Part of #1919 closing as duplicate.
