### ISSUE TITLE
Epic: Get TransDim ready

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1089]
## What does TransDim need?

- [x] #1091
- [x] I can get a list of Events by Trans DImension Partners in the API
- [x] #1094
- [x] #1072 

## What does PlaceCal need?

- [x] #1090
- [x] #1087

**Comment by kimadactyl** [comment]
there is eventsByFilter tho yeah? https://www.notion.so/gfsc/API-Reference-933b0eb85b3b40dcaec5e4200ca7458a

**Comment by katjam** [comment]
Yep. I'm going to chat to Ivan. I am hoping that can take a list of partner IDs. Just have to work out to get the partner Ids before I call it too.

**Comment by katjam** [comment]
Yep.If there is one tag we use for partners to designate "For this site" then should work for our use case now. I had not realised the Event Filter actually uses partner tag & all partners on this site have that tag.

**Comment by kimadactyl** [comment]
@katjam is this done?

**Comment by katjam** [comment]
Yep. Closing.
