### ISSUE TITLE
Investigate neighbourhood setting breakage on a new user

### ISSUE THREAD

**Issue by alexandria-gfsc** [geeksforsocialchange/PlaceCal#1104]
**Current Behaviour**
- Make a new user using the `users/create` screen. Give them a neighbourhood region (like `london, england`)
- Log in as new user
- User is missing `neighbourhood_admin` permission and has no neighbourhood regions assigned to them  

**Intended Behaviour (Checklist for testing)**
- [ ] Create a new user, give them a neighbourhood region (like `london, england`)
- [ ] Log in as user
- [ ] User has `neighbourhood_admin` permission and has neighbourhood region assigned to them

**Approval Criteria**
- [ ] I can make a new user, assign one or more neighbourhoods to them, when they log in they have those neighbourhoods assigned and have the `neighbourhood_admin` permission set to true

**Comment by kimadactyl** [comment]
What actually is the bug here? Pls use the template :)

**Comment by alexandria-gfsc** [comment]
The bug is that a neighborhood set on the /create screen on a new user isn't carried over during save. Probably a transient bug, and I'm not sure why it would have happened. If it doesn't occur (i.e. following the steps in the issue don't present a bug), it's fine to close :)

**Comment by ivankocienski** [comment]
It was verified that root users can create new users (also with root role) with neighbourhoods and when logging in as new users they can see the neighbourhood_admin flag has been set and they can see the neighbourhoods that were assigned.

Any new behaviour should require a new ticket
