### ISSUE TITLE
Articles can have Tags

### ISSUE THREAD

**Issue by alexandria-gfsc** [geeksforsocialchange/PlaceCal#1120]
Do these now

- [ ] An Article has_many Tags
- [ ] As an Endpoint User, I should be able to ask for a list of Articles for a Tag in a GraphQL Query
- [ ] As Root, I should be able to alter the Tags shown for an Article in the Admin Edit Screen
- [ ] As an Editor, I should be able to alter the Tags shown for an Article in the Admin Edit Screen

Do these later

- [ ] As a Partner Admin, I should be able to alter the Tags shown for an Article in the Admin Edit Screen
- [ ] As a Neighbourhood Admin, I should be able to alter the Tags shown for an article in the Admin Edit Screen
- [ ] As a User, I should be able to see an Article's tags in the Index listing

**Comment by kimadactyl** [comment]
**Use cases**

1. I'm a TransDim Partner. If I publish an Article, I want it to show on the TransDim site
1. I'm an Editor or Root and I want to make Articles show up on the TransDim site, even if they don't have a Partner tagged.
1. I'm a GMSC Partner. I want to publish an Article and have it show up on the GMSC site, and my local neighbourhood site
1. I'm a GMSC Partner. I want to publish an Article and have it show up only on my local neighbourhood site

**Use cases we don't care about**

1. I'm a TransDim Partner. If I publish an Article, I **do not** want it to show on the TransDim site. _Why would u want this?_
