### ISSUE TITLE
Calendar "updated at" is getting changed every time the importer runs

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1121]
**Describe the bug**

Calendar "updated at" should change whenever an admin changes the details in the calendar.

Calendar "last imported at" should change whenever the importer successfully runs.

Currently both are being updated together.

**To Reproduce**

1. Go to https://admin.placecal-staging.org/calendars
1. See error

**Expected behavior**

Updated at does not change when calendar imports

**Screenshots**

<img width="1230" alt="Screenshot 2022-04-06 at 10 16 55" src="https://user-images.githubusercontent.com/511734/161941923-802e0bb7-9a82-47b7-806c-70cf3aab7ec4.png">

**Comment by kimadactyl** [comment]
this seems to be an issue again - reopening 

<img width="1280" alt="Screenshot 2022-11-11 at 11 25 13" src="https://user-images.githubusercontent.com/511734/201330855-c9f20eb1-9cce-4a8b-8068-fb527dd9c359.png">

**Comment by katjam** [comment]
@ivankocienski To check if it's fixed and close if so.
