### ISSUE TITLE
Fix db sync tool documentation

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1159]
**Describe the bug**

As of recent upgrade, db sync tool seems to have stopped working.

**To Reproduce**

`rails db:dump_production_and_restore_other restore_on_local=1`

This might be version related and a documentation bug but either way be good for it to be clearer what's unhappy

**Comment by alexandria-gfsc** [comment]
Does `rake db:sync_prod_staging` work?

**Comment by alexandria-gfsc** [comment]
Added page `Synchronizing production to staging` on Notion / Placecal devops
