### ISSUE TITLE
graphql API: Add lat and long to address for Partner & Event

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1165]
**Is your feature request related to a problem? Please describe.**
Lat and Long required to generate mapbox images for Trans Dimesion Event and Partner listings

**Describe the solution you'd like**
Kim thinks:
> we want to add a geo property (https://schema.org/Place) that has a GeoCoordinates object in it (https://schema.org/GeoCoordinates)

## Steps to complete

- [x] Partners API endpoint has a geo property
- [x] Geo property has type: GeoCoordinates, latitude and longitude

**Comment by katjam** [comment]
Yep. All we need for the mapbox image is lat and long. Thanks.

**Comment by kimadactyl** [comment]
Oop, forgot they wanted these for events too.

Suggest that we just simplify this and have the `geo` bit part of `Address` instead even tho its not totally compliant. Too much faff.
