### ISSUE TITLE
Calendar edit/create page is super bugged

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1176]
**Describe the bug**

I think this didn't survive the turbo migration. Prob needs putting in some kind of no-turbo block for now of some description.

**To Reproduce**

**Issue 1: bugged out strategy selector**

1. Pick "default location" and select a venue
2. Click "save"
3. Pick "event" and click "save"
4. Select option reverts to previous selection

**Issue 2: import_events button doesnt work**

Now fixed!

**Comment by alexandria-gfsc** [comment]
`import events` button on Calendar page is nonfunctional
