### ISSUE TITLE
Velociposse events not showing up on (1) partner page (2) main events page

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1198]
These places are in our new category that do not have a location/place known to us

- [x] They should show up on the velociposse partner page because of the partner match
- [x] They should show up in the trans dim site listing because of the service area match (depends on #1194)
- [x] They can still raise a notice/warning in the calendar but this should not prevent the above

**Comment by alexandria-gfsc** [comment]
See: #1201
