### ISSUE TITLE
[Bug]: Importer not properly displaying punctuation characters from certain sources

### ISSUE THREAD

**Issue by alexandria-gfsc** [geeksforsocialchange/PlaceCal#1208]
## Description

When viewing issues, certain characters like quote marks (`'`) or dashes (`-`) are replaced with `?` in the description text

## Steps to reproduce

1. View [here](https://trans-dimension.placecal.org/events/277027) and [here](https://trans-dimension.placecal-staging.org/events/277343)
2. I see weird question marks in the description in the first one
3. I see lots of `\n` characters in the second one

![Screenshot from 2022-05-03 13-06-29](https://user-images.githubusercontent.com/92374839/166449872-60147205-f692-4a28-b72f-f65da2a097bc.png)

## What you expected to happen

I should be able to see punctuation instead of question marks, and newlines instead of `\n`

![Screenshot from 2022-05-03 13-06-14](https://user-images.githubusercontent.com/92374839/166449843-d82882d4-9d77-4fcd-a703-69988c55480a.png)

<img width="1056" alt="Screenshot 2022-05-03 at 17 36 55" src="https://user-images.githubusercontent.com/511734/166499172-bd3867db-3a7d-47bd-ae2b-e66c697bfa46.png">

**Comment by alexandria-gfsc** [comment]
I suspect that this calendar is in `iso-8859-1` format and not `utf-8`, it might simply be we are expecting a given encoding when it is not the case. While figuring out encoding of a given text is NP-hard, it should be possible to verify this case by checking for instances of the (character number of) `'` or `-` and other such punctuation characters.

**Comment by kimadactyl** [comment]
This is possibly chopping stuff off the bottom of listings too

https://trans-dimension.placecal-staging.org/events/27688

![Screen Shot 2022-05-03 at 18 26 45](https://user-images.githubusercontent.com/511734/166506559-f47ea75f-036c-4835-9d4e-1f82d880adf1.png)
