### ISSUE TITLE
Web scrapers are maxing out our logging tools and probably slowing down the site

### ISSUE THREAD

**Issue by alexandria-gfsc** [geeksforsocialchange/PlaceCal#1230]
## User story

As a Developer, I need to be able to use Rollbar so that I can see production/staging errors.

As a Developer, I am currently unable to use Rollbar, because of 11k events from web scrapers going over our tier limit.

## Acceptance criteria

- [ ] [This rollbar item](https://rollbar.com/gfsc/placecal-production/items/107/) should no longer trigger after 2202-05-23

## Implementation notes & questions

Summary: Rollbar died due to 11k warnings being triggered from our site. It looks like it's entirely just web scrapers thinking that we have a specific event at `/events/(id)`, but our event ids got changed up so we do not.

There are a number of ways we can do this:
- `.htaccess`
- `robots.txt`
- Altering our rollbar config to not report these (it doesn't really matter if these 3 or 4 bots scrape our site)
- ??? There are other ways too

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
I would like to add Cloudflare to prod but we need to evaluate if that will cause any issues with caching, api endpoint, postcodes.io access, etc etc (i dont think so but lets be sure)
