### ISSUE TITLE
[Bug]: Foreign constraint violation when doing import:all_events on staging db

### ISSUE THREAD

**Issue by alexandria-gfsc** [geeksforsocialchange/PlaceCal#1262]
## Description

I was running the importer by hand

## Steps to reproduce

1. Run `rake import:all_events`
2. Notice a number of exceptions due to 

```
ActiveRecord::InvalidForeignKey: bad thing: PG::ForeignKeyViolation: ERROR:  insert or update on table "events" violates foreign key constraint "fk_rails_b2e7252813"
DETAIL:  Key (place_id)=(44486) is not present in table "partners".
```

This appears to occur on calendars: 8, 30 

## What you expected to happen

The events should be taken into the system as normal.

## Platform (if relevant)

Ran with a fresh database from staging and stashed my changes so `HEAD` was on `main` (Specifically `f9bc3a7` / `v0.11.0`)

**Comment by kimadactyl** [comment]
Assuming this is now resolved as noone's reported it for a while and the whole system has been changed in the interim.

**Comment by ivan-kocienski-gfsc** [comment]
Verified - ran task on staging with no faults
