### ISSUE TITLE
[Bug]: Handbook is down

### ISSUE THREAD

**Issue by janbaykara** [geeksforsocialchange/PlaceCal#1264]
Visiting the handbook linked via the README doesn't work. It's down! https://handbook.placecal.org/

<img width="883" alt="Screenshot 2022-05-30 at 15 20 34" src="https://user-images.githubusercontent.com/237556/171011413-651ab6fb-1254-4450-98c9-22240a87069d.png">

**Comment by kimadactyl** [comment]
Ha yeah I have set it as a http redirect to our new notion page for it and have no idea why its not working!! V frustrating :) 

It is here atm anyway if you need it in the interim, in the process of migrating from readthedocs which was just an enormous pita to update: https://www.notion.so/gfsc/PlaceCal-Handbook-8825c5a470954703be4acaca68f51c8f

**Comment by janbaykara** [comment]
That makes a lot of sense! We're currently doing a lot of docs on Notion and were in fact thinking of moving it to Github, but I share the belief that Notion is where most edits would get done. We've used https://super.so/ for the odd occassion where we want both Notion editing as well as better-than-average presentation.

**Comment by kimadactyl** [comment]
Oooooh that looks like a good shout thanks! Honestly that's like half our total hosting bill atm per month lol but maybe worth it if it's one thing we don't have to think about. And the SEO question has been bothering me.

We tried Github wiki for imok and honestly it's a pain and not even that easy to include in the main repo. We also probably obviously want non-technical users to be able to edit it when we get up and running so anything git-y is immediately a huge barrier. I feel the perfect solution is yet to exist!

**Comment by kimadactyl** [comment]
Alright have set that up as a redirect, not sure if the "use our domain" plan is free or not but I guess we find out in 30 days, thanks so much for this!!

**Comment by kimadactyl** [comment]
This is so weird, it was working? My best guess is they are running interference on http redirects to stop you doing exactly this which is kinda fucked tbh
