### ISSUE TITLE
[Bug]: Improve styling of new password form

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1284]
## Description

What were you doing?
Accepting sign up to new account - this is the first screen new users see. It should not look broken.

## Steps to reproduce

1. Click accept invite link (e.g. https://placecal.org/users/invitation/accept?invitation_token=rk9szD8D2ZyPzTBZzzvq)

## What you expected to happen
See a pretty form

What would you like to happen instead?
The form sits comfortably in the frame

![image](https://user-images.githubusercontent.com/861172/173332785-08541031-cf98-40e8-af51-ddddf472bde6.png)

**Comment by kimadactyl** [comment]
At the top of `routes.rb` you can see theres some monkey patches for `:users` that link to files in `/app/controllers/users`. The key line is the one that does `before_action :set_site` because that then sets `default_site` and then everything else should load corerctly.
