### ISSUE TITLE
[Bug]: 404 on GET bootstrap 4 css asset

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1285]
## Description
Console error:
https://placecal.org/assets/datatables.net-bs4/css/dataTable.bootstrap4.css

## Steps to reproduce

1. Visit placecal.org
2. See 404 in console

## What you expected to happen

If we are not using it, remove the GET. Id we are using it, fix the path / add the asset into build.

![image](https://user-images.githubusercontent.com/861172/173334427-975b328e-25ef-4092-948f-4a3129446d5c.png)

**Comment by ivankocienski** [comment]
This issue was fixed [here](https://github.com/geeksforsocialchange/PlaceCal/commit/0fda07cb733d5cb8faa45cce70681b6453fd66cc).

**Comment by ivan-kocienski-gfsc** [comment]
Verified on production and staging
