### ISSUE TITLE
[Bug]: Vue running in dev mode in production build

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1287]
## Description
vuejs should be compiled in production mode on production.

No idea how easy this is with current build process. Not a big priority.

![image](https://user-images.githubusercontent.com/861172/173335598-ccc5c4e6-9f8f-4fa3-94b7-b83af8abff7c.png)

**Comment by kimadactyl** [comment]
Note that we should resolve this by removing Vue entirely

**Comment by alexandria-gfsc** [comment]
Are we actually using vue for anything now? I thought we'd already migrated away from using it :o

**Comment by katjam** [comment]
> Are we actually using vue for anything now? I thought we'd already migrated away from using it :o

Hey @alexandria-gfsc small nit-pick. Making comments like this here take people away from other stuff - and do not progress the issue.

You can check for yourself whether or not we are using it - and if you can't find out by looking at the code, then ask the writer of the ticket (me in thins case) explicitly whether the issue is still relevant.
