### ISSUE TITLE
[Bug]: Sign in requires refresh after entering password

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1288]
## Description

When I sign in to PlaceCal, I get errors and no visual indication that I have signed in.
If I refresh the login screen, I am redirected to the admin dashboard (so actually sign in did work)

This might be to do with me using a few different log-ins on same browser, which could happen on a shared computer in a partner org, but is not the most usual use case.

We should verify that this does not happen to users who are only using one login per browser instance.

## Steps to reproduce

1. Sign out with one user account
2. Refresh browser
3. Sign in with user account

## What you expected to happen

When I press login button, I land on my admin dashboard.

What device and browser were you using?
Chromium Version 101.0.4951.41 (Official Build) Arch Linux (64-bit)

![image](https://user-images.githubusercontent.com/861172/173336196-31c2c9ae-ac88-4892-bc73-60bc8ea90bac.png)

**Comment by alexandria-gfsc** [comment]
This also is a salient problem with logging out of PlaceCal too

**Comment by ivankocienski** [comment]
i thought this was fixed in PR covering #1286

**Comment by katjam** [comment]
Fixed. Verified on production.
