### ISSUE TITLE
[Bug]: Invite email contains escaped html

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1290]
## Description

This is a little ugly as a first intro to the system.

If it is not easy to send as html, then maybe just remove the `< br/>`

![image](https://user-images.githubusercontent.com/861172/173339096-cd92f9b4-7083-42c0-9505-3fb154a1941b.png)

## Strategy

Open up email controller, find view, see what is wrong, fix, test, push?

**Comment by kimadactyl** [comment]
change line 1 to "You've been invited to join PlaceCal! You can accept this invite by clicking the link below"

**Comment by kimadactyl** [comment]
And lets remove the `<div class="c">` wrappers for each file in `/app/views/devise/mailer` while we're here, that's a mistake
