### ISSUE TITLE
[Bug]: Forgot Password flow redirects to Log Out

### ISSUE THREAD

**Issue by alexandria-gfsc** [geeksforsocialchange/PlaceCal#1294]
## Description

Trying to get a password reset on local development causes a redirect to `Log In` after accepting the email link.

## Steps to reproduce

1. Go to Log In
2. Click "Forgot my password"
3. Enter your email address and submit the form
4. You should be directed to the email with the password accept link
5. Strip the `https://` off the link and visit it
6. Get immediately redirected to "Log Out"

## What you expected to happen

After step 5,
6. I should see a form to enter my new password

## Platform (if relevant)

Local development, because I am currently not able to verify on Staging due to another bug.

**Comment by katjam** [comment]
On production:

1- requested password reset
![image](https://user-images.githubusercontent.com/861172/173812948-9ea92d06-f76c-4f28-8dce-b9ff6428c002.png)

**Comment by kimadactyl** [comment]
arghhhhhhh

**Comment by katjam** [comment]
We'll check logs in a bit.

**Comment by katjam** [comment]
Blocked by #1295

**Comment by kimadactyl** [comment]
Doing it on prod for me
