### ISSUE TITLE
[Bug]: Selecting a date to filter events by on a partner pages scolls to top

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1307]
## Description

On a partner page (e.g. https://moss-side.placecal.org/partners/52), if I use the filter controls for event listing, when the page reloads with my results, I land at the top and have to scroll to see events.

This is mildly confusing but not urgent.

![image](https://user-images.githubusercontent.com/861172/173832025-dc9636cd-7093-4b0e-b1a2-528747b7a7ec.png)

**Comment by kimadactyl** [comment]
can do this as part of #1306 it should just be a simple html anchor right?

**Comment by ivan-kocienski-gfsc** [comment]
Verified [here](https://moss-side.placecal.org/partners/37/events/2024/3/18?period=week&sort=#paginator) that this is fixed.

(Although it would be better to use hotwire to replace the contents of the filter results box)
