### ISSUE TITLE
[Bug]: Alternative contact method text at bottom of join form oversized & change to generic email

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1310]
## Description
![image](https://user-images.githubusercontent.com/861172/173843198-ebef6ad6-bfd7-4cc6-a6c3-6ff492e4865f.png)

## Acceptance
- Text should be the same size as "Get in touch and let’s discuss how you can
join our not-for-profit social enterprise."
- change contact email from kim@ to info@ (double check with Kim which email to use - we might want placecal@ ?)

**Comment by kimadactyl** [comment]
<img width="784" alt="Screenshot 2022-06-28 at 16 17 54" src="https://user-images.githubusercontent.com/511734/176216776-5aa072ff-4e6b-4edd-a75b-55c06887eaf2.png">

confirmed fixed
