### ISSUE TITLE
[Bug]: Event import needs re-run on production & better documentation

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1311]
## Description

Viewing same event on staging and production reveals that the website address for the event is missing on production.

## Steps to reproduce

https://berwickshire.placecal.org/events/283154
![image](https://user-images.githubusercontent.com/861172/173844328-a442c911-21cd-40d7-9633-78e07be19fd2.png)

vs
https://berwickshire.placecal-staging.org/events/279574
![image](https://user-images.githubusercontent.com/861172/173844386-aabd286f-039f-4bf5-8fa2-86a2c2fa811b.png)

## What you expected to happen
They should match

## Notes

![image](https://user-images.githubusercontent.com/861172/173844597-7e454894-be4e-4508-80e8-9ec93bc3f8e9.png)

**Comment by kimadactyl** [comment]
That button is really massive can we just make it a regular link pls when this is done 😄

**Comment by katjam** [comment]
Dream Yard until it becomes a user need

**Comment by kimadactyl** [comment]
Is this still outstanding or was it resolved?

**Comment by katjam** [comment]
I don't think an issue was ever made to reduce the size of the button - but we certainly have done a lot of work on designs and logic listing online events so I think we can safely close this.
