### ISSUE TITLE
[Bug]: After password reset request, redirect to a screen telling you to check your inbox

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1322]
## Description

When you do a password redirect, after filling in the form it sends you back to the login screen. This is a bit confusing. 

## Steps to reproduce

1. Go to https://placecal.org/users/password/new
1. Enter email

## What you expected to happen

I think it should either

- Go to the home page with a flash message saying "check your inbox"
- Go to a dedicated page with just "check your inbox - remember to check spam if it's not arrived"

**Comment by ivankocienski** [comment]
This may work now that flashes are being rendered visibly on the root placecal site.

**Comment by kimadactyl** [comment]
Nice nice
