### ISSUE TITLE
[Bug]: Several importers are stuck on in_worker status

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1329]
## Description

There are 8 calendars permanently stuck on "in worker"

## Steps to reproduce

1. View https://admin.placecal.org/jobs
2. Feelds 25, 19, 5 etc never change status

## What you expected to happen

To complete processing and go back to idle even if they fail

To show an error message if they won't import or the URL is wrong

<img width="803" alt="Screenshot 2022-06-17 at 13 55 17" src="https://user-images.githubusercontent.com/511734/174302688-a5624d4f-c0af-41fe-9aa0-69684c3f7935.png">

**Comment by ivankocienski** [comment]
There seems to be a problem with how jobs are given to the calendar importer and there is an Active Record exception raised during the job. This is fine but the calendars are not being put into the correct state so they look like they are perpetually in the worker.

**Comment by katjam** [comment]
@kimadactyl @ivankocienski I'm not sure how to verify this - there are 5 in worker on staging right now, but I do not know whet that means.

![image](https://user-images.githubusercontent.com/861172/181274123-64591a14-163b-4934-995f-87ecb26702fb.png)

**Comment by kimadactyl** [comment]
I think this means it's prob not done but it's an improvement on before

**Comment by katjam** [comment]
Should we re-open? Or wait until it comes up again?

**Comment by kimadactyl** [comment]
It seems to be working now?
