### ISSUE TITLE
[Bug]: It is not clear that image upload on Article has a size limit

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1334]
## Description

What were you doing?
Trying to add an image to article

## Steps to reproduce

1. Upload an image that is 1.2MB
2. No error on the upload
3. When I save there is no image

## What you expected to happen
I'd like to see some guidance on what the file size limit is
Even better a warning when I try to upload an image that is bigger
Or at least an error message when I save that my image was too big

Currently the only indication is a 413 error on POST in the console.

**Comment by kimadactyl** [comment]
Just a note that this size limit comes from NginX i think and I'm not sure how to change it (or have the app read it in for that matter)
