### ISSUE TITLE
[Bug]: No location set for default location strategy calendar message is unhelpful

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1343]
## Description

Calendar validation error message isnt very helpful

## Steps to reproduce

1. Create a new calendar
1. Set strategy to 'default location' ('place' strategy in code)
1. Don't pick a default location
1. Error message doesn't tell you what's wrong

## What you expected to happen

A more helpful error message, maybe some better context clues to select default location.

## Platform (if relevant)

What device and browser were you using?

**Comment by kimadactyl** [comment]
Perfect, just to tidy up a bit:

> You have selected the "Default Location" strategy to set events on this calendar's locations, but the "Default Location" field has not been set. Please go to the [edit calendar page](link) and set a Default Location, or choose another strategy.

**Comment by katjam** [comment]
@ivankocienski Not sure how to get this error to appear. Is this the old one or a different one?

![image](https://user-images.githubusercontent.com/861172/182150525-d5075143-0646-43f1-9222-9d5c9c0eaa6f.png)

**Comment by kimadactyl** [comment]
have you tried saving while its like that? this looks fine tho. i think this was quite a niche error tbh

**Comment by katjam** [comment]
Yeah that error came after I pressed save. Maybe needs more fields filled in.

I'm happy for this to go in either way if it's a niche error and @ivankocienski has presumably tested that it works as expected.
