### ISSUE TITLE
Show maps on partners with addresses and service areas

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1346]
## User story

As a partner I want to see a nice map on my page even if I have a service area set in order that people can see where our office is based (People found this counterintuitive in testing)

As a citizen I don't want to see service area-based organistaions on the global page though as this tends to zoom the map out to London

## Acceptance criteria

- [ ] Partner show page has map if both service area and address are listed
- [ ] Partner index page does not have marker if both service area and address are listed

## Implementation plan

_To be written by the developer_

**Comment by ivankocienski** [comment]
@kimadactyl 

Some clarifications:

As a user who is viewing the 'show partner' page, and the partner has no address but does have service areas, I would like to see those service areas on the partner's map.

As a user who is viewing a 'sites index' or 'partners index' page, I would only like to see pins in the map from partners that have physical addresses (no service areas).

Is this still valid?

**Comment by kimadactyl** [comment]
> As a user who is viewing the 'show partner' page, and the partner has no address but does have service areas, I would like to see those service areas on the partner's map.

No - I don't want to start building a way to visualise service areas. It's just soley if we have an address, show it irregardless if service area is set or not on the show page

> As a user who is viewing a 'sites index' or 'partners index' page, I would only like to see pins in the map from partners that have physical addresses (no service areas).

On the index page however these are getting in the way - so don't show markers for addresses where a service area is present becuse they're making the maps do weird things.

This prob needs further refinement down the road.

**Comment by ivan-kocienski-gfsc** [comment]
> > As a user who is viewing the 'show partner' page, and the partner has no address but does have service areas, I would like to see those service areas on the partner's map.
> 
> No - I don't want to start building a way to visualise service areas. It's just soley if we have an address, show it irregardless if service area is set or not on the show page

This is the current behaviour: on show partner page, only show the map with a pin if the partner has an address. [controller code here](https://github.com/geeksforsocialchange/PlaceCal/blob/0fda07cb733d5cb8faa45cce70681b6453fd66cc/app/controllers/partners_controller.rb#L57)

Although it does only provide a map if NO service areas are present. so this is the behaviour to change?

**Comment by kimadactyl** [comment]
> Although it does only provide a map if NO service areas are present. so this is the behaviour to change?

YEs exactly :)

**Comment by katjam** [comment]
Not sure which partners have only service areas - yet, but so far - no zoom out in Hulme. There are no PlaceCal's to compare with in production as they are not active there.

![image](https://user-images.githubusercontent.com/861172/181961419-9fccf208-35fe-45fb-9747-c1c98963fc09.png)

Will check next week which partners I should be looking at.

**Comment by kimadactyl** [comment]
London not showing Consortium (index page works)

<img width="1261" alt="Screenshot 2022-08-01 at 10 54 36" src="https://user-images.githubusercontent.com/511734/182123273-087a4c14-9bf4-4eca-880a-43c77e56bddd.png">

The show view is not working though -- there is no map even though it should as it has an address

<img width="1303" alt="Screenshot 2022-08-01 at 10 55 55" src="https://user-images.githubusercontent.com/511734/182123526-d5d633a8-ffd2-4ff6-a0fd-99d9df595bcd.png">

I think this is still an improvement and will merge this and open a new ticket.

**Comment by kimadactyl** [comment]
Opened #1410

**Comment by kimadactyl** [comment]
Apologies. I'm a total idiot, I was testing on placecal.org and not placecal-staging.org. Blame mondays. Confirm this is working!

<img width="1318" alt="Screenshot 2022-08-01 at 11 57 17" src="https://user-images.githubusercontent.com/511734/182133665-efc56d0b-4cb5-407f-97c1-c766ba579340.png">

<img width="1227" alt="Screenshot 2022-08-01 at 11 57 35" src="https://user-images.githubusercontent.com/511734/182133719-5609439f-a013-4040-903c-46b6deff1a70.png">
