### ISSUE TITLE
[Bug]: README quickstart instructions incomplete - seeding the DB

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1371]
## Description

I followed the "quick start" instructions to get the database up and running. It looked positive in the command line but when connecting to 
`lvh.me:3000` the page would not load.

@kim suggested running 

```sh
bundle exec rails db:setup db:migrate seed:migrate
bundle exec rails import:all_events
```
This resolved the issue and these commands are covered in the notion page "PlaceCal live db download instructions". But I am not clear which `db` commands where essential to getting up and running.

## Steps to reproduce

Follow quick start guide in readme

## What you expected to happen

To Follow quick start guide in readme and have a working DB

**Comment by erbridge** [comment]
This is fixed by the introduction of setup scripts in #1459, I think. Can you confirm @aaaaargZombies?

**Comment by erbridge** [comment]
Oh wait. I do too now. Odd. Thanks for testing.

**Comment by kimadactyl** [comment]
I think you prob found this now (sorry looking at some old todos) but the live db sync instructions are on our [private notion](https://www.notion.so/gfsc/PlaceCal-live-db-download-instructions-0cd4a7fb21314890a3e18d718a0b8f8b). the prob is that we only ever develop with live data so the seeds are now out of date. this is covered in the new issues ofc.
