### ISSUE TITLE
[Bug]: "find your placecal" linking to live site not local versions

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1373]
## Description

Trying to access events via the menus takes you to the live website on the internet / away from the local dev environment.

## Steps to reproduce

1. Click "find your placecal" in top menu `http://lvh.me:3000/find-placecal`
2. click a location, eg. Hulme.
3. end up at `https://hulme.placecal.org/`

The local version is accessible by typing the address directly eg. `http://hulme.lvh.me:3000/`

## What you expected to happen

Links within the local environment don't take you to a different version of the site.

**Comment by katjam** [comment]
Needs to be verified on a dev version. @alexandria-gfsc or @aaaaargZombies can you please do that? Mine is broken at the moment. :)
