### ISSUE TITLE
[Bug]: Partners visible on incorrect sites if you type the URL in manually

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1386]
## Description

You can view any partner on any site if you type it in the URL bar. This is being picked up by Google.

## Steps to reproduce

1. Go to https://moston.placecal.org/partners/will-griffiths-court
1. Note this is in Moss Side and should not show up on this site

## What you expected to happen

Currently - probably 404 or redirect (but to where?)

This might be easier to resolve after Kim's suggested home page refactor. Partners just don't have canonical URLs currently, and should.

**Comment by alexandria-gfsc** [comment]
Maybe redirect to the Site's Partners page?

**Comment by kimadactyl** [comment]
I think we just obsolete this one later but leaving it open as long as it's technically an issue

**Comment by kimadactyl** [comment]
Closing as dupe of #1722
