### ISSUE TITLE
Go through `behaviors` folder and group common functionality for extraction to stimulus.

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1389]
## User story

As a developer I need have a consistent / standardised way of adding JS functionality to Placecal so that I can focus on the feature I am working on and not maintain a DIY JS loading system.

## Acceptance criteria

- [x] All functionality in behaviors folder has an issue describing how it will be transferred to stimulus.

## Implementation plan

The first one is done for select2 see #1387
Continue based on this approach

**Comment by aaaaargZombies** [comment]
I don't think everything is covered by an issue yet. I'll start adding some now but I'm nearly out of time.

**Comment by kimadactyl** [comment]
i just added a bunch fyi

**Comment by aaaaargZombies** [comment]
This is done and work is underway
