### ISSUE TITLE
Document Datatables usage

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1390]
## User story

As a developer working on #1340 I need come back to finish this off at a later date so that I can work on some of the issues that have been highlighted in #1340.

## Acceptance criteria

- [ ] Useful info relating to Datatables exists in [JS wiki page](https://github.com/geeksforsocialchange/PlaceCal/wiki/Javascript-in-PlaceCal#code-we-have-wrote-but-not-used) 

## Implementation notes & questions

Either work finished on new issues or this becomes necessary to complete the issues I want to work on.

## Implementation plan

Read code base and library docs. Update [JS wiki page](https://github.com/geeksforsocialchange/PlaceCal/wiki/Javascript-in-PlaceCal#code-we-have-wrote-but-not-used) if needed.

**Comment by kimadactyl** [comment]
Superceded by the "Write system tests for ..." tickets we just made
