### ISSUE TITLE
[Bug]: Staging storage is full

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1392]
## Description

Disk space on staging is low and our monitoring software is spamming us with emails warning us about this.

## Steps to reproduce

N/A

## What you expected to happen

Clean out the disk so no more warning emails. Possibly investigate where this is happening and purge the files. If it is possible this should be automated.

**Comment by kimadactyl** [comment]
happy to just increase the limit to say 75%, it does seem a LOT of disk space for a lil rails app tho

**Comment by alexandria-gfsc** [comment]
yeah lmao

Docker(tm) in a (slowly expanding) Nutshell

**Comment by alexandria-gfsc** [comment]
I went ahead and expanded it to `73`, given thats the highest we've ever seen it at
