### ISSUE TITLE
[Bug]: Unclear when data is updated in forms using back / forward button

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1393]
## Description

I was editing a user, If i navigate with the back / forward buttons my data is still in the form. If I refresh it is gone. This is probably confusing for a user if they are not sure when / how work is saved.

## Steps to reproduce

1. Go to a calendar http://admin.lvh.me:3000/calendars/109/edit in the browser.
2. Update the name.
3. hit back, then forward. Data retained.
4. Refresh. Data reverted to saved state.

## What you expected to happen

Either;
- leaving a page destroys unsaved data.
- Data is saved on change.

## Platform (if relevant)

Firefox, linux

**Comment by erbridge** [comment]
Counterpoint: this is almost exactly the behaviour I'd want. Accidentally hit "back"? Phew, it's all still there, but still in draft.

I believe this behaviour is browser default and not actually PlaceCal, and is a Good Thing. The one thing we might want to consider here is explicitly saving "draft" content, but that also feels like a really high effort thing to do.

**Comment by katjam** [comment]
Closing as won't fix. Will come up as part of usability testing if real issue for people.
