### ISSUE TITLE
[Bug]: Replace site admin field in Sites with a select2

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1394]
## Description

Setting the site admin is currently a total pain

## Steps to reproduce

1. Create a new site
2. See dropdown options below

## What you expected to happen

Replace this with a select2

<img width="986" alt="Screenshot 2022-07-20 at 12 34 07" src="https://user-images.githubusercontent.com/511734/179972280-d3742d69-85d8-4851-bc3d-e2c583618f33.png">

**Comment by kimadactyl** [comment]
Ahh noo it doesn't need to change the underlying relationship, it's litearlly just that this input is not searchable or alphabatized so it's impossible to find the user you want. It's still a has_one! This is the person that shows up on the site homepage for the local contact.

It is probably technically a feature though you're right!

**Comment by katjam** [comment]
User can type-ahead and get auto-complete but the entries are not ordered in any obvious way

![image](https://user-images.githubusercontent.com/861172/181274935-513ef8ee-284c-4c18-84e5-90a4fc9e8f19.png)


@kimadactyl Is this still "passing"?

**Comment by kimadactyl** [comment]
Yeah this is "good enough", it's something I set like once a month and it's only me that does it really
