### ISSUE TITLE
[Bug]: #107 ActiveRecord::RecordNotFound: Couldn't find Event with 'id'=275583

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1407]
## Description

https://rollbar.com/gfsc/placecal-production/items/107/

This is single handedly overloading our rollbar limit, labeled urgent but realistically we might be over limit before this gets tackled

## Steps to reproduce

1. What you did first
1. What you did next

## What you expected to happen

What would you like to happen instead?

## Platform (if relevant)

What device and browser were you using?

**Comment by ivankocienski** [comment]
Might want to look at [this](https://riptutorial.com/ruby-on-rails/example/9621/rescuing-activerecord--recordnotfound-with-redirect-to) and check if PC has something along those lines.
