### ISSUE TITLE
Move leaflet functionality into Stimulus

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1418]
## User story

As a developer, I want all my javascript in Stimulus controllers, so that its easier to understand and maintain

## Acceptance criteria

- [ ] Refactor Leaflet code into Stimulus

## Implementation plan

_To be written by the developer_

**Comment by aaaaargZombies** [comment]
A question for later, I'm importing all the stimulus controllers into both 'admin.js` and `application.js` which feels like I'm delivering unused code in both cases. It looks like this is how name.pn is working and how rails-stimulus is designed. see this [issue](https://github.com/hotwired/stimulus-rails/issues/105).

There is an option to separate these out and not use the `rails generate stimulus CONTROLLER_NAME` command line helper.
