### ISSUE TITLE
Remove `behaviors.place.js`

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1419]
## User story

As a developer I need to not have to look at old code we aren't using so that I can reduce the amount of time fixing bugs or adding features.

## Acceptance criteria

- [ ] file is removed but no site functionality is lost.

## Implementation notes & questions

I believe this has been replaced by `behaviors.partners.js`

This is part of #1389

## Implementation plan

Delete file, run tests, manually check site.

**Comment by kimadactyl** [comment]
Place and Partner used to be diff models then we merged them - this is prob just old crud
