### ISSUE TITLE
Move partner image preview to a stimulus controller

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1421]
## User story

As a developer I need move useful code out of the behaviors folder so that I don't have to keep track of turbo load events.

## Acceptance criteria

- [ ] A stimulus controller is created that replicates the existing functionality 
- [ ] A system test is written so JS is more robust in the future

## Implementation notes & questions

- remove jquery as it is not needed for this small task.
- [behaviors.partner.js:11](https://github.com/geeksforsocialchange/PlaceCal/blob/ecdc157e895df47435858e0d86507efaa77c78dd/app/javascript/src/behaviors/behaviors.partner.js#L11)
- part of #1389

## Implementation plan

Keep most of the logic, replace jquery with stimulus

**Comment by aaaaargZombies** [comment]
the sites page also deals with images, is this functionality needed there?

**Comment by kimadactyl** [comment]
Yes it would be nice to hvae it there but if it's a new feature it's outside the scope of our current milestone. Please do make a new ticket tho for like "add image preview to all image upload fields" if that is the case
