### ISSUE TITLE
[Bug]: partners showing up multiple times on same page

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1427]
## Description

I was visiting https://gmsc.placecal.org/partners and I saw that Flourish was listed 3 times

## Steps to reproduce

1. visit https://gmsc.placecal.org/partners

## What you expected to happen

No duplication of listings

## Implementation notes

This is proving to be a sticky issue, the following prob need doing

- [ ] Rewrite the AR stuff as straight SQL so it can be read easily 
- [ ] Write better tests for site partners page that do things like check tags work
- [ ] Write tests for the blocks on the site homepages like "where to get online"

**Comment by kimadactyl** [comment]
Labelling urgent as I think this looks super janky and will cause Questions

**Comment by kimadactyl** [comment]
Oops. put this in the wrong place. This is currenlty totally ignoring the tag filter - shit. My bad for approving this but this needs fixing asap

<img width="1407" alt="Screenshot 2022-08-22 at 13 00 19" src="https://user-images.githubusercontent.com/511734/185916431-a01a014a-104e-47df-b530-0f66466b8b2b.png">
