### ISSUE TITLE
[Bug]: Site admin not accepting new header image

### ISSUE THREAD

**Issue by undividual** [geeksforsocialchange/PlaceCal#1428]
## Description

Trying to upload a new header image to the C2 PlaceCal site

## Steps to reproduce

1. Uploaded one image successfully (but it was the wrong one)
2. Followed the same process to try and upload a second image, but it would not replace it
3. Tried logging in and out again, tried with and without image credit, made no difference

## What you expected to happen
Image to upload

What would you like to happen instead?
For the image to actually upload

## Platform (if relevant)

What device and browser were you using?
macOS Big Sur, Firefox

**Comment by kimadactyl** [comment]
Labelling urgent as this is preventing us getting a new user going

**Comment by undividual** [comment]
![C2HeaderImage_Photo](https://user-images.githubusercontent.com/90701712/182820069-60663463-45ec-4a58-9463-5ded24c21f77.png)
Oh yeah, here's the image concerned as requested. Credit for Daniel Funes Fuentes (Unsplash)

**Comment by ivan-kocienski-gfsc** [comment]
This looks like it is a problem with the file size. That PNG is 1.8 megs and when I converted it to a JPG it dropped to ~500 kb and could be uploaded.

So either:
- better wording on the requirements text
- increase limit (I suspect this may be in nginx as the code states it has a limit of 10mb)

**Comment by kimadactyl** [comment]
that's weird, yeah we deffo increased this before! if it's 10mb why is it failing with a 1.8mb image?

so i guess steps

- [ ] Find why it's failing even tho it's under the 10mb limit
- [ ] Add in a "failed validation - image too big" flash message. Maybe while we're at it we should check this works everywhere?
- [ ] Improve requirements text

This is possibly 3 tickets? Also @aaaaargZombies has added the code to make lil previews when you upload - maybe the second item on this list should be to review and standardize all the image uploaders? Like the file type thing isn't exactly consistent or well documented why the choice was made either.
