### ISSUE TITLE
Convert `paginator.js` to Stimulus

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1441]
## User story

As with other areas of the site, we want to remove jQuery and move towards stimulus.

## Acceptance criteria

- [ ] jQuery code removed
- [ ] any JS moved out of `/components` dir and into a stimulus contrller

## Implementation notes & questions

See `app/javascript/src/components/paginator.js`

A page is loaded with 7 days worth of buttons + a back and forward button. This is the amount needed to fill the screen at the parents largest possible width.

When loaded a javascript function runs to see if there is enough space to display all buttons, if not it hides some of them. This also trickers when resizing the window.

- native resize trigger available https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver
- potential to set overflow to scrollable in CSS and not use JS at all.

## Implementation plan

_To be written by the developer_

**Comment by erbridge** [comment]
Suggest we hold on this one until we know what we're doing with components.

**Comment by katjam** [comment]
Closing as won't fix. No longer a priority.
