### ISSUE TITLE
[Bug]: Calendar organiser field overlaps layout

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1445]
## Description

On the calendar screen the input field for oragniser goes into the right column

<img width="953" alt="Screenshot 2022-09-05 at 16 42 17" src="https://user-images.githubusercontent.com/511734/188483852-06144caf-dd89-4df2-a130-26b24d210fa1.png">

## Steps to reproduce

1. Go to https://admin.placecal.org/calendars/113/edit
2. 

## What you expected to happen
Fields align properly

**Comment by erbridge** [comment]
Apart from being a bit visually janky, does this interfere with anything?

**Comment by kimadactyl** [comment]
Nah

**Comment by katjam** [comment]
Closing as won't fix. Hopefully admin area will get overhaul when we need it to.
