### ISSUE TITLE
Lint Ruby

### ISSUE THREAD

**Issue by erbridge** [geeksforsocialchange/PlaceCal#1453]
## User story

As a developer I need to have my Ruby code checked by a computer so that I know it follows the repository code standards and doesn't have any obvious issues.

## Acceptance criteria

- [ ] Ruby code is linted as part of testing

## Implementation plan

_To be written by the developer_

**Comment by ivan-kocienski-gfsc** [comment]
Verified in code: we use ruby linting in the default make task, as a precommit hook on local dev machine and as part of the CI deploy process
