### ISSUE TITLE
Lint JavaScript

### ISSUE THREAD

**Issue by erbridge** [geeksforsocialchange/PlaceCal#1454]
## User story

As a developer I need to have my JavaScript code checked by a computer so that I know it follows the repository code standards and doesn't have any obvious issues.

## Acceptance criteria

- [ ] JavaScript code is linted as part of testing

## Implementation plan

_To be written by the developer_

**Comment by ivan-kocienski-gfsc** [comment]
This is already happening as part of the prettier linting script that is run pre-commit

**Comment by ivan-kocienski-gfsc** [comment]
Verified in code, is run pre-commit and as part of CI branch merge protections
