### ISSUE TITLE
Lint stylesheets

### ISSUE THREAD

**Issue by erbridge** [geeksforsocialchange/PlaceCal#1455]
## User story

As a developer I need to have my stylesheets checked by a computer so that I know it follows the repository code standards and doesn't have any obvious issues.

## Acceptance criteria

- [ ] Stylesheets are linted as part of testing

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
Related to https://github.com/geeksforsocialchange/PlaceCal/issues/1319

**Comment by r-ferrier** [comment]
verified in the code - no sass remains and all scss is now linting on save.
