### ISSUE TITLE
Run formatters and linters on CI

### ISSUE THREAD

**Issue by erbridge** [geeksforsocialchange/PlaceCal#1457]
## User story

As a developer I need to have CI check my code so that I know it doesn't break standards when merging.

## Acceptance criteria

- [ ] CI fails if there are formatting issues
- [ ] CI fails if there are linting issue

## Implementation plan

_To be written by the developer_

**Comment by ivan-kocienski-gfsc** [comment]
Verified in code.

Linting is run as part of the [deploy process](https://github.com/geeksforsocialchange/PlaceCal/blob/f8809e85343ef10834e9469419cd96b2f6f2383a/.github/workflows/test-and-deploy.yml#L53).
