### ISSUE TITLE
Make admin permissions more granular

### ISSUE THREAD

**Issue by erbridge** [geeksforsocialchange/PlaceCal#1479]
## User story

As a superadmin I need be able to grant admin users the minimal access they need so that I can give them full autonomy to work without putting other things at risk.

## Acceptance criteria

- [ ] We have more details issue(s) written up for this work

**Comment by kimadactyl** [comment]
I think the permissions are granular on the right level - they are just untested. This should be documented... somewhere.

**Comment by kimadactyl** [comment]
Concrete things 

- Georgie should only be able to see London partners tagged TransDim, and only create new partners tagged TransDim
- Rachele should only be able to see partners in GM tagged GMSC, and able to create partners anywhere in Manchester

If this is too complex this could also work:

- Georgie can edit all of london and tag and untag things TransDim
- rachele can edit all of greater manchester and tag and untag things GMSC

... it gets messy fast

**Comment by r-ferrier** [comment]
closing as duplicate, we're working on this in more detail in other tickets
