### ISSUE TITLE
[Bug]: fix handbook link

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1498]
## Description

This is not being imported properly https://www.eventbrite.co.uk/o/43149878503

Partner "London Trans Meetup"

**Comment by aaaaargZombies** [comment]
> DJ-MUMSNET — Today at 8:53 AM
Also - for Eventbrite links, how do we add them as a calendar? This one doesn't appear to be pulling any events through. I realise it's not a .ics link but I'm not sure how to get that from Eventbrite? I clicked the PlaceCal Handbook but the link is dead.
<img width="594" alt="eventbrite_screenshot" src="https://user-images.githubusercontent.com/6824891/197533416-6e8e612c-b1e6-4d8a-b22a-cc334762d63e.png">
