### ISSUE TITLE
[Bug]: Metadata description for events is Markdown when it should be plain text

### ISSUE THREAD

**Issue by erbridge** [geeksforsocialchange/PlaceCal#1530]
https://trans-dimension.placecal.org/events/320734:

<img width="531" alt="Screenshot 2022-11-02 at 18 48 09" src="https://user-images.githubusercontent.com/1027364/199551580-685f8f26-8ec4-4b5a-99e7-470b15fb5f56.png">

I think that says it all?

**Comment by kimadactyl** [comment]
This is also being output via the API to TransDim - unsure eaxctly what the functionality should be here. @katjam - which end do you think we should fix this?

https://transdimension.uk/events/320734

<img width="1197" alt="Screenshot 2022-11-03 at 12 47 47" src="https://user-images.githubusercontent.com/511734/199724335-39c75f0f-9cf2-44de-8730-aabc945ebecf.png">

**Comment by kimadactyl** [comment]
Just realised this should prob be 2 bugs - break it up if you like @erbridge

**Comment by ivan-kocienski-gfsc** [comment]
So the original problem seems to be fixed on both local dev environment and production:
![Screenshot_2022-11-07_16-27-11](https://user-images.githubusercontent.com/109223824/200362576-7c423ea3-a046-4ab7-82b2-d3e2f5f07ff0.png)

**Comment by kimadactyl** [comment]
this is why this ticket needs splitting into 2 heh. there's 2 problems here: 

- api output has those weird markdown css classes in
- og:description has the markdown classes in too

both should be plaintext

**Comment by erbridge** [comment]
The original issue this describes hasn't been addressed.

**Comment by aaaaargZombies** [comment]
I have created a new issue #1540 for the api output and leaving this one to deal with metadata.
