### ISSUE TITLE
[Bug]: TestoHunkies events are not importing via OutSavvy

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1531]
For these calendar settings, nothing is being imported (also doesn't work with 'place' strategy)

<img width="1435" alt="Screenshot 2022-11-03 at 00 30 10" src="https://user-images.githubusercontent.com/511734/199724517-ad13d4a5-f19e-45bf-bee1-a81c42296e42.png">

Even though there is one event in the future here:

https://outsavvy.com/organiser/testo-hunkie1

**Comment by kimadactyl** [comment]
Riposte not working either https://admin.placecal.org/calendars/121/edit

**Comment by kimadactyl** [comment]
This doens't seem to be working on prod - reopening

**Comment by ivan-kocienski-gfsc** [comment]
Just checked this on production and the upstream URLs.

- TestoHunkies don't have any events on the source page.
- Riposte has one event. The calendar looked like it was stuck in the `in_queue` state and when I manually ran the import task it completed without incident. There is now an event on that calendar (as this is what appears on the source URL).

**Comment by kimadactyl** [comment]
Testohunkies did have one event at the time the calendar ran that did not import - you can see it in 'past events'. Was this perhaps the same issue?

**Comment by ivan-kocienski-gfsc** [comment]
production does seem to be working for both these. they get queued up and complete. there are past events that have been imported (going by the calendar edit page).

**Comment by kimadactyl** [comment]
Oh they were not there before! I really shoulda screenshotted the view page. OK, it must have been the stuck in_queue thing. All good.
