### ISSUE TITLE
[Bug]: Literal &amp;s are in the API output for event titles

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1533]
Not sure if this is a problem PlaceCal or TransDim end but we have a HTML token here visible in the event title:

https://transdimension.uk/events/320735

<img width="1197" alt="Screenshot 2022-11-03 at 12 54 44" src="https://user-images.githubusercontent.com/511734/199725973-e20c82b2-0880-4220-8522-2adba6a1f746.png">

@katjam, what do you think?

**Comment by katjam** [comment]
Probably being encoded like that in PlaceCal. TransDim is already set up to handle Markdown or plain strings. So it would be useful if PlaceCal sent as one of those.

**Comment by ivan-kocienski-gfsc** [comment]
So this isn't a bug exactly but an ambiguity in specs? The titles and summaries coming from PlaceCal are identical and are assumed to be plain utf-8 text (without any HTML encoding). We don't do any filtering in PC apart from stripping bad utf-8 characters. So if the calendar importer gets any HTML from the remote calendar source then it is saved as is. When TransDim reads that data it is then presented on the TransDim site as if it were plain text which elm escapes for us before rendering the string into HTML. so `&amp;amp;` gets rendered into `&amp;amp;amp;` which is what we are seeing.

fixing this could be done either by
- rendering out any HTML on PlaceCal side so it is plaintext and then assuming the string is "HTML safe"
- rendering the HTML on TD side like we do for the description (but trusting that whatever is present in that field isn't compromising)
- both

**Comment by kimadactyl** [comment]
Prob need @erbridge input here as well as @katjam

**Comment by erbridge** [comment]
Isn't there another option which is to expand HTML encoded characters only? eg https://stackoverflow.com/a/1600584

**Comment by ivan-kocienski-gfsc** [comment]
This was fixed in PR but it wasn't linked properly

https://github.com/geeksforsocialchange/PlaceCal/commit/d5971c12626daeec20be1e18a59647b191008e99
