### ISSUE TITLE
Tests should not depend on the real current datetime

### ISSUE THREAD

**Issue by erbridge** [geeksforsocialchange/PlaceCal#1572]
## Description

```
Failure:
PartnerIntegrationTest#test_if_theres_a_lot_of_events_show_them_with_a_paginator [/path/to/PlaceCal/test/integration/partner_integration_test.rb:84]
Minitest::Assertion: Expected at least 5 elements matching "div.event", found 0..
Expected 0 to be >= 5.
```

Lots of instances of `PartnerIntegrationTest#test_if_theres_a_lot_of_events_show_them_with_a_paginator` have been failing this weekend on CI:

```
Failure:
PartnerIntegrationTest#test_if_theres_a_lot_of_events_show_them_with_a_paginator [/path/to/PlaceCal/test/integration/partner_integration_test.rb:84]
Minitest::Assertion: Expected at least 5 elements matching "div.event", found 0..
Expected 0 to be >= 5.
```

After a bunch of investigation, I worked out that the issue is to do with the way pagination works by grouping by week:

The factory generates events starting at `DateTime.now + 1.day` and ending at `DateTime.now + 1.day + 2.hours`. If `DateTime.now` is on Sunday, then that means created events start on Monday.

Pagination groups by week and defaults to the current week. But all of our events are next week, so we have no events to show this week. So the test fails.

I'm also getting the following error, which given the assertion that fails is looking for some events, I'd suspect the a similar issue (I haven't actually looked at the code):

```
Failure:
EventsControllerTest#test_should_get_index_with_configured_subdomain [/path/to/PlaceCal/test/controllers/events_controller_test.rb:52]
Minitest::Assertion: Expected exactly 2 elements matching "ol.events li", found 0..
Expected: 2
  Actual: 0
```

We should make our tests more deterministic and stop using real time in them anywhere, as I suspect this is the cause of other test flakiness. We could use something like [Timecop](https://github.com/travisjeffery/timecop) to do that.

## Acceptance criteria

- [x] Tests are configured to freeze time to a fixed, known date
- [ ] We test known time sensitive behaviour for boundary conditions and edge cases

**Comment by kimadactyl** [comment]
Excellent catch!

**Comment by kimadactyl** [comment]
Is this resolved now @aaaaargZombies?

**Comment by aaaaargZombies** [comment]
@erbridge said to leave this open because of

> We test known time sensitive behaviour for boundary conditions and edge cases

I think we just deal with this stuff as it comes up and close this when we are confident that we've got them all. Maybe they will correct me if that's not right.

**Comment by kimadactyl** [comment]
Pretty sure this has been resolved with timecop

**Comment by katjam** [comment]
If it hasn't we'll find out when this gets verified at some point.
