### ISSUE TITLE
[Bug]: Investigate why Project Indigo events are not showing up on Trans Dimension

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1587]
## Description

This is an Outlook calendar. Events are correctly importing although all have the title "busy". Inspecting the calendar manually indicates that this is the case though - I assume some privacy settings are wrong?

However they're not showing up on the TransDimension frontend

Calendar: https://admin.placecal.org/calendars/124

Needs a bit of digging to see what's really going on here. I wonder if events are not loading with just a service area? They are very keen on not showing any more precise location than that.

**Comment by aaaaargZombies** [comment]
#1608 I might have duplicated this

**Comment by r-ferrier** [comment]
closing as we think is fixed

**Comment by ivan-kocienski-gfsc** [comment]
Verified in production

![Screenshot_2024-04-23_14-49-00](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/12dab0f0-750f-40d0-b06b-2312025ef636)
