### ISSUE TITLE
[Bug]: Unable to enter address for partner

### ISSUE THREAD

**Issue by erbridge** [geeksforsocialchange/PlaceCal#1588]
## Description

Trying to add the address for http://regard.org.uk/

## Steps to reproduce

1. Open edit partner page for Regard (https://admin.placecal.org/partners/regard/edit)
1. Enter the following details:

   ![image](https://user-images.githubusercontent.com/1027364/203570783-738dedc8-1b11-4c62-97d3-892e1091eb7a.png)
1. Press "Save partner"
1. See "The page you were looking for does not exist" error page and the address is not updated

## What you expected to happen

The address should be saved for the partner.

**Comment by kimadactyl** [comment]
@ivan-kocienski-gfsc is this fixed now?

**Comment by ivan-kocienski-gfsc** [comment]
This looks like it was due to out of date data which we have no fixed with a neighbourhood data updater task
