### ISSUE TITLE
[Bug]: Calendar update status incorrectly persists after URL is changed

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1601]
## Description

Trying to update the Yard's calendar and it's showing me incorrect older error messages

## Steps to reproduce

1. Replace the URL with a new feed
2. Press save
3. Error shows up - which is the old error
 
This does reset after next import but I think it's very confusing when people are trying to debug this

<img width="1409" alt="Screenshot 2022-12-01 at 10 24 46" src="https://user-images.githubusercontent.com/511734/205029093-f4d329f8-a123-4e9e-abc7-53e975ce8248.png">

## What you expected to happen

Errors should reset when the URL field is updated

## A/C
- [ ] When a calendar has an error message on it, changing the source URL and saving will clear that message (and any associated fields)

**Comment by ivan-kocienski-gfsc** [comment]
Verified on staging

### When a problem is present
![Screenshot_2024-04-23_15-35-37](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/7fca4510-8bd3-41d8-8083-f3f981212d19)

### When the URL is changed and saved
![Screenshot_2024-04-23_15-36-04](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/01d26b80-75b0-4a4b-8b90-6ddc4d60b245)
