### ISSUE TITLE
[Bug]: project indigo - pulling through event status instead of event

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1608]
## Description

from discord

>also - entirely unrelated - this partner (project indigo) is using outlook but the info being pulled through seems to be the event 'status' rather than event. any thoughts on what that might be?

![transdimension_screenshot](https://user-images.githubusercontent.com/6824891/206234160-95d71bef-978d-4dbf-9fcf-0f40630fc208.png)

**Comment by r-ferrier** [comment]
might be fixed - reopen/chase if not
