### ISSUE TITLE
[Bug]: events being added multiple times

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1622]
## Description

From discord

<img width="1038" alt="londonFriendMultEvent" src="https://user-images.githubusercontent.com/6824891/207881234-c1c3767b-a0e6-4cf2-afc4-6dda30b3bff4.png">

https://transdimension.uk/partners/135

https://admin.placecal.org/calendars/100/edit

>  Error: Internal database error for calendar London Friend (id 100): Validation failed: Events is invalid 

```

Recent Updates
Dec 15, 2022 12:00 - Today

    Events Created
    Stonewall Housing - Dec 15 2023 (Fri)
    LGBTQ+ Drop-In Café - Dec 15 2023 (Fri)

    Events Updated
    Atypiqueers Winter Holiday Party -
        Dates: 5 dates between Sat, Dec 17, 2022 and Sat, Dec 17, 2022
        Changes: summary, summary_html

    Events Deleted
    Turning Point (in-person) - Dec 14 2022 (Wed)
    Conversation English Classes (in-person) - Dec 14 2022 (Wed)
    Opening Doors London (in-person) - Dec 14 2022 (Wed)
    Atypiqueers @ the LGBTQ+ Community Centre - Dec 14 2022 (Wed)

```

I downloaded their `.ics` file into thunderbird and there's only one listing for that event there so presume it's not a mistake on their end.

## Steps to reproduce
attempt to import calendar / view https://trans-dimension.placecal.org/partners/135 or https://transdimension.uk/partners/135

## What you expected to happen

events on placeCal match those in partners calendar

## Platform (if relevant)

What device and browser were you using?

**Comment by aaaaargZombies** [comment]
need to see if it's effecting other calendars / events

**Comment by katjam** [comment]
@geeksforsocialchange/developers I have a vague recollection that we did something about this, maybe elsewhere?

**Comment by aaaaargZombies** [comment]
duplicate of  #2287
