### ISSUE TITLE
[Bug]: LGBT Hero events not pulling through

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1630]
## Description

> LGBT Heros events don't seem to be pulling through since 23 Aug (noted at GI catch-up)

## Steps to reproduce

check https://trans-dimension.placecal.org/partners/163 / https://transdimension.uk/partners/163

## What you expected to happen

To see the events featured on their site appearing on placecal / transdim

https://www.lgbthero.org.uk/Pages/Events/Category/upcoming-hangouts

## Notes

I thought I'd fixed what was a temporary issue here ( #1614 ) but obviously not, a collection of issues that might relate to the problem.

- #1256
- #1539 PR #1541
- #1596
- #1614 
- #1616

**Comment by ivan-kocienski-gfsc** [comment]
So in the ticket the source URL is https://www.lgbthero.org.uk/Pages/Events/Category/upcoming-hangouts
But on PlaceCal the calendar (id 108) is pulling from https://www.eventbrite.co.uk/o/lgbt-hero-17463624603

So the LGBT hero site has current events but the eventbrite site has only past events
