### ISSUE TITLE
add calendar error dashboard for developers?

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1643]
# Problem

Calendars often get stuck in the `in_worker` state or are in the `error` state. This stops them from being imported properly and affects end-users who are trying to get their work done.

## User story

As an internal developer who is maintaining platform stability I would like to have a place I can go to that clearly lays out which calendars are having problems and any relevant details that will aid in my investigations.

## Sketch of solution

When visiting the "Importer Status" dashboard I would like to see a list of Calendars that are in error state (with links to the calendar pages) with useful information that will help me debug a problem.

## Acceptance criteria

- [ ] calendars with errors show up on importer status page
- [ ] determine useful info to put in the status line (like last import time, problem description, importer used, etc)
- [ ] has link to calendar

**Comment by kimadactyl** [comment]
This seems sensible. Ticket needs a bit of love though:

- user story needs an "in order that" clause
- user story is a bit too rigidly tied to one UI implementation - can you zoom out a bit and define the larger problem?
- what is the useful information?
- what has a link to calendar?

**Comment by kimadactyl** [comment]
Alternate implementation here is to add a status filter to the [calendars index](https://admin.placecal.org/calendars) for example

**Comment by aaaaargZombies** [comment]
Is there an error log, I think some of the calendars cycle from error / in_queue states

**Comment by kimadactyl** [comment]
suggested new title: "add calendar error dashboard for developers?"

i think this prob needs a (pencil) sketch first too at least?
