### ISSUE TITLE
Calendars with dead source URLs should show this to the user

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1648]
# Problem

Calendars can have URLs that are unreachable/unsuccessful (404/501/401) that causes them to move in to "error" state but that state is also used to catch every other error mode the calendar can encounter. 

## User story

As a partner/site admin I would like to see clearly when my calendars are pointing to "unsuccessful request" URLs so I can change the URL or delete the calendar.

As a developer/platform admin I would like to see which calendars are "unsuccessful request" so they don't show up in the list of error-ing calendars (it is not an error that comes from PlaceCal itself).

## Acceptance criteria

- [ ] as an end user: calendars with bad source URLs have a distinct and clearly worded message indicating that the URL is not working.
- [ ] as an admin: calendars that have bad source URLs don't show up on the list of calendars with errors (as it is not an internal problem).

## Implementation notes & questions

- [ ] Put new state on calendar
- [ ] Put new transition method and filter method
- [ ] In admin calendar edit/show implement "bad url" error box UX
- [ ] In the developer job page verify calendars in this state don't show up.

**Comment by kimadactyl** [comment]
This looks good I would just reframe "dead" as "unsuccessful requests" or something? a minor note!
