### ISSUE TITLE
[Bug]: RestClient::BadGateway: 502 Bad Gateway

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1658]
https://rollbar.com/gfsc/placecal-production/items/243/
https://rollbar.com/gfsc/placecal-production/items/205/
https://rollbar.com/gfsc/placecal-production/items/247/
https://rollbar.com/gfsc/placecal-production/items/253/
https://rollbar.com/gfsc/placecal-production/items/256/

Look like the same problem

```
File /app/app/jobs/calendar_importer/parsers/eventbrite.rb:26 in download_calendar
File /app/app/jobs/calendar_importer/parsers/base.rb:32 in calendar_to_events
File /app/app/jobs/calendar_importer/calendar_importer_task.rb:52 in calendar_source
File /app/app/jobs/calendar_importer/calendar_importer_task.rb:56 in event_data_from_parser
File /app/app/jobs/calendar_importer/calendar_importer_task.rb:15 in run
File /app/app/jobs/calendar_importer_job.rb:47 in perform
```

**Comment by kimadactyl** [comment]
Yeah i think there's a way to link tickets in Rollbar if they're the same if that helps

**Comment by ivan-kocienski-gfsc** [comment]
Should we ignore the bad gateway problem (as the service is intermittent) or flag it as a bad_source? i think the proper way to solve it would be to have a retry-count (this could be true of all bad_source calendars) and if the calendar is dead after 5 goes then it is flagged as a bad_source, but that is just me over-engineering the solution.

**Comment by kimadactyl** [comment]
Retry count sounds complicated, I think just flagging it bad source for now sounds fine?

**Comment by ivan-kocienski-gfsc** [comment]
I thought that at first but it seems we have a few calendars that do this fairly often so if the problem occurs then we shouldn't halt all future calendar imports. So we are ignoring that specific problem so we can still get future events for the calendar

**Comment by kimadactyl** [comment]
Yeah - it should try and import again and not get blocked for sure
