### ISSUE TITLE
[Bug]: Partner created without service area or address

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1663]
## Description

A partner has been created without either piece of location info. I didn't create it so not sure how.

https://admin.placecal.org/partners/oshun-abi-dougill/edit

https://admin.placecal.org/partners/oshun-abi-dougill/edit

## What you expected to happen

This should be impossible - PlaceCal should require either an address or a service area

<img width="1255" alt="Screenshot 2023-01-30 at 15 26 30" src="https://user-images.githubusercontent.com/511734/215519518-6fbbb4b3-dcb3-4500-a7a1-bca54fe82925.png">

**Comment by ivan-kocienski-gfsc** [comment]
[We only validate partners have an address or service area on create, not save](https://github.com/geeksforsocialchange/PlaceCal/blob/899bcdf3306981edf7f1163248f8b3f645ce1c75/app/models/partner.rb#L92).

**Comment by kimadactyl** [comment]
Ah ok so you think it was made without one, then edited to remove it?

**Comment by ivan-kocienski-gfsc** [comment]
I think it was made with a Service Area, saved and then at a later time the Service Area was removed.
