### ISSUE TITLE
Neighbourhood seed data loading

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1664]
## Description

As a developer who wants to rebuild a clean PlaceCal database I would like it if Neighbourhoods were populated with the correct records and relationships.

## Motivation

As it stands our `bin/setup` onboarding script is incomplete (and it doesn't reset the database). If I try to do anything in PlaceCal (like make a partner or a calendar) it won't work without the correct neighbourhood information.

**Comment by aaaaargZombies** [comment]
just had to rebuild my database

```
rails placecal:load_pht_category_tags
```

I ran `bin/setup` first which gave some output saying I had an admin account set up as in the readme but once dumping the database it was gone, presumably we need to get data from production first.

**Comment by katjam** [comment]
Closed with another PR solution in linked PR not needed.

**Comment by ivan-kocienski-gfsc** [comment]
Verifying that this does not happen in the setup script but there is a rake task for updating the neighbourhood info that can be run after a new database has been built
