### ISSUE TITLE
create PartnershipTag, update admin UX to show what kind of tag is what on Sites/Partners

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1690]
As an admin that is managing my Partners and Sites, I would like to see and change the tagging of these resources.

(note: This is just a specialisation of what is going on in the Tag model already)

## Acceptance Criteria
- As an admin
    - I should be able to create a Partnership
    - I should be able to assign a Partnership to a Site
    - I should be able to modify my Partnerships (on either Partner or Site page).

## Notes
Partnerships need to require a Site be assigned to them.
Facilities should not be allowed to have a Site assigned to them.

**Comment by ivan-kocienski-gfsc** [comment]
One question I have is: when showing a Partner or a Site how do we let users pick Facilities and Partnerships? Should it be all mooshed together into the one Tag select box or are we going to have separate boxes for Facilities and Partnerships?

**Comment by kimadactyl** [comment]
I think this is low priority - only we edit the site config at the moment so as long as it works we well as it currently does that's totally fine

**Comment by kimadactyl** [comment]
so to rephrase - i don't think any of this needs any additional functionality to how it works now but yes we should test it does still work?
