### ISSUE TITLE
Change instance homepage to have free text and remove current pro forma

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1699]
## Description

Setting up project-based sites like this and our default text is a bit too much, it's not flexible enough:

https://consciouscollectivemcr.placecal.org/

"PlaceCal is working to make Manchester a better connected neighbourhood.

We're working with [local organisations](https://consciouscollectivemcr.placecal.org/partners) and [places](https://consciouscollectivemcr.placecal.org/places) to create a great calendar of everything that's on in Manchester."

We should change this to just be a few free text boxes. Maybe it can autofill with this text.

We prob also need to limit the length of this significantly.

## Acceptance Criteria

- [x] #1983
- [ ] Before starting this do some work to work out what text groups would like to have here
- [ ] All text for home pages is changable
- [ ] Current sites that do use the instance text dont get left broken
- [ ] Sensible validations are used
- [ ] Consider using ActionText for this to allow bold/italics etc

**Comment by r-ferrier** [comment]
Conscious collective would also like their logo to be larger so have added this to the above AC

**Comment by kimadactyl** [comment]
Opened #1943 to track the logo thing so removed it from here!

**Comment by kimadactyl** [comment]
I think this has been done
