### ISSUE TITLE
update admin partner tag select box to show all kinds of tags

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1702]
As an admin who is creating/updating a partner i would like to see which tags are of what kind so i can better tag my partner to drive traffic to my clients.

# Acceptance Criteria

For now just prefix tags in the tag selection box with the type as a string. e.g. 'category: housing', 'partnership: trans-dimension', 'facility: public-wifi', etc

**Comment by kimadactyl** [comment]
maybe use an emoji for this for brevity? Category: 📂 / Partnership: 👯‍♀️ / Facility: 🏗️? Perhaps too faddy im just worried itll get a bit unreadable if people have a few.

**Comment by kimadactyl** [comment]
Nice, looks good
