### ISSUE TITLE
[Bug]: Nil exception on production

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1705]
## Description

https://rollbar.com/gfsc/placecal-production/items/277/

>  ActionView::Template::Error: undefined method `name' for nil:NilClass

From client site: consciouscollectivemcr.placecal.org

Source line: /app/app/views/admin/partners/edit.html.erb:8
https://github.com/geeksforsocialchange/PlaceCal/blob/main/app/views/admin/partners/edit.html.erb#L8

**Comment by ivan-kocienski-gfsc** [comment]
Looks like some addresses are missing neighbourhoods, which shouldn't be possible

**Comment by kimadactyl** [comment]
hmmm

my worst fear is that our geodata is out of date and there are now postcodes which don't match up to the wards we imported

not sure
