### ISSUE TITLE
Tag admin field only shows up on Partnership Tags

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1711]
## User story

As a PlaceCal admin, I only want to see the Tag Admin field on Partnership Tags, as it's the only one it's relevant to.

## Acceptance criteria

- [ ] Tag users field shows up on Partnership Tags
- [ ] Tag users field does not show up on Category or Facility tags

## Implementation plan

_To be written by the developer_

**Comment by ivan-kocienski-gfsc** [comment]
So: as an admin who is on the edit site page i would only like to see and select from partnership tags?

**Comment by kimadactyl** [comment]
Yep!
