### ISSUE TITLE
[Bug]: Ward picker is missing

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1717]
## Description

https://admin.placecal.org/partners/oshun-abi-dougill/edit

An admin user is having difficulty with the Ward Picker (service areas) on the Partner Edit page. The js select box does not contain any neighbourhoods.

![Screenshot_2023-03-01_15-15-31](https://user-images.githubusercontent.com/109223824/222181759-fb6816e1-94d4-4498-9db5-fc76182f5be1.png)

This was happening on Windows with Chrome.

**Comment by kimadactyl** [comment]
It might be worth creating an exact copy of the account with the same settings to see if it's some weirdness there - guessing not but maybe good to rule out

**Comment by ivan-kocienski-gfsc** [comment]
Turns out this may be a problem where the user lacks any assigned neighbourhoods.

**Comment by ivan-kocienski-gfsc** [comment]
This is not a bug. Perhaps an UX enhancement that lets the user know that they have no assigned neighbourhoods would be a better solution
