### ISSUE TITLE
[User Bug]: difficulty changing email address

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1720]
## Description

An admin user cannot change their email address if the destination email address is already taken

**Comment by kimadactyl** [comment]
i think some sites say "email taken" but understand this may be a security/gdpr problem.

i think this is low priority for me but we should address it at some point!

**Comment by katjam** [comment]
It's bad practice security-wise to state that the email is already in use, and one way to get around it is to remind people when they try to sign up that they can reset their password if they think they might have an account already.

As long as the response is the same whether the email exists or not, its good from security pov. 

This goes alongside:

When they request a reset, don't give away whether the email exists.
When they attempt to log in with a non-existent email, the messaging should be that their email OR password is incorrect.

**Comment by r-ferrier** [comment]
closing as this is expected behaviour
