### ISSUE TITLE
[Bug]: Events are missing an address

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1723]
## Description

From User description "Sundance Calender - is linking weirdly and not putting the address or lining to Ebb & Flow?  Why"

Calendar https://admin.placecal.org/calendars/132/edit

Partner https://admin.placecal.org/partners/oshun-abi-dougill/edit

## Notes

I believe the problem is [here](https://github.com/geeksforsocialchange/PlaceCal/blob/main/app/jobs/calendar_importer/event_resolver.rb#L75): Basically the calendar is using the 'Event' location strategy (that only takes the address from the ICAL feed) and that value is missing (in the response as we parse it).

## Implementation Plan

The events table has a `raw_location_from_source` field. 
When importing events populate this field with the raw value from the calendar location.
When showing an event (to the guest) then first try the address field and then use `raw_location_from_source`

**Comment by kimadactyl** [comment]
This feels pretty critical - i can see on the source side of things the address is deffo there!

**Comment by ivan-kocienski-gfsc** [comment]
so it looks like the ICS feed has a location value of "Birch Community Centre" which obviously doesn't resolve to an actual address

**Comment by kimadactyl** [comment]
I can see it if I load it up in Google Calendar though. Is it anywhere else in the response?

**Comment by kimadactyl** [comment]
Not fixed - reopening 

Address not showing up here in the list: 

https://manchester.placecal-staging.org/partners/age-friendly-hulme-moss-side

Only title showing up here:

https://manchester.placecal-staging.org/events/330098

Location is indeed visible in iCal response:

```
LOCATION:Birch Community Centre\, Brighton Grove\, Manchester M14 5JT\, UK
```

**Comment by ivan-kocienski-gfsc** [comment]
I am just checking in on this on production:

Partner: I have checked the [Partner "Age Friendly Hulme & Moss Side"](https://admin.placecal.org/partners/age-friendly-hulme-moss-side/edit) and the admin page has the address set to "Manchester School of Architecture, M15 6BR" which is also what is shown on the public guest page (as you noted).

Calendar: The [calendar](https://admin.placecal.org/calendars/16/edit) has the above partner set as the partner organiser. The location policy is set to "event" and there is no default location set.

Feed: So I just checked the iCal feed (16th March 2023) and currently it has the location value of "Alternates between Hulme and Moss Side"

Event: On the event page (on localhost) the event location value is "Alternates between Hulme and Moss Side" which is pulled from the iCal feed as the calendar is using the event feed location.

I am just going to try something on staging

**Comment by ivan-kocienski-gfsc** [comment]
So this may actually be another problem altogether: when a calendar is imported and its events are created the data in the ical feed is used to create the events. BUT if the user changes the location in the ical feed our importer doesn't pick up on this because it thinks it is a duplicate event.

I will turn this into a ticket

**Comment by kimadactyl** [comment]
@ivan-kocienski-gfsc to review this tomorrow and see if done

**Comment by ivan-kocienski-gfsc** [comment]
So on production you can look up the [calendar](https://admin.placecal.org/calendars/132/edit). Drop into the console to list all the events with this calendar of which the following are found

```
331281, 180
331282, 180
326440, 180
331286, 
331287, 
331288, 
331289, 
```
(The events without a second number are missing an address)

Then visit [331289](https://trans-dimension.placecal.org/events/331289).

The address value is: Birch Community Centre (which has been pulled from the raw location field

![Screenshot_2023-04-27_16-51-14](https://user-images.githubusercontent.com/109223824/234917141-457eddf2-31c4-4f3a-9cca-19e2fb7eaf8b.jpg)

**Comment by katjam** [comment]
@ivan-kocienski-gfsc not sure if I follow this conversation properly, but I think I have proven that it is fixed for the specific case originally flagged - and that it was released to production prior to this release. If that's not the case, or you have a good way to verify, please do so.
