### ISSUE TITLE
[Bug]: Tags selector incorrectly displaying as select box not select2

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1726]
## Description

Looks like some JS not loading

https://admin.placecal.org/partners/flourish/edit

<img width="1118" alt="Screenshot 2023-03-06 at 17 51 42" src="https://user-images.githubusercontent.com/511734/223191075-104eaaa6-b7c4-471f-8914-352ba402f66f.png">

**Comment by kimadactyl** [comment]
Marked urgent as i think most people can't use these boxes to select multiple as it involves keyboard shortcuts people don't use

**Comment by katjam** [comment]
Probably due to select2 not loading properly

**Comment by kimadactyl** [comment]
i don't think we should do it now but this seems an excellent case for why we need to migrate this stuff to view_component huh

**Comment by aaaaargZombies** [comment]
ok more bothers because that controller updates a hidden input, it's updated partners without opening times to have and opening time of 

```
{{ $data.openingHoursSpecifications }}
```

This is not valid JSON and is causing the stimulus component to fail

effected partners 

```
[
  182,
  181,
  184,
  185,
  186,
  127,
  178
]
```

so plan is probably fix problem partners and set some sort of guard to prevent this happening again.

**Comment by aaaaargZombies** [comment]
so far this is the only place in the code that seems to reference that opening times format.

https://github.com/geeksforsocialchange/PlaceCal/blob/main/test/models/partner_test.rb#L152-L157

but I'm not sure how it's working its way in there in the firstplace. Flourish is a new partner and creating a partner with no `opening_times` defaults to `nil`

This results in `opening_times_data` = `"[]"` which should not be a problem for the stimulus component so I don't think that is the problem. The issue the stimulus component should not generate a string like this `{{ $data.openingHoursSpecifications }}`.

**Comment by katjam** [comment]
Verified on staging:
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/4852ef0f-b4fe-4e03-84f2-167775f119c7)
