### ISSUE TITLE
[Bug]: Site admin isn't showing the tag category

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1734]
Below tag should say "Partnership: C2 Connecting Communities"

<img width="537" alt="Screenshot 2023-03-14 at 12 25 54" src="https://user-images.githubusercontent.com/511734/225000526-1b7d8dc8-be38-4ea8-b888-edb56dae0344.png">

**Comment by katjam** [comment]
verified on staging:
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/3b3c853a-b13e-4e6e-b6ad-6976dbf7208f)
