### ISSUE TITLE
[Bug]: Partner.opening_times is somehow getting malformed

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1743]
## Description

see #1726 to show how the issue was discovered.

I was investigating why the `select2` stimulus controller wasn't working and realized that some json was not being parsed properly. It happened to be on the opening times controller. passed in at this point

`PARTNER.opening_times = "{{ $data.openingHoursSpecifications }}"`

https://github.com/geeksforsocialchange/PlaceCal/blob/main/app/views/admin/partners/_opening_times.html.erb#L4

there is a test that describes the issue here

https://github.com/geeksforsocialchange/PlaceCal/blob/main/test/models/partner_test.rb#L152-L157

## Steps to reproduce

i am unsure how to reproduce, #1742 should have corrected the existing problems

## What you expected to happen

partners should have `opening_times` = `nil` or valid json that meets this spec https://schema.org/OpeningHoursSpecification

## Platform (if relevant)

What device and browser were you using?

**Comment by aaaaargZombies** [comment]
after merging #1742  we should only have valid json or nil in that field but it is not guaranteed to meet the openHoursSpec

**Comment by katjam** [comment]
Verify whether this is still an issue

**Comment by r-ferrier** [comment]
verified on production as per last comment.
