### ISSUE TITLE
[Bug]: Can imported events change their location

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1744]
## Description

As a calendar admin I would like to be able to change existing event information in my off-placecal calendar (that has already been imported) and have that information updated on my placecal calendar.

## Steps to reproduce

1. create calendar with some events
2. import calendar
3. change event location information
4. re-run calendar import

## What you expected to happen

The new location should be added to the pre-existing events

**Comment by katjam** [comment]
Partners can set this. System behaves as expected.
