### ISSUE TITLE
Speed up the install process for new GFSC devs

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#1748]
## User story

As a GFSC dev I need to have more complete setup docs so that I can get placecal running locally.

## Acceptance criteria

- [x] The readme contains all the required steps & info to get a local version running with a working database
- [x] The readme does not contain any sensitive info

**Comment by aaaaargZombies** [comment]
## verified

hard to screen shot but the `makefile` turned this from a confusing saga into about an hour long task on my new laptop including installing rven/docker/etc
