### ISSUE TITLE
[Bug]: Fix broken parser_base_test

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#1751]
## Description

One test fails on my machine: `read_http_source raises correct exception with invalid URL`
This fails because the error messages produced differ from one environment to another.

## User stories
- [x] As a Rosie I can run tests on my local machine and they all pass

## Implementation plan
- [x] Change test to look for presence of substrings `Failed to open TCP connection to dandilion.gfsc.studio:443` and `There was a socket error` instead of asserting a complete string match

**Comment by aaaaargZombies** [comment]
verified, again hard to screenshot the absence of something
