### ISSUE TITLE
[Bug]: dataTable.destroy is not a function

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1754]
## Description

Visit the tag table see js error.
![image](https://user-images.githubusercontent.com/861172/226906133-83a4f650-36a9-4a39-890c-1016e57b2e29.png)

## Steps to reproduce

1. What you did first
1. What you did next

## What you expected to happen

What would you like to happen instead?

## Platform (if relevant)

What device and browser were you using?

**Comment by kimadactyl** [comment]
yeahh I would love to get rid of datatables, this is jquery and turbolinks fighting i think

**Comment by ivan-kocienski-gfsc** [comment]
Verified on staging

![Screenshot_2024-02-29_12-45-22](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/d415dcac-cf2e-46df-8413-775b252c940a)

(please ignore the unrelated 500 errors)
