### ISSUE TITLE
[Bug]: Patnership admin cannot see partners unless they are also neighbourhood admins for the area where partner is located

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1755]
## Steps to reproduce

1. Add partnership tag
1. Assign partnership tag to a citizen user
2. The citizen user signs in - cannot see partners

## What you expected to happen

I would expect to see my assigned partners in my dashboard

## Platform (if relevant)

What device and browser were you using?

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/226906830-c5b99569-3c12-4e63-8604-ad8a30d00e6b.png)

![image](https://user-images.githubusercontent.com/861172/226906945-972413b0-f55d-4837-b6e2-13e25d852b81.png)

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/226907277-af847c3a-c164-4bf4-9560-9081a0b3b7ff.png)

**Comment by katjam** [comment]
Won't fix as issue not arising with users. Was from when honor and I set up dummy instances.

**Comment by katjam** [comment]
Removing won't fix as this can be looked at with wider permissions areas

**Comment by ivan-kocienski-gfsc** [comment]
Confirming this is a problem that can be looked at / fixed when we perform a security / permissions audit milestone.

**Comment by kimadactyl** [comment]
Superceded by #2063
