### ISSUE TITLE
[Bug]: Publishing a site breaks /find-placecal

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1758]
## Description

Tried to publish new site (honor inner london) got 500. Not checked logs to see what the error was.

## Steps to reproduce

1. What you did first
1. What you did next

## What you expected to happen

What would you like to happen instead?

## Platform (if relevant)

What device and browser were you using?

**Comment by ivan-kocienski-gfsc** [comment]
This no longer seems to be the case (checked on localhost and staging).

**Comment by ivan-kocienski-gfsc** [comment]
This no longer seems to be the case (checked on localhost and staging).
