### ISSUE TITLE
[Bug]: Neighbourhood admins can see all users and edit their partners

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1760]
## Description

Browsing user list as a neighbourhood admin

## Steps to reproduce

1. Log in as a user with only neighbourhood admin
1. See the Global Admin menu including items in it , though editing is only possible on some fields

## What you expected to happen

Not see, nor have access to root level configuration

## Platform (if relevant)

What device and browser were you using?

**Comment by r-ferrier** [comment]
duplicate & we think is also fixed
