### ISSUE TITLE
Limit the amount of categories possible to tag a partner with to 3

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#1766]
This has been generated by one of the acceptance criteria from #1653:

>  I can assign up to 3 categories to any partner I manage

**Comment by kimadactyl** [comment]
What's the "needs evidence" tag for?

**Comment by kimadactyl** [comment]
ahha yeah np - this was a request from the planning meeting we had about it with the place health team, it is a bit plucked out the air but we mostly wanted to avoid the situation that tranzwiki has for e.g.: https://www.gires.org.uk/tranzwiki/regions/uk-wide/?tags=all

**Comment by aaaaargZombies** [comment]
relates to work done in pr #1653
