### ISSUE TITLE
[Bug]: London Cruisers calendar woes

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1772]
## Acceptance Criteria

- [ ] London Crusers events all have London. Hoxton as a default location
- [x] When Van logs in with their user account, they can see London Cruisers in their partner list

## Description

I’ve problems with the drop box “default location” while trying to import an event from my google calendar. The drop box is blank and no matter what I type, it returns “no results found” Please advise.

I thought I was able to override the prompt and post my events - they showed up on placecal. However, I can't see them any more, and looks like my club London Cruisers no longer shows up on the partners list.

I think this is happening because right now it only allows you to assign a default location that your user account manages

**Comment by katjam** [comment]
Waiting for Van to get back with a default location.

**Comment by katjam** [comment]
Van got back with Hoxton as location

**Comment by kimadactyl** [comment]
Just to note that's a neighbourhood not a location (i think?) - so prob non trivial - ugh!

**Comment by r-ferrier** [comment]
Made a start on investigating this - it looks like there's no address associated with the partner account & I'm wondering if this could be causing problems - just been refreshing my local setup to test this further. Have unassigned myself in case anyone else fancies it before I'm back again!

**Comment by r-ferrier** [comment]
After looking into the other related issues I still think this one arises from them having no address - without an address for themselves, they cannot select a default location for events . . . unless I am completely misunderstanding this. Is there a reason they don't want to have an address, and in this case, do I need to create a new partner for them to just house an address they can select? Is there a reason they need to have a default location? I think I'm maybe just missing some context for this overall!

**Comment by kimadactyl** [comment]
I think you're right and this is more about giving them proper feedback what's going on?

**Comment by r-ferrier** [comment]
Ok, great. Do we have an email address or is there an active thread about this anywhere? I've had a look but couldn't find anything in the pht-tech-support channel for this one

**Comment by r-ferrier** [comment]
I can't find any mention of Van or London Cruisers in any of our channels & I can't remember which GI-related channel specifically this is related to - if someone could just let me know who I should be @-ing and in which channel, or provide me with an email address, I'm happy to provide some quick support to them

**Comment by katjam** [comment]
I'll look. It's probably a thread with Georgie

**Comment by katjam** [comment]
I'll look. It's probably a thread with Georgie

**Comment by r-ferrier** [comment]
Am closing - have replied to email thread & hopefully it's with them now - will re-open if they get back to me and we need to do further work
