### ISSUE TITLE
Frontend renders backslash before apostrophes

### ISSUE THREAD

**Issue by honor-gfsc** [geeksforsocialchange/PlaceCal#1773]
Noted that in event titles the frontend neighbourhood sites render a backslash before apostrophes, see screenshots 
Appears consistent across multiple neighbourhood calendars
<img width="430" alt="Screenshot 2023-03-28 at 11 45 05" src="https://user-images.githubusercontent.com/127757676/228213217-0583c5f9-0296-4107-8d49-f864e6464271.png">
<img width="603" alt="Screenshot 2023-03-28 at 11 47 37" src="https://user-images.githubusercontent.com/127757676/228213223-cc731aab-c3e1-4e34-bf55-6321941e9836.png">

Edited to add
Links to examples: 
https://hulme.placecal.org/events/295619
https://hulme.placecal.org/events/292915
https://hulme.placecal.org/events/288019
https://moston.placecal.org/events/279503
https://moston.placecal.org/events/279925

For what it’s worth, I couldn’t find an example without the backslash with an apostrophe, but this doesn’t mean there aren’t any examples out there. 

## Process

- [x] Fix bug
- [x] Update staging with `dokku run placecal rails events:import_all_calendars[true]`
- [x] Verify working on staging
- [x] Update prod with `dokku run placecal rails events:import_all_calendars[true]`
- [x] Verify working on prod

**Comment by kimadactyl** [comment]
Ouch - can you link these please? It won't be everywhere, it will be per-importer so good to know what's generating these.

**Comment by honor-gfsc** [comment]
<img width="563" alt="Screenshot 2023-09-04 at 09 18 26" src="https://github.com/geeksforsocialchange/PlaceCal/assets/127757676/551f15fc-f7b5-4941-984b-a3b1e1fa0222">
<img width="557" alt="Screenshot 2023-09-04 at 09 18 33" src="https://github.com/geeksforsocialchange/PlaceCal/assets/127757676/cfe195cd-1d39-4bb4-af31-ce9c19cb4c15">
<img width="569" alt="Screenshot 2023-09-04 at 09 18 38" src="https://github.com/geeksforsocialchange/PlaceCal/assets/127757676/40cc40b8-e049-44e7-9ae3-54746f5af12b">
<img width="566" alt="Screenshot 2023-09-04 at 09 18 45" src="https://github.com/geeksforsocialchange/PlaceCal/assets/127757676/aac37d52-f914-4819-b0db-e756dfbd0489">
<img width="568" alt="Screenshot 2023-09-04 at 09 18 57" src="https://github.com/geeksforsocialchange/PlaceCal/assets/127757676/cc9bd9f8-d597-4d58-b78e-acb6f1701e26">
<img width="566" alt="Screenshot 2023-09-04 at 09 19 09" src="https://github.com/geeksforsocialchange/PlaceCal/assets/127757676/9b37265f-2285-4580-a74d-ba6bbc164d87">
<img width="556" alt="Screenshot 2023-09-04 at 09 19 13" src="https://github.com/geeksforsocialchange/PlaceCal/assets/127757676/5f4a327a-b1d9-4984-af75-e2cf96465eb0">

Noted that the issue is also present on transdimension.uk

**Comment by katjam** [comment]
Noted again:
https://norwich.placecal.org/partners/norfolk-lgbt-history-club
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/8e06a51c-e936-4aaf-83eb-be16cdccf989)

**Comment by kimadactyl** [comment]
I think this is a bit of a polish issue that makes us look bad actually while we are concentrating on new organiser experience - bumping into current milestone

**Comment by kimadactyl** [comment]
Looks like summaries are getting double-escaped. Will investigate where this is coming from.

```
 id: 362027,
 place_id: nil,
 calendar_id: 93,
 uid: "1nh7bo29fqsoh2u2ekh4ng426m_R20230305T170000@google.com",
 summary: "HHV Women\\'s Training",
 description: [...]
```

**Comment by kimadactyl** [comment]
This is **not verified** on staging. Unsure if that's because old events don't get overwritten on import or if the bug is outstanding.

Reopening, lets see how it looks in a few weeks.

<img width="1059" alt="Screenshot 2024-09-03 at 12 03 18" src="https://github.com/user-attachments/assets/5f991696-e90e-4d22-bd80-248fe244f742">

**Comment by kimadactyl** [comment]
Ahha - there's a `force_import` option that overwrites events. Confirmed working - this takes a while to run and will need running on prod. Leaving open as a reminder until its done.

<img width="1089" alt="Screenshot 2024-09-03 at 12 54 14" src="https://github.com/user-attachments/assets/892321c4-3bb9-4aba-ba9c-411f57a5a754">
