### ISSUE TITLE
[Bug]: Unclear permissions around system tags

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#1776]
## Description

While working on #1767 I noticed that the two tags with a type of `Facility` in our production copy db are currently also system_tags. They cannot be assigned/removed from a partner from the tags interface, but partners can be assigned/removed from these tags in the partners interface. I think the permission to edit a partner relationship to a system_tag should be the same in both places, but not sure which is correct.

**Comment by kimadactyl** [comment]
The only thing system tags are meant to do is stop you accidentally editing them! Its just a failsafe as the IDs are hard coded

**Comment by katjam** [comment]
I think we should remove this extra complexity. Is there a way to make sure IDs are not hardcoded? Only roots should be able t edit any tag - so hopefully this mitigates the issue slightly also. It's confusing having a tag called `system_tag` that means `read only`.

I agree also that if other tags can be added / removed in both directions *add remove partner on tag & *add remove tag on partner, then Facility tags should not be any different.

**Comment by kimadactyl** [comment]
We could just remove it yeah, esp if only roots can edit it.

Not making it hard coded means adding a pretty big feature - i.e. making the internet access / wifi blocks on the partner homepages something as part of a "facilities" meta info feature or something.

Prob is right now if you change the name of those tags it will just 501 when you visit the homepage

**Comment by kimadactyl** [comment]
Is this now resolved indirectly @r-ferrier?

**Comment by r-ferrier** [comment]
I guess so? With the work @aaaaargZombies did?

**Comment by kimadactyl** [comment]
Superceded with better tickets
