### ISSUE TITLE
Category filter has a "show all" or "clear filter" option

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1778]
No way to unset this once set

<img width="250" alt="Screenshot 2023-03-30 at 15 42 10" src="https://user-images.githubusercontent.com/511734/228873053-f5252358-4399-4ae2-9553-cdc6a45de77f.png">

**Comment by katjam** [comment]
@aaaaargZombies I'm trying to verify on staging. Am I looking in the wrong place?
https://manchester.placecal-staging.org/partners
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/9ac4fb8d-cf16-49c8-817a-3f84b850e400)

**Comment by katjam** [comment]
I found it - you actually have to submit the filter before you can reset & you have to re-open the dropdown to do so. I think this is not ideal. I'll add to https://github.com/geeksforsocialchange/PlaceCal/issues/1906 but I also think we could consider fixing now.

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/1fc5f557-d167-4128-8a0b-ec56920a6813)
