### ISSUE TITLE
URL route contains partner category and options if selected

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1779]
## User story

As someone wanting to link a set of filtered partners, I want the URL to be pastable to someone else in order that we both see the same thing when the link is shared

## Acceptance criteria

- [ ] URL bar has params in it when partner filter is used

## Implementation plan

Having reviewed the code I have the feeling this could do with a bit of a tidy up
- moved filter code into a concern (the same pattern as other filters on the site)
- moved form into partial
- changed form over to a GET
- moved filter logic from /partners/tag into filter
- removed unused action
- put in unit tests for filter class
- put in integration tests covering the UX

**Comment by katjam** [comment]
Verified on staging. Raised issue for improvements #https://github.com/geeksforsocialchange/PlaceCal/issues/1906

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/882461d4-4353-4ed5-95d9-85a7734beeed)
