### ISSUE TITLE
Production build environment differs from staging

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1783]
## Description
We had an issue releasing to production because of a mismatch in node versions.

## Motivation

Our build environments need to match in order that we can be certain that the released code is identical, so that we can rely on testing in development and staging environments.

It appears that for the testing part of release process, it is using nodenv & the expected version but when it comes to the deploy / dokku release, it is not.

## Mitigated during 0.14.2

- Rolled back expected node version v16.13.1
- Rolled back lint-staged version
- Recreated yarn lock
- Pushed to staging
- Pushed to production

## Consider fixing
- Make sure all environments use the node version configs
- Turn off renovate
- Update INSTALL.md so it does not refer to stuff we no longer use (like travis)
- Think about why dev deps would be installed at all during production build process

**Comment by katjam** [comment]
We tracked the problem to thie renovate upgrade
![image](https://user-images.githubusercontent.com/861172/229078100-ea02bd44-1d4f-4246-91e3-05e3d11be31b.png)

Which caused this error:
![image](https://user-images.githubusercontent.com/861172/229078309-d8fa517a-1ec4-4655-9a3e-c9edc11d1f2a.png)

**Comment by katjam** [comment]
Seems to be using defaults it can find - maybe we can specify. This info from build logs at https://github.com/geeksforsocialchange/PlaceCal/actions/runs/4573700543/jobs/8074444478
![image](https://user-images.githubusercontent.com/861172/229090907-2141c004-7066-4579-99ca-0477a6404fb0.png)

**Comment by r-ferrier** [comment]
Example renovate PR that will break production in its current state: https://github.com/geeksforsocialchange/PlaceCal/pull/1787

**Comment by kimadactyl** [comment]
Gonna just say I think disabling renovate is a terrible idea - this is how we end up with real long term problems, getting renovate in has been a huge plus for the codebase over what we had before and I don't think we should backtrack. Our code should deploy properly on our dev environment. We should stop dependabot and renovate fighting, though.

It is also possible to add in renovate rules to just stop node updating - this is the route i would want to go if we need a quicker fix.

**Comment by kimadactyl** [comment]
This is prob scope creep for this ticket too but I would love it to be easier to sync staging to the current state of production. Like we should be dealing with the latest data in prod as close as possible. This would cover database, assets on disk, ssl certs. Potentially this could be something scriptable at the Digital Ocean level - not sure.

**Comment by r-ferrier** [comment]
Ok so this is fixed by #1846 BUT it will get out of step again with our other node versions as long as we allow anything to auto update our node version so I think we just need to stay on top of this when doing releases - I'm going to add a note to the release file & the readme to make sure the engines node version matches the node version config. Why heroku can't also use this & needs it specifying in another separate place is beyond me but there ya go.

**Comment by kimadactyl** [comment]
Maybe do a one-off npm update so renovate starts working again?

**Comment by r-ferrier** [comment]
verified in https://github.com/geeksforsocialchange/PlaceCal/actions/runs/4928511843/jobs/8806968727

This is the `Deploy to placecal-staging.org` step from line 63 of the [test and deploy workflow](https://github.com/geeksforsocialchange/PlaceCal/blob/d57e0b86a7857a07147720955ae7b9669f37c816/.github/workflows/test-and-deploy.yml)

![Screenshot 2023-05-25 at 11 35 10](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/9a31a155-6eb3-4419-90d0-dcb3aeeea080)
