### ISSUE TITLE
Ruby v2 nearing EOL (Dec 2023)

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1786]
## Description
Upgrade to Ruby v3

## Acceptance Criteria

- [ ] Ruby version 3 or higher is specified in `.ruby_version` and `Gemfile`. Running `ruby --version` in PlaceCal directory returns version indicating such.

## Motivation
![image](https://user-images.githubusercontent.com/861172/229094155-d90c1623-4010-41f3-b075-11cab197fb82.png)

**Comment by kimadactyl** [comment]
We should prob do this as part of https://github.com/geeksforsocialchange/PlaceCal/issues/1110, honestly it's prob time to just be on Rails 7 so we don't get more of this kinda thing

**Comment by kimadactyl** [comment]
See also https://github.com/geeksforsocialchange/PlaceCal/pull/1157

**Comment by r-ferrier** [comment]
verified in the code - we're now on 3.1.2

https://github.com/geeksforsocialchange/PlaceCal/blob/6bfea42e68bdea5ecf96856058b782ee4ffd76a5/.ruby-version#L1
