### ISSUE TITLE
Add logo for conscious collective & check birch community centre calendar import

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1789]
## Acceptance Criteria

- [ ] I can see the  logo in the site header
- [ ] I can see the logo in the site footer
- [ ] I can see the banner image on the home page
- [ ] I can see the logo & banner in the site edit page
- [ ] The logo colors & aspect ratio don't jar too much - Chose Orange theme

## Description

Request from discord 22/03/23

- [ ] Once complete, follow up in discord

Hi sorry for the late reply, the person who was originally working on some logo-type stuff has been really busy so I've just knocked together a couple of things we can put on for now. Not all the events are at the birch community centre, and not all the birch community centre events are relevant to us. It'll probably be a trial and error thing to figure out exactly which calendars need pulling from because I imagine there could end up being some overlap between the event facilitators and venue spaces

small update - the address issue is a bit of a confusing one and a bit of an existential q about how placecal works. we are on it but taking a couple weeks break from placecal as we've gone a bit hard on it. if you continue to add partners and calendars we will get it all fixed eventually tho - and remember to send us logo + background image whne youre ready

a bit more context here - if all the events are at the birch community centre then they should prob be imported from a birch community centre calendar - this is a wild ride tho lol https://www.birchcommunitycentre.co.uk/news-events/
[Birch Community Centre](https://www.birchcommunitycentre.co.uk/)
[Events - Birch Community Centre - Our Latest News](https://www.birchcommunitycentre.co.uk/news-events/)
News - The latest news from Birch Community Centre, Brighton Grove, Manchester, M14 5JT
Events - Birch Community Centre - Our Latest News
(we are still going to fix it just a bit more explanation about why its not working now, placecal currently expects all addresses to be known to it)

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/229504732-d235072b-45a6-4761-88da-4d3eec3c9e16.png)

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/229504755-3b90354e-bf8a-45a0-aaf2-eb7c35a35b8d.png)

**Comment by katjam** [comment]
Asked in discord: Let me know if we want to do more work here - maybe a transparent background on the header logo (and footer) if that works with brand guidelines and/or make the hero banner a little lighter so we can see the text better?

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/233087906-7102b2f5-7749-4128-9011-d01c95593074.png)

**Comment by r-ferrier** [comment]
![logoNoBG](https://user-images.githubusercontent.com/46496391/235871613-5b12b420-d9f9-4afd-8c85-df856a576817.png)

![229504732-d235072b-45a6-4761-88da-4d3eec3c9e16](https://user-images.githubusercontent.com/46496391/235872328-a8ca06d7-5aca-446a-9183-af81b6de39d8.png)
 
They want the header to be a little bit more faded and a larger, different logo adding - attached here. (I've knocked the original back by 15%)

**Comment by katjam** [comment]
verified in production. This is a DB thing.
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/fc5d1943-1e3a-46b4-9196-c0fc77a7605a)
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/f0417912-e25e-4bfa-a129-fed41c75a7d1)

**Comment by katjam** [comment]
I'm not sure about the Birch Calendar part of this ticket. Will follow-up with Rachele in discord if it's not logged elsewhere.
