### ISSUE TITLE
[Bug]: Enforce full domain in site settings

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1791]
## Description

Needs to have https:// in front of it - otherwise gets generated as a relative link.

## Acceptance Criteria

- [ ] Domain needs to include protocol in the site settings

## Implementation Notes
- Whatever is easiest - automatically add https:// if it isn't there on save or give the user a hint and prevent saving if it isn't there.

GOOD:
![image](https://user-images.githubusercontent.com/861172/229543346-8d4f6177-4885-4008-a650-05d98fa1a985.png)

BAD:
![image](https://user-images.githubusercontent.com/861172/229543519-d759d69a-4194-473c-b81f-31092f060b1d.png)

**Comment by ivan-kocienski-gfsc** [comment]
Just reviewing the PR attached to this and I think this is a bad solution: URL domains do not have the protocol part on them and it should be up to us to prefix the protocol when we form the URL for presentation.

**Comment by ivan-kocienski-gfsc** [comment]
Verified on staging

![Screenshot_2024-01-31_15-03-52](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/928f180e-eaaf-4f4f-99ba-f6b3d6904d95)
