### ISSUE TITLE
[Bug]: Root users cannot see all sites

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#1792]
## Description

Rachele at PHT can no longer edit the sites they need to edit, because root users can only see every site if they do not have admin permissions for those sites. We need to restore root users' ability to see all sites. This ability was modified in order to fix #1746.

## Steps to reproduce

1. Sign into admin as a root user who is designated as an admin for 1 or more sites
2. View sites tab

## What you expected to happen

I expect to see all sites but instead I can only see those I am designated as an admin for

## Implementation thoughts

Need to change this but make sure the sites shown on the dashboard remain limited.

## Acceptance criteria

- [ ] I am a site admin for two sites & also am a root user, in sites I can see every site, but in dashboard I can only see my two sites
- [ ] I am not a site admin for any site & also am a root user, in sites I can see every site & in dashboard I can see every site.

**Comment by katjam** [comment]
Verified on staging - a root with site admin on 2 sites:
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/f5b7cd08-7bba-4ee7-8502-72223f69d521)
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/84481961-5251-4d05-890c-ae49f5e8bca4)

Just root:
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/3dc59368-ff74-4b13-b581-f42778bc4d6d)

**Comment by kimadactyl** [comment]
Reopening to double check as it seems to be a cause of this: https://github.com/geeksforsocialchange/PlaceCal/issues/1964

**Comment by katjam** [comment]
Closing as https://github.com/geeksforsocialchange/PlaceCal/issues/1964 has been fixed
