### ISSUE TITLE
[Bug]: Making a partner with the postcode "EC1V 2NX" doesn't work

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1808]
## Acceptance Criteria

- [x] If a postcode is not found in our data, the person inputting the address gets a message to explain that

**Comment by r-ferrier** [comment]
From what I can see this already happens - screengrab attached here.

![Screenshot 2023-04-27 at 12 17 59](https://user-images.githubusercontent.com/46496391/234846879-c106bec2-94cf-402a-809e-6635b4fb0ddc.png)

Did we want a different message to this, or a flash warning, or are we happy with this as is?

**Comment by kimadactyl** [comment]
I think this just needs to be clearer it's our fault! This makes it sound like user error atm.

Is there a temporary workaround we could suggest too? I wonder if there's a way to get "nearest working postcode" somehow?

**Comment by ivan-kocienski-gfsc** [comment]
I think we'd have to modify the model validation so that it does a lookup and gets a valid response BUT if we then don't find a neighbourhood we can have a different message

**Comment by ivan-kocienski-gfsc** [comment]
So the line in question is [here](https://github.com/geeksforsocialchange/PlaceCal/blob/644e8978012f60800ff44b2e59b3f416cfff598a/app/models/address.rb#L88) do we have a better way of describing this problem?

Something like- "This postcode has been found but could not be mapped to a neighbourhood at this time"

**Comment by ivan-kocienski-gfsc** [comment]
As per Kim's suggestion it is possible to get nearby postcodes by using the geo data we get back to do a "find postcodes near LAT and LONG" type search and present the alternatives to the user, but that sounds like it may involve a bit of UX engineering (to allow the selection of postcode from list)

**Comment by kimadactyl** [comment]
I wasn't suggesting anything so complicated - I was asking if there's a website we could link people to that would help them find something nearby as a stopgap. It would be quite manual but it feels a bit more constructive to suggest a workaround than just say no.

I think the error needs to explcitly say something like "postcode could not be found, this is a known bug in PlaceCal we will be addressing in a forthcoming update, please refer to [this manual page] for workarounds in the meantime"

**Comment by ivan-kocienski-gfsc** [comment]
That sounds like a simpler solution.

I have made a PR so it'd be best to put any further replies there

**Comment by katjam** [comment]
Verified on staging:
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/18414270-2785-4583-a988-9e9f99c0beb0)
