### ISSUE TITLE
Add minimum viable for our (2?) pages

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1811]
## Acceptance criteria

- [ ] #1817
- [ ] #1818
- [ ] #1819
- [ ] more TBC...

## Implementation plan

_To be written by the developer_

**Comment by katjam** [comment]
On hold because needs to be fleshed out

**Comment by kimadactyl** [comment]
Let's make the page first - then make it the root page when everyone is happy :)

**Comment by kimadactyl** [comment]
Just officially rolling that back as per our meeting!

**Comment by katjam** [comment]
Closing as the sub-issues have been made.

**Comment by katjam** [comment]
Do not need verifying as a whole - all in sub issues,
