### ISSUE TITLE
There is place that contains information about how to "get a PlaceCal" (currently Join us in main navigation)

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1819]
As a person or organisation who might benefit from a PlaceCal for their community, I need it to be clear when I land on the home page that this is a possibility, even if I hadn't considered it, and it needs to be easy for me to get started, so that I have the highest possible chance of success in starting one.

## Acceptance Criteria

- [ ] #1817 includes this action and why it is a good idea for me
- [x] (Currently the Join us Form page) makes it clear that I can start my own PlaceCal and how to do that
- [ ] #1841

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/235635046-00f13e45-edf5-498a-99a1-1c3b1397090e.png)

**Comment by studiosquid** [comment]
In the design system the updated Join us forms are essentially the same as before with some minor adjustments to the header text. Have attached the flats of the states for reference but the XD link should be more useful in terms of info. 

I also created a simpler form in the system just in case we need one so you can ignore that unless useful :) 

![1_Web 1366 – Form](https://user-images.githubusercontent.com/9461465/236182156-75ecc162-feab-4538-9175-248aac6eb33e.png)
![2_iPad Landscape 1024 – Form](https://user-images.githubusercontent.com/9461465/236182166-d0cc0024-639a-4a83-bf82-163d84ab3fc0.png)
![3_iPad Portrait 768 – Form](https://user-images.githubusercontent.com/9461465/236182169-65773959-c07d-4f56-8f07-d87517fc5858.png)
![4_320 – Forms](https://user-images.githubusercontent.com/9461465/236182175-b3ba2934-98a7-455e-b9e2-3e12ecadb7c7.png)

**Comment by katjam** [comment]
Also submitted a contact form. WIll post back when verified that it was received.

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/ac838408-1bcf-469e-8dbf-d97bd91e18a2)
