### ISSUE TITLE
Retire ward level sites

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1828]
- [x] Add in ward filter #1733 
- [ ] There are DNS redirects in place for sites that we take down (Hulme & Mosside & other manchester ward site go to manchester)

**Comment by aaaaargZombies** [comment]
this can now begin as we have the ward / neighbourhood filter

**Comment by katjam** [comment]
Won't fix until it comes up again. Ideally we want the word level sites to be active again!
