### ISSUE TITLE
The homepage contains a real life "how PlaceCal filled a need" story

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1831]
## Acceptance Criteria

- [x] There is a Trans Dimension feature block on the homepage
- [x] Logo - linked to TD home
- [x] Short description / quote 
- [ ] This is what a funded partnership PlaceCal looks like vs This is what a standard partnership PlaceCal looks like (for later)
- [x] Find out more about the Trans Dimension - TD About
- [x] Start your own link

**Comment by katjam** [comment]
At the moment, this is a little bit fulfilled by the quote

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/235899515-61b05e04-9d1b-4730-b5e4-4fafb5ab244a.png)

**Comment by aaaaargZombies** [comment]
https://github.com/geeksforsocialchange/gfsc-v3/blob/main/content/blog/2019/placecal-capabilities-approach/index.md?plain=1#L298

this section of the blog has a couple of quotes

**Comment by kimadactyl** [comment]
surely best example of this would be the trans dimension?

**Comment by studiosquid** [comment]
I think there's a question of how much of a case study it makes sense to have on the homepage, it's likely to get very wordy which we're trying to avoid I think? So maybe a good quote with a link beneath to a case study page (both being Trans Dim sounds good to me).

**Comment by ivan-kocienski-gfsc** [comment]
Why not have a punchy text with a "read more" link?

**Comment by r-ferrier** [comment]
verified

![Screenshot 2023-05-22 at 12 46 18](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/d5a0f3e8-6715-4003-91a3-84f67c61ace0)
