### ISSUE TITLE
Background tile SVG needs updating

### ISSUE THREAD

**Issue by studiosquid** [geeksforsocialchange/PlaceCal#1833]
New SVG created to tile better, SVG is attached should just need swapping. No urgency. Relates to #1824

![PlaceCal_Backing_v2](https://user-images.githubusercontent.com/9461465/235950908-3dbf63b2-908c-4609-a3ba-f69648f1de5b.svg)

**Comment by ivan-kocienski-gfsc** [comment]
Does this go in `app/assets/images/patterns/PlaceCal_Backing.svg` or `app/assets/images/home.bg.svg` ?

**Comment by r-ferrier** [comment]
verified:
![Screenshot 2023-05-25 at 11 30 33](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/48b64310-86d4-42dc-9ec4-ca5a616d2c8d)
