### ISSUE TITLE
Join us/ Start a placeCal page has correct copy

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#1841]
## Description

The join us page has copy we may wish to update.

## Acceptance Criteria
- [x] Copy for the link in the nav bar (Currently "Start a PlaceCal")  --> Get in touch
- [x] Copy for the page title (Currently "Join us") --> Get in touch
- [x] Copy for slug (Currently "Join") --> get-in-touch
- [x] Copy for subtitle (Currently "Want PlaceCal for your community, group or area?") --> Want to run PlaceCal in your community, group, or area?
- [x] Copy for description (Currently "Get in touch and let's discuss how you can join our not-for-profit social enterprise.") --> Contact us to discuss how you can join our not-for-profit social enterprise

**Proposed new copy from honor approved by Rach**

Nav bar: Get in touch
Title: Get in touch

Slug: get-in-touch (with redirect set up from join) (so https://placecal.org/get-in-touch)

Subtitle: Want to run PlaceCal in your community, group, or area?

Description: Contact us to discuss how you can join our not-for-profit social enterprise

**Comment by honor-gfsc** [comment]
Notion page for working through these ideas: https://www.notion.so/gfsc/Start-a-PlaceCal-Join-Us-Page-7eab2dbd832f47008945471fd82fc7e3?pvs=4

**Comment by katjam** [comment]
@r-ferrier I think the other places that refer to "Start a PlaceCal" will get sanity checked by @honor-gfsc in the big sweep, so I'm happy for this to be just the menu and the page itself.

**Comment by r-ferrier** [comment]
verified in #1869
