### ISSUE TITLE
[Bug]: remove Stefan's work landline

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1851]
## Description

Stefan is not the best person to contact directly about placecal

https://placecal.org/join

![Screenshot 2023-05-11 at 14-58-12 PlaceCal](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/1b9d0304-f041-4dd1-ac26-316b6979bb6c)

## Steps to reproduce

1. What you did first
1. What you did next

## What you expected to happen

What would you like to happen instead?

## Platform (if relevant)

What device and browser were you using?

**Comment by r-ferrier** [comment]
Think this got resolved by https://github.com/geeksforsocialchange/PlaceCal/issues/1872

**Comment by ivan-kocienski-gfsc** [comment]
This is verified because the issue #1827 has been verified

**Comment by katjam** [comment]
@ivan-kocienski-gfsc I think you mean #1872 and probably not a bad idea to verify here anyway since @r-ferrier said "I think this got resolved..."
