### ISSUE TITLE
content - confirm header title for nieghborhood placecals

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1861]
## Description

Title is Marks filler content for designing, someone should confirm it's fine and close the ticket or propose a replacement

> Check out a neighborhood

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/8eeaadb8-3956-465b-acf3-61d75158e3ca)

**Comment by r-ferrier** [comment]
handled in #1857

**Comment by r-ferrier** [comment]
verified in #1869
