### ISSUE TITLE
Check appearance of case study at desktop still good once content finalised

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#1867]
## Issue 

See https://github.com/geeksforsocialchange/PlaceCal/pull/1853#issuecomment-1544348993

If copy not long enough & there is a lot of whitespace or the layout looks off, remove desktop breakpoint that has content & buttons displayed side by side and instead jump straight to tablet view with logo and buttons positioned above copy

**Comment by r-ferrier** [comment]
Looking good for now BUT there may be a copy update to this next week so we may need to revisit this - leaving open for now as a chore

**Comment by katjam** [comment]
won't fix - will arise naturally
