### ISSUE TITLE
[Bug]:  Partnerships are hard coded - use is_published data instead

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#1873]
## Description

Use data in the same way as we do for neighbourhood instances

## Acceptance Criteria

- [x] The image is pulled from the logo
- [x] The summary is pulled from the tag line
- [x] The button says "[Partnership name] calendar" and goes to the events page

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/ee6f29ca-d339-4fcb-92a3-4a5cccfa7059)
