### ISSUE TITLE
[Bug]: Longer text on neighbourhood buttons will break them

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#1902]
## Description

Not a problem right now because currently published neighbourhoods all have small enough names for the buttons to look good at all sizes. But it is conceivable that we could have longer place names here in the future.

## Steps to reproduce

![Screenshot 2023-05-22 at 12 31 51](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/474bf891-7a81-483a-a262-532be94068fa)

**Comment by katjam** [comment]
Won't fix because we will notice if we add one such. The calendars are hard coded and hand selected.
