### ISSUE TITLE
This is what a funded partnership PlaceCal looks like vs This is what a standard partnership PlaceCal looks like

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#1903]
## Description

We have a case study on the home page for the trans dimension, but this is a big shiny funded partnership - we don't have anything to show off a standard partnership

**Comment by katjam** [comment]
Added as potential AC on #1911

**Comment by kimadactyl** [comment]
Closing this as we should address this as part of copy review and not predefine what we are selling (i.e. its a good idea but not sure this ticket is the way to tackle making sure it gets done)
