### ISSUE TITLE
Trans dimension case study contains a quote & text from a user perspective

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#1904]
## Description

In the final sign-off meeting it was discussed that the case study could be more effective with different copy. Currently the copy has been scraped together from other published text but David said he would get something more specific from Georgie.

**Comment by kimadactyl** [comment]
I put a suggested quote and reorder for this here: https://github.com/geeksforsocialchange/PlaceCal/issues/1911

**Comment by katjam** [comment]
closing as line item on #1911
