### ISSUE TITLE
Place-based calendars risk linking to empty events pages

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1912]
## What's the issue?

Currently the "place-based calendars" block runs the risk of not actually linking to a working calendar.

The usual process for new sites is that first, partners are added in bulk - say 20. Then people are reached out to to add a calendar feed. Usually you get 1-2 at first if you're lucky and then the rest can take many months. In some cases you won't get a calendar for ages.

Because this is linking directly to the events page and not the partners page, we run the risk of linking people to a page which is simply blank, or only 1 or 2 partner's events. 

Personally I would link the partners page as I think this is the most complete datasource for any given site but other solutions welcome.

![Screen Shot 2023-05-22 at 19 42 39](https://github.com/geeksforsocialchange/PlaceCal/assets/511734/61942c85-f77b-45c3-aa58-6ff1c89bb107)

## Acceptance criteria

- [ ] Sites with no calendars or few calendars are not linked to from the home page
- [ ] We have an answer from partners which is more important to link to (partners or events)

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
Ah - flourish and ccm dont have events but i wrote the ticket name wrong!

https://placecal.org/find-placecal

**Comment by katjam** [comment]
We do not feature those 2 sites on the homepage for the reason that they are still work in progress in terms of populating events. We might also not want to include them in the all instances list until they are ready to "go more public" or include a clear path to partners where there are no events listed.

In our testing we will hopefully uncover how people are engaging with and using the sites with no events.

Feel free to re-open and reword as a research ticket or a database fix.

**Comment by kimadactyl** [comment]
nah i think youre right, this problem will go away by the time we relaunch, no need to do anything
