### ISSUE TITLE
[Bug]: Yarn sometimes uninstalls itself

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#1915]
## Description

Related #1976 

I haven't experienced this on my machine locally but it's something that was attempted as a fix in [#1910](https://github.com/geeksforsocialchange/PlaceCal/pull/1910/commits/ca074c5fd44476c93ee6d5493f5daa6b73a339a2) but it broke on staging.

Just ticketing this for now as something to consider in the future. If we want to try adding this as a dev dependency again we need to also add the lock file and be wary that the different environments we deploy to may react differently to this.

**Comment by katjam** [comment]
Won't fix. This is a developer environment issue.
