### ISSUE TITLE
[Bug]: /calendars crashes on staging

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1921]
## Description

See https://app.rollbar.com/a/gfsc/fix/item/placecal-production/319

**Comment by ivan-kocienski-gfsc** [comment]
so it looks like the calendar view is trying to read `notice_count` from a calendar object that does not have that method.

i see this is a column in the database (not a method on the model).

so there's a migration that needs to be happen. the code on staging is newer than the code on production and that is causing a problem.

**Comment by katjam** [comment]
Do you have a quickfix plan or do you want to pair on it?

**Comment by ivan-kocienski-gfsc** [comment]
This looks like it has been fixed now (checked on staging and production)
