### ISSUE TITLE
[Bug]: Calendar error for Techno Tantrick / Clemantine Bedos

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1927]
## Description

We've added our online workshops to PlaceCal with a link to a google calendar with the dates and times. I can't see how this would show up for a potential participant though, could you please have a look and let me know if I've done it correctly as it says 'Error".

<img width="1073" alt="Screenshot 2023-05-30 at 16 52 37" src="https://github.com/geeksforsocialchange/PlaceCal/assets/861172/3ab9a34f-daac-4eec-a161-2b94bc206c5b">

**Comment by katjam** [comment]
Kim, Katja or Alfie have contact details by email.

**Comment by katjam** [comment]
Hmmm looks like the hide feature is not intended for use with confidential information. We may want to think about how we share sensitive stuff in these open repos.

**Comment by ivan-kocienski-gfsc** [comment]
I have just checked on [production](https://admin.placecal.org/calendars/139/edit) and the calendar appears to be in idle state with no errors. It doesn't look like there are any events (from the interface side of things).

**Comment by ivan-kocienski-gfsc** [comment]
This is still not failing a week later so i am closing this issue and keeping an eye on it

**Comment by ivan-kocienski-gfsc** [comment]
Has been verified as working on production https://admin.placecal.org/calendars/139/edit

![Screenshot_2023-07-26_14-12-44](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/aae8dbd4-5367-44e3-9aa3-eb09923e2fae)
