### ISSUE TITLE
Create a github template for a new site

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1954]
## User story

As a PlaceCal salesperson, I need to have a way to request new sites from the team, in order that we can get people up and running.

## Acceptance criteria

- [x] There is a github issue template for new site that has all the steps you need in to add a new site
- [x] It's kept up to date when we can do more in the UI (e.g. ssl certs)

## Implementation notes & questions

Possible template to base on here: https://github.com/geeksforsocialchange/PlaceCal/issues/1800

## Implementation plan

_To be written by the developer_

**Comment by aaaaargZombies** [comment]
## verified

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/b0b1afb5-18b1-489e-84b4-ab22731b3c76)

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/4014d8cc-c902-4ecd-b2d3-806917de1a77)
