### ISSUE TITLE
Review and remove any neighbourhood data files that are not in use

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#1955]
## Acceptance criteria

- [x] Only neighbourhood related data used by the code is stored in the repo - anything not referenced is removed (see lib/data)
- [ ] [Neighbourhood data for 2023](https://geoportal.statistics.gov.uk/search?collection=Dataset&sort=-created&tags=all(LUP_WD_LAD_CTY_RGN_GOR_CTRY)) is added to the repo

**Comment by aaaaargZombies** [comment]
## verified

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/0fca5125-a9e9-497f-bed7-76841a0783dd)
