### ISSUE TITLE
[Bug]: admin homepage takes a very long time to load

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1964]
## Description

When first signing in as an admin it takes a very long time to respond and looks like it is not working.

After signing in it took placecal nearly 12 seconds to send the page back to the user.

Kim suggests the cause is

> its slow because its too busy incorrectly calculating the events total for each site lol

## Steps to reproduce

1. sign in at https://placecal.org/users/sign_in
2. use network tab in dev tools to record if you want more details

https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/78742a19-ae45-4572-928f-764d876cfae5

## What you expected to happen

Dramatically reduced page load and possibly some indication that the site is still working and not crashed so I know to wait.

This article suggests 5 seconds as a max time limit which still seems very slow to me. https://infrequently.org/2022/12/performance-baseline-2023/#2023-content-targets

## Platform (if relevant)

What device and browser were you using?

**Comment by ivan-kocienski-gfsc** [comment]
I think the problem is in the [dashboard view](/app/views/admin/pages/home.html.erb)
```ruby
      <%= render_component 'dashboard_card',
        title: site.name,
        subtitle: "#{pluralize(site.events_this_week, 'event')} this week (#{sprintf('%+d', site.events_this_week - site.events_last_week)})",
        link: edit_admin_site_path(site),
        last_updated: site.updated_at %>
    <% end %>
```
the `subtitle` makes calls to `events_this_week` and `events_last_week` which look like
```ruby
  # Get a count of all the events this week
  def events_this_week
    Event.for_site(self).find_by_week(Time.now).count
  end

  # Get a count of all the events last week
  def events_last_week
    Event.for_site(self).find_by_week(Time.now - 1.week).count
  end
```

which in turn is calling this scope on events
```ruby
  scope :for_site, lambda { |site|
    site_neighbourhood_ids = site.owned_neighbourhoods.map(&:id)

    joins('left join addresses on events.address_id = addresses.id')
      .joins('left join partners on events.partner_id = partners.id')
      .joins('left join service_areas on partners.id = service_areas.partner_id')
      .where('(service_areas.neighbourhood_id in (?)) or (addresses.neighbourhood_id in (?))',
             site_neighbourhood_ids,
             site_neighbourhood_ids)
  }
```

so every load of the admin page makes two calls to the scope that we use on the front-end to show public users events in a site, per site. 10 sites * 2 calls = 20.

- easy solution: simplify subtitle text
- harder solution: lazy load site data (this is what a lot of modern apps do)
- harder solution: optimize query

**Comment by ivan-kocienski-gfsc** [comment]
Lazy loading partials: https://stevepolito.design/blog/lazy-load-content-in-rails-from-scratch

**Comment by kimadactyl** [comment]
It should't be showing all those sites tho, it should be showing 1-2. I think this has become un-fixed: https://github.com/geeksforsocialchange/PlaceCal/issues/1792

**Comment by aaaaargZombies** [comment]
## verified

1.17s on staging


![2023-07-26-14:10:36-screenshot](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/57005dc5-70be-4912-99bb-c0ffb84901a4)
