### ISSUE TITLE
Review data migration rake tasks / scripts

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1975]
## Description

We have a number of rake tasks and scripts that performed various data migrations at some point but are essentially dead wood at the moment.

## Motivation

Old code like this can be confusing or dangerous or just a mental burden. If they are no longer useful then they should be removed. If they are useful then they should be assessed and documented.

## To remove
- [x] `recreate_images:site` (regenerate site hero images from uploaded media)
- [x] `fixes:reset_bad_opening_times` (fix invalid json on partners)
- [x] `fixes:rename_admins_to_root` (sets all users to `root` role, DANGEROUS!)
- [x] `addresses:update_all_neighbourhood_tags` (`geocode_with_ward` all addresses)
- [x] `addresses:set_missing_neighbourhood_tags` (`geocode_with_ward` all addresses, for addresses missing a `neighbourhood_tag`)
- [x] `events:set_missing_addresses_from_place` (sets event.place, where address is nil and place is not nil)
- [x] `data:render_html_fields` (for Article, Site, Partner and Event, regenerate HTML)
- [x] `placecal:load_pht_category_tags` (is duplicated in seeds, i think this was used to load the initial tags when that table was created)

Parts of the neighbourhood update script that we ended up not using:
- [x] `placecal:bulk_lookup_address_postcodes`
- [x] `placecal:verify_address_postcodes`
- [x] `placecal:capture_site_relations`
- [x] `placecal:verify_site_neighbourhoods`
- [x] `placecal:find_obsolete_neighbourhoods`
- [x] `placecal:find_broken_addresses`

Two ways of generating documentation from code (do we use either?):
- [x] `doc:generate`
- [ ] `yard`

**Comment by ivan-kocienski-gfsc** [comment]
## Rake tasks


lib/tasks/fixes/partners.rake
- `fixes:reset_bad_opening_times`
  updates malformed opening_times data

lib/tasks/fixes/users.rake
- `fixes:rename_admins_to_root`

lib/tasks/addresses.rake
- `addresses:update_all_neighbourhood_tags`
- `addresses:set_missing_neighbourhood_tags`
- `events:set_missing_addresses_from_place`

lib/tasks/data.rake
- `data:render_html_fields`

lib/tasks/db.rake
- `db:dump`
- `db:dump:table`
- `db:dumps`
- `db:restore`
- `db:sync_prod_staging`
- `db:dump_production`
- `db:restore_local`
- `db:restore_staging`
- `db:dump_production_and_restore_other`
- `db:get_files`
- `db:info`

lib/tasks/doc.rake
- `doc:generate`

lib/tasks/events.rake
- `import:scan_for_calendars_needing_import`
- `import:all_events`
- `import:events_from_source`
- `import:past_events_from_source`
- `import:purge_papertrail`
- `import:refresh_online_addresses`

lib/tasks/neighbourhoods.rake
- `neighbourhoods:import`

lib/tasks/placecal.rake
- `placecal:load_pht_category_tags`
- `placecal:bulk_lookup_address_postcodes`
- `placecal:verify_address_postcodes`
- `placecal:capture_site_relations`
- `placecal:verify_site_neighbourhoods`
- `placecal:find_obsolete_neighbourhoods`
- `placecal:find_broken_addresses`

lib/tasks/recreate_images.rake
- `recreate_images:site`

lib/tasks/workers.rake
- `workers:purge_all`
- `workers:inspect_errors`
- `workers:sync_state`

lib/tasks/yard.rake
- `yard`

**Comment by r-ferrier** [comment]
reopening as the linked issue is the address
