### ISSUE TITLE
[Bug]: add yarn to package.json

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#1976]
## Description

Related #1915 

So it stops uninstalling itself.

## Steps to reproduce

1. `npm install yarn`
2. `make` (specifically `rails test:system`)
3. *yarn uninstalls itself*

## What you expected to happen

Not to uninstall yarn.

## Platform (if relevant)

javascript / node / npm / yarn

**Comment by ivan-kocienski-gfsc** [comment]
Will add a note in the README about this.

**Comment by katjam** [comment]
Won't fix on the basis that we should maybe just use npm instead?
