### ISSUE TITLE
Clean out broken Addresses

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2005]
## Description

There are 1,037,176 addresses of which 1,037,017 have no partner (only 159 have partners) and 14 have no address.

Some addresses 
- have bad postcodes and should be deleted. e.g. 'M15', 'M16', 'M144' and 'UK'.
- are missing neighbourhoods
- are missing partners

---

## notes

- events can have address
- it looks like some addresses are being remade (maybe by the importer) 1 address has around 700,000 duplicates
- requires research to see why we have to many and come up with a plan to remove as many as possible

**Comment by r-ferrier** [comment]
verified on staging: 

<img width="917" alt="Screenshot 2024-02-27 at 16 44 49" src="https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/e3670838-8658-46b0-a7f7-b3c2173774e7">

We need to schedule this to run on production post release. Will add a task into the sprint db on notion to cover this.

**Comment by r-ferrier** [comment]
https://www.notion.so/gfsc/027-e8f8fc29f1a144e29e29e171d9830843?p=93e5c2b8dd6f42dbafb4d25ae72bbdd0&pm=s
