### ISSUE TITLE
Neighbourhood updating phase 2

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2012]
Neighbourhood updating is complicated.

So far we have added a column to the neighbourhood and written a script that will insert/update neighbourhoods with new ONS data.

Things left to do:
- #1962 
- #833 
- #2003 

Other things that should be considered and turned into tickets
- indexes on neighbourhoods (related to #1962)
- end-user UX
  - admin interface will be slower (more records to load)
  - end-user interface will be slower (same reason)
  - there may be duplicate names
  - when a user has an out-of-date neighbourhood they are indicated
- root admin UX
  - some kind of root admin display showing the year on partners
  - show year on neighbourhood pages
- prune unused old neighbourhoods
- any other places where neighbourhoods are used
  - calendars?
  - partners?
  - sites?
- improve the neighbourhood importer so it prunes unused older neighbourhoods automatically

**Comment by katjam** [comment]
Closing as won't fix.
