### ISSUE TITLE
[Bug]: Rennovate keeps bumping node version to a broken one

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2016]
## Description

pr by renovate #2010, we've already had to revert it once #2009

## notes

some googleing around suggests we need to add these options to `renovate.json` 

```json
{
  "packageRules": [
    {
      "matchUpdateTypes": ["pin"],
      "matchStrings": ["node"],
      "enabled": false
    }
  ],
  "global": {
    "node": {
      "version": "16.20.1"
    }
  }
}
```
I'm a bit wary of this snippet, I can't find the global option in the docs

- node renovate docs https://docs.renovatebot.com/node/
- constraining a version https://docs.renovatebot.com/configuration-options/#constraints

The above `packageRules` option would probably work on it's own because it disabled renovate from updating node but we can also specify a version like

```json
{
  "force": {
    "constraints": {
      "node": "< 15.0.0"
    }
  }
}
```

@ivan-kocienski-gfsc  says 

> buildpacks are configured on the servers through dokku (there are a few other places they can be set from) so it's something we need to manually keep our eyes on

This will effect the node version on our deploys as apposed to our development environments

**Comment by katjam** [comment]
Won't fix. Hasn't been an issue for a while
