### ISSUE TITLE
[Bug]: Change "warning" copy on out-of-date address

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2027]
"The address for this partner is assigned to an out of date neighbourhood. You do not need to take any action but if you wish to reassign this to an up to date neighbourhood please contact support at info@gfsc.studio"

**Comment by r-ferrier** [comment]
I got the wrong email address! Should be:

"The address for this partner is assigned to an out of date neighbourhood. You do not need to take any action but if you wish to reassign this to an up to date neighbourhood please contact support at [info@placecal.org](mailto:info@placecal.org)"

**Comment by r-ferrier** [comment]
That's what we have on the home page anyway ^^
