### ISSUE TITLE
[Bug]:  possible to create redundant citizen user

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2037]
## Description

I created a citizen with no entities that it can effect

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/c1220ba2-8682-428a-b4ca-f884b20ecf95)

It should not be possible to create redundant users someone should have some reason for using their account if they are to join.

## Steps to reproduce

1. Create a user with the bare minimum options

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/4fe6a5b5-41d7-4106-82b1-8266d299b26c)

## Developer notes

Put in a validation that checks if user has at least one Partner, Neighbourhood or Tag.

What if they have a Site though? Sites are added to users elsewhere so if someone wants to make a new site with a new admin then they have to make a site, make a user with a dummy neighbourhood (e.g.) associate the site with the user (on the site edit page) then remove the dummy neighbourhood from the user (?).

I will put in a check so we also validate that they have at least one site- which will solve this scenario but add a hidden dependency between users and sites (on this specific page as there is no way to manage users' sites on the user edit page). This may also present a problem on the site edit page: if a site admin removes a user from a site and that user then becomes "empty" how do we let the site admin know?

**Comment by ivan-kocienski-gfsc** [comment]
I think this can be solved by putting on a custom validation on the user model where we check they have at least one of partners, tags or neighbourhoods (?)

**Comment by aaaaargZombies** [comment]
> I think this can be solved by putting on a custom validation on the user model where we check they have at least one of partners, tags or neighbourhoods (?)

sounds sensible

> But I am a little concerned that there may be hidden relationships not on this form (like a site owner or a calendar) that the user who is currently using the form won't be able to fix.

worth investigation by creating some test users but I suspect that if don't have a neighbourghood or partner having access to a site or calendar will be useless.

**Comment by ivan-kocienski-gfsc** [comment]
good point! that seems logical to me

so i put in the checks aaaaaand now the test suite is on fire because our factories don't create users in the correct way any more. This is going to be a long day.

**Comment by ivan-kocienski-gfsc** [comment]
So just for posterity, here is what I added to the user model
```ruby
  # near the top
  validate :must_have_useful_relation
 
  # in a `private` bit
  def must_have_useful_relation
    return if partners.present? || neighbourhoods.present? || sites.present? || tags.present?

    errors.add :base, "Must have at least one of Partner, Neighbourhood or Tag"
  end
```

**Comment by kimadactyl** [comment]
> It should not be possible to create redundant users someone should have some reason for using their account if they are to join.

I sort of agree but also this is just a needed step in adding a new admin user. It will also get messy as we have to consider statuses around if someone has admin status removed temporarily before setting something new up. I think we're potentialy looking at a lot of validation issues here.

In future too this might have more functionality.

I'm not saying no to doing it I'm saying it doens't seem like a security issue to me and I think will be a lot of work for little reward. It's a base a lot of the rest of the software is predicated on and I think how it is now is a good pragmatic solution. I'm removing from the milestone but feel free to re-add if you disagree.

A potential other route here would be to make it easier in the admin interface to see which users have this status and flag them up.

**Comment by kimadactyl** [comment]
Decided wontfix today - causes more issues than solves
