### ISSUE TITLE
[Bug]: `neighbourhood_admin` can give edit permission to any user on the site to a partner

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2041]
## Description

If you are `neighbourhood_admin` for hulme you can give any user on the site permission to edit any partner which belongs to the hulme neighborhood without that partners consent.

---

update: I believe `neighbourhood_admin` can now only see/update users that have a partner in their neighbourhood due to work we did around permissions.

**Comment by r-ferrier** [comment]
I think this is an assumption about behaviour we want to see rather than definitely wrong behaviour - sticking a question label on it for now

**Comment by r-ferrier** [comment]
closing as we think this is now desired behaviour

**Comment by ivan-kocienski-gfsc** [comment]
Confirmed any neighbourhood admin who is a partner admin can add any partner they can see to any user they can see (within their neighbourhood pool)

![Screenshot_2024-01-31_16-09-56](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/a3997d0e-1b27-4a8a-83cb-d85ce4cd2cee)
