### ISSUE TITLE
Investigate if `neighbourhood_admins` should be able to edit any calendar details connetcted to partners in their neighbourhood.

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2043]
## Description

A `neighbourhood_admin` can edit any calendar details associated with their neighbourhood.

- This includes adding new calendars to partners
- modifying existing calendars
- deleting existing calendars

This is a vector of for abuse that potentially privileges place based groups over interest based groups

**Comment by r-ferrier** [comment]
we think in our current system this is correct - if you can see it as an admin, you can edit it.
