### ISSUE TITLE
[Bug]: creating a plain `editor` user is redundant

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2044]
## Description

If you make a user that has no additional admin privileges you get a blank dashboard with no warnings

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/35bea580-9e82-4895-9ad1-3b4d399440d3)

**Comment by kimadactyl** [comment]
Covered by #2045 now I've tweaked it
