### ISSUE TITLE
Can we subscribe to wordpress calendar feeds? (investigation)

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2048]
## Description

Rach at PHT has asked if this might be possible. It certainly looks like it could be?

https://theeventscalendar.com/blog/news/how-to-let-users-subscribe-to-your-wordpress-calendar/
https://theeventscalendar.com/knowledgebase/exporting-events/

**Comment by kimadactyl** [comment]
We support any valid iCal feed - this is prob just to be added to the list in the documentation.

https://handbook.placecal.org/admin-handbook

**Comment by katjam** [comment]
I think also this relates to #2094 where one hypothesis is that they are using a plugin to generate the iCal feed that isn't encoding the data in a useful way for us to consume, so it could be worth noting plugins we recommend?

**Comment by kimadactyl** [comment]
Yeah, we do already have some WP sites in use too, it would be good to list plugins we can support

**Comment by katjam** [comment]
Closing as the answer is yes.
