### ISSUE TITLE
[Bug]: A list of all tags is exposed to pages that do not use them

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2051]
## Views where this is not required but is currently supplied

- [ ] dashboard for citizen + tag_admin
- [ ] dashboard for editor (is this needed? i don't think we really use editor at all?)
- [ ] dashboard for citizen + site_admin
- [ ] dashboard for citizen

Given I am an empty user with role "citizen"
And I have a tag 
When I log in
And I am on the admin dashboard
Then I should only see the tag i can administer

**Comment by kimadactyl** [comment]
I think these AC should be more tightly scoped to only be about partnership admins.

See: https://github.com/geeksforsocialchange/PlaceCal/issues/2061

**Comment by ivan-kocienski-gfsc** [comment]
verified - was just removing an unused `@variable` from the controller
