### ISSUE TITLE
[Bug]: Citizen users with neighbourhood permissions can edit any neighbourhood

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2053]
## Description

Users with neighbourhood_admin roles can edit any neighbourhood. This feels like something we should lock down - the neighbourhoods are all dependent on each other in ways that may not be clear to a user and changing a field could have wide reaching consequences that they do not understand, and impact on other users' inclusion in sites.

It also looks like they can edit a name of a neighbourhood & the timestamps but these changes do not save - but this is a redundant concern because I think we should essentially just remove the edit view from them completely.

## Acceptance criteria

- [ ] citizen user with a neighbourhood can visit neighbourhoods index
- [ ] citizen user with a neighbourhood can view their neighbourhood
- [ ] citizen user with a neighbourhood can view other neighbourhoods, but not see their details
-----
- [ ] citizen user with a neighbourhood cannot edit their neighbourhood
- [ ] citizen user with a neighbourhood cannot destroy neighbourhoods
-----
- [ ] root user with a neighbourhood can do all of the above, including for neighbourhoods they do not own
- [ ] root user without a neighbourhood can do all of the above

### Plan

Write tests for all of the above AC:
- [x] citizen user with a neighbourhood can visit neighbourhoods index
- [x] citizen user with a neighbourhood can view their neighbourhood
- [x] citizen user with a neighbourhood cannot edit their neighbourhood
- [x] citizen user with a neighbourhood cannot view other neighbourhoods
- [x] citizen user with a neighbourhood cannot destroy neighbourhoods
- [x] root user with a neighbourhood can do all of the above, including for neighbourhoods they do not own
- [x] root user without a neighbourhood can do all of the above
- Remove links to pages that should not be visible
- add policies to controllers for pages that should not be visitable

**Comment by aaaaargZombies** [comment]
## verification

- citizen user with a neighbourhood can visit neighbourhoods index

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/6644b5c2-5c7b-4522-b9f9-c8b04ef143bb)


- citizen user with a neighbourhood can view their neighbourhood

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/3a06edf9-71d1-409d-bfee-ab20c35ef295)

- citizen user with a neighbourhood can view other neighbourhoods, but not see their details

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/06b01229-296e-4264-aabe-c4a2348a4214)

-----
- citizen user with a neighbourhood cannot edit their neighbourhood
- citizen user with a neighbourhood cannot destroy neighbourhoods

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/8a9f2702-142c-4a00-b602-78769137498c)

-----
- root user with a neighbourhood can do all of the above, including for neighbourhoods they do not own
- root user without a neighbourhood can do all of the above

Clarification needed here - a root user can edit / destroy neighborhoods, AC says should be all of above but I am not sure this is correct. I would have though root user is the person who needs to be able to do this, or are we intending that to be for devs only in console/rake/migration?

![2023-09-29-11:17:52-screenshot](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/1bcfab49-ed99-49a8-801d-6bd22ac9ad61)
