### ISSUE TITLE
[Bug]: neighbourhood_admin users can press update button but cannot change anything on edit user page

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2054]
## Description

Edit page or maybe just the update button should not be visible when a user is not able to make any updates

**Comment by aaaaargZombies** [comment]
This issue may be out of date. Currently a NA can

- update which partners a user has
- delete some users, potential regression on #2104 

![2024-01-20-14:49:33-screenshot](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/ab02ed31-c00c-4e58-9c27-1f9c37c502d4)

**Comment by r-ferrier** [comment]
marking as duplicate, dealt with in #2203
