### ISSUE TITLE
[Bug]: dead links

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2056]
## Description

Given I am a partner admin
That has a partner
When I log in
And visit the edit partner page
Then I should see the list of users for this partner
And that list should not be links to those user pages

Given I am a neighbourhood_admin
And a partner exists
That has a service area
When I visit the neighbourhood page
Then I should see a list of partners for that neighbourhood
But they should not be links to partners

- Partners with service areas in a neighbourhood are listed in the neighbourhood admins partner list, but cannot be visited.
- Partner admins can click add new partner admin from an individual partner page but it returns them to the dashboard

## AC

- [ ] Are visible but are not links

**Comment by ivan-kocienski-gfsc** [comment]
I would say the first point is moot: non-root users should not be able to see any of the neighbourhood pages

**Comment by kimadactyl** [comment]
I think its OK if they can see the neighbourhood pages but not the admin user info. Ivan's solution is prob simpler in the short term. If we go that route tho we should open a new ticket about making the ward map visible to people somehow another way.

**Comment by aaaaargZombies** [comment]
## verified

This is really an ongoing tech debt issue that can't be completely resolved till decisions have been made about what access each user should have. I can confirm the following has been fixed.

> Partners with service areas in a neighbourhood are listed in the neighbourhood admins partner list, but cannot be visited.


![2023-09-29-10:26:39-screenshot](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/937f2f1e-d294-4b15-a447-fc2ffc3d69f9)

> Partner admins can click add new partner admin from an individual partner page but it returns them to the dashboard

![2023-09-29-10:28:22-screenshot](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/fa8ada8d-b5d8-4342-bb5f-46a10f66c82e)
