### ISSUE TITLE
Audit and fix Partnership Admin permissions

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2063]
## User story

As a partnership admin (PA), I should only have access to relevant data and actions related to my role.

## Acceptance criteria

- [x] A basic partnership admin (ie the Trans Dimension Organiser) has the permissions `neighbourhood_admin`: region covered by their activities, `partnership_admin`: tag they admin for. They might also be a site admin, partner admin, or editor.

In the admin interface, a PA can:

View everything a NA can, with restrictions:
- [x] All of the neighbourhoods
- [x] #2168
- [x] #2169
- [x] #2170
- [x] All Category Tags

Create everything a NA can, with restrictions:
- [x] #2171
- [x] #2172
- [x] #2173

Edit everything a NA can, with restrictions:
- [x] #2174
- [x] #2175
- [x] Everything about a calendar
- [x] #2176

Delete everything a NA can, with restrictions:
- [ ] #2177
- [x] Calendars within their scope

**Comment by aaaaargZombies** [comment]
> - CRUD only partners in partnership The Trans Dimension
> - CRUD partners not in The Trans Dimension partnership (e.g. this means that it is impossible for this role to make a partner without a Trans Dimension partnership)

Will need to figure out how do existing partners get added to a new Partnership?

**Comment by kimadactyl** [comment]
> Will need to figure out how existing partners get added to a new Partnership?

Agree totally this is an issue - we should open a ticket, but for now this isn't affecting anyone and if it came up GFSC staff could fix manually

**Comment by kimadactyl** [comment]
> create users assigned to partners tagged The Trans Dimension 

afaik this already works and just needs tests adding

**Comment by kimadactyl** [comment]
> CRUD news articles tagged The Trans Dimension

If we are removing this from scope are we just telling Georgie they can't edit the news articles any more?

**Comment by ivan-kocienski-gfsc** [comment]
## Notes on: Acceptance criteria

- [ ] TDO has permissions (role) "editor"
- [ ] TDO has "neighbourhood_admin: england" (has a neighbourhood)
- [ ] TDO has "partnership_admin: the trans dimension" (has partnership tag)
- [ ] TDO is set as site_admin for The Trans Dimension (is owner of site)

In the admin interface, TDO can:

- [ ] CRUD only partners in partnership The Trans Dimension
  - extend permissions so a user with a partnership tag can see partner admin page
  - filter partners by partnership tag
  - cannot remove trans dimension partnership (tag).
- [ ] create calendars, but only if they are attached to The Trans Dimension partners
  - needs a validation based on the current users' tags
  - does this conflate with the "neighbourhood admin" logic?
- [ ] read, update and delete only calendars with partners in partnership The Trans Dimension
  - no create but yes delete?
- *create users assigned to partners tagged The Trans Dimension* decided out of scope for this cycle 24.10.23 HA
- [ ] see users who are partner_admin for partners tagged The Trans Dimension
  - this is a filter on the users controller
- *assign existing users to partners in tagged The Trans Dimension* decided out of scope for this cycle 24.10.23 HA
- *CRUD news articles tagged The Trans Dimension (note this means I can't remove The Trans Dimension tag from a news article too)* decided out of scope for this cycle 24.10.23 HA
- [ ] Configure key info about the Trans Dimension PlaceCal site (homepage information on trans-dimension.placecal.org)
  - controller filters: validate user is site_admin for site and allow update
- [ ] Edit the description for the Trans Dimension partnership tag
  - controller filter: validate user has this partnership_tag

TDO cannot:

- [ ] CRUD partners not in The Trans Dimension partnership (e.g. this means that it is impossible for this role to make a partner without a Trans Dimension partnership)
- [ ] CRUD any calendars not attached to a Trans Dimension partner
- [ ] Unassign The Trans Dimension partnership tag from a partner (?)
- [ ] Delete users 
- [ ] Edit users
- [ ] Delete the Trans Dimension partnership tag
- [ ] CRUD any categories, facilities, or other partnership tags
- *CRUD news articles not tagged The Trans Dimension* decided out of scope for this cycle 24.10.23 HA

**Comment by katjam** [comment]
> > CRUD news articles tagged The Trans Dimension
> 
> If we are removing this from scope are we just telling Georgie they can't edit the news articles any more, or is this being addressed another way? I don't think we should just remove their functionality personally?

There have not been any news items added since the launch, so am not anticipating it to be an issue, but we should definitely chack with Georgie.

**Comment by kimadactyl** [comment]
Tbh I think the fact we've not done one is a big issue we should address - TransDim is our current biggest sales pitch and the fact it's looking un-updated isn't great. Hopefully there's some movement on this following calls today.

**Comment by r-ferrier** [comment]
closing as reticketed

**Comment by katjam** [comment]
Marking as duplicate because only one of the connected issues has not been closed and verified independently.
