### ISSUE TITLE
[Bug]: Partnership admin should be able to see partners assigned to their tag and remove partnership tags from them

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2064]
## Description

A partnership admin currently is a useless position. The person in charge of a partnership should be able to view the partners tagged with that partnership tag, and remove the tag from them if required. They should also be able to invite new users, create new partners with their partnership tag, and assign users to partners they have created. 

Expanding these permissions might also help us to remove the dependency a partnership site has on a neighbourhood further down the line.

## Questions

All of the above is an assumption that needs verifying!

**Comment by kimadactyl** [comment]
Superceded by #2089
