### ISSUE TITLE
Replace generic 'tags' inputs with ones for partnerships, facilities and categories

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2066]
## User story

As a developer I am getting confused about the current combined tags field and would like it to be split into the seperate bits in order that we use proper terminology more.

As a partner admin and site admin the current input is pretty confusing as some of the options are not real

In other words it should be an architectural irrelevance that these things inherit from tags and currently they are being talked about interchangably.

A lot of this will be covered when #2061 and #2051 are done, this ticket is a failsafe to make sure its done completely.

## Acceptance criteria

- [ ] #2333
- [x] #2334
- [x] #2335
- [x] #2336
- [ ] #2337

## Implementation notes & questions

This is supposed to be a quick easy fix so I'm going to implement the suggested UI

```ruby
<%= f.association :partnerships (...) %>
<%= f.association :categories (...) %>
<%= f.association :facilities (...) %>
```

And raise a draft PR so we can see how many other tickets it raises and make an informed judgement about time/cost/benefit. Essentially doing some active research. Fingers crossed it will be plain sailing ⛵🏝️🌞

## Implementation plan

_To be written by the developer_

**Comment by aaaaargZombies** [comment]
![2024-01-11-14:22:01-screenshot](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/0f3e909d-6765-40f9-b3f5-c1b262495db3)

split this input into 3 inputs

**Comment by kimadactyl** [comment]
OK so it's my understanding that this should be as simple as replacing the one tags input with three like this. I'm sure the validations need redoing but I think the fact they're backed with a single database table is irrelevant.

If I'm wrong then I understand this is a significantly more complex ticket!

```ruby
<%= f.association :partnerships (...) %>
<%= f.association :categories (...) %>
<%= f.association :facilities (...) %>
```

**Comment by r-ferrier** [comment]
For future context: this was discussed at a meeting this afternoon. There's potentially quite a bit of unpicking here required to make this happen. I raised some concerns that me and Ivan had about what the evidence is that this is required, how much time we think it could take, and if we think this is introducing further complexity to an already overloaded part of the system. We will try to make time to investigate this next week after prioritising the issues in the milestone based on the feedback from miro & the session notes.

**Comment by katjam** [comment]
Closing as has been sharded off.
