### ISSUE TITLE
Calendar admin page does not specify if contact info is public or private

### ISSUE THREAD

**Issue by david-gfsc** [geeksforsocialchange/PlaceCal#2069]
## User story

As a Partner Admin or Organiser, I need to be able to know if contact information I'm adding to a partner's calendar will be public or private.

## Acceptance criteria

- [ ] The page for add/edit calendar makes clear where the information is shared

## Implementation notes & questions

At present, the page to add or edit a calendar ( https://admin.placecal.org/calendars/*/edit  <-- wildcard for calendar number) has a section for contact details, but does not specify whether those details are private (i.e. a contact specifically for PlaceCal/GFSC internal use) or public (will be published, anyone interacting with PlaceCal can see them).

Asking a developer about this in a meeting yielded "I'm not sure". The page should make it clear so none of us get confused ever again.

## Implementation plan

_To be written by the developer_
![Screenshot 2023-09-20 at 15 54 20](https://github.com/geeksforsocialchange/PlaceCal/assets/108418912/20a5dec0-4bf7-47cd-b65c-88f0a1d6e888)

**Comment by ivan-kocienski-gfsc** [comment]
Okay here is what i have found.

In calendar we collect contact name, email and phone. 

This is only used in the event show page here
![Screenshot_2024-01-18_09-51-18](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/7f9f076e-a520-4c67-94e1-36d14d22b218)

Some points:
- non of this information is used in any admin area (apart from the calendar form)
- the email is read from calendar public email, then the partner public email, then place (?) public email
- this is not validated
- this can be blank or nil
- the view doesn't check if this is blank, only if it is nil, and empty string is "true" in ruby
- we don't use the phone number at all
- we don't use the name at all
- it looks like we CC `support@placecal.org` (or try to)
- not tested this link to see if it works

**Comment by katjam** [comment]
Verified on staging
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/436ef7bb-d53a-424a-beac-94794180f6e1)

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/caea0cb5-04e2-46c4-9917-3a8a88032f41)
