### ISSUE TITLE
Update releasing documentation about PR reviews

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2085]
Add a line in the `RELEASING.md` after point 3 but before point 4 describing that the merge PR from main to production needs to be reviewed by another developer, not to verify the code changes (as this has already happened) but to verify that all the steps in the releasing procedure have been followed correctly.

**Comment by katjam** [comment]
Won't fix as leaving responsibility up to developer.
