### ISSUE TITLE
README.md easily gets you to a state a member of staff can develop from

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2088]
See below suggested AC, may need updating

Currently the install docs are far too verbose. Instructions should be simple and easy to follow.

Suggested AC for a new one:

- [ ] Add `gem install foreman` step (currently missing)
- [ ] Default `make docker` command should do everything the gfsc one does except with seed data not prod data
- [ ] Move GFSC-specific install info into another doc and maybe rename command to `make gfsc_docker` or something like that
- [ ] Delete all depends section that Docker covers for you - ideally provide one brew/apt etc command or move into a script that detects if they're installed
- [ ] Add more info on how to start a server, restart it, reset it, shut down, etc (current instructions say bin/dev but the docker way seems to be a make command instead? and these are only in the "for everyone else" section)
- [ ] Double check the `make clean` command works - this isn't getting to the network for me
- [ ] Work out why when Kim runs it it does it in prod mode
- [ ] Move non essential info into docs dir
- [ ] If we are using docker lets just make that the one supported way to use the repo and remove refs to other ways
- [ ] When done, test all this on a fresh computer!

see also: 

- [x] https://github.com/geeksforsocialchange/PlaceCal/issues/1967

**Comment by ivan-kocienski-gfsc** [comment]
Verified / no code
