### ISSUE TITLE
[New site]: PlaceCal Exeter

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2089]
**Blocked by #2062**

# New site request

- Name of person: Michael F
- Region covered: Exeter
- Site name: PlaceCal Exeter
- Desired colour scheme (pick one): orange blue green pink custom
- ~[Optional] Interest covered: partnership_name~
- Domain: exeter.placecal.org

## Acceptance criteria

- [ ] site_name_slug.placecal.org exists!
- [ ] site_name_slug.placecal.org is not set to public
- [ ] site_name_slug.placecal.org has an SSL certificate added (see [handbook](https://gfsc.notion.site/Creating-a-new-PlaceCal-Site-bd90494c88e74bfe94c306f714ede8dc))
- [ ] Header and footer logos are created (preferably as svg), with transparent background
- [ ] Site has logos uploaded in correct places
- [ ] person_name is set as site admin
- [ ] person_name is set as neighbourhood admin for region_name
- [ ] The [handbook](https://gfsc.notion.site/Creating-a-new-PlaceCal-Site-bd90494c88e74bfe94c306f714ede8dc) is accurate (make edits if not clear)
- [ ] person_name is informed their site has been created

## plan

- [x] exeter.placecal.org exists!
- [x] exeter.placecal.org is not set to public
- [x] exeter.placecal.org has an SSL certificate added (see [handbook](https://gfsc.notion.site/Creating-a-new-PlaceCal-Site-bd90494c88e74bfe94c306f714ede8dc))
- [x] exeter.placecal-staging.org exists!
- [x] exeter.placecal-staging.org is not set to public
- [x] exeter.placecal-staging.org has an SSL certificate added (see [handbook](https://gfsc.notion.site/Creating-a-new-PlaceCal-Site-bd90494c88e74bfe94c306f714ede8dc))
- [x] The [handbook](https://gfsc.notion.site/Creating-a-new-PlaceCal-Site-bd90494c88e74bfe94c306f714ede8dc) is accurate (make edits if not clear)
- [x] Header and footer logos are created (preferably as svg), with transparent background
- [x] Site has logos uploaded in correct places
- [x] Michael F is has a user account
- [x] Michael F is set as site admin
- [x] Michael F is set as neighbourhood admin for Exeter
- [x] Michael F is informed their site has been created

**Comment by kimadactyl** [comment]
Adding to milestone - suggest we just pick a colour for them and get this made

**Comment by aaaaargZombies** [comment]
blocked by lack of logo

**Comment by aaaaargZombies** [comment]
I'm going to try and do everything but upload the logo so it's ready to go

**Comment by undividual** [comment]
Gonna do the logo tomorrow @aaaaargZombies! x

**Comment by aaaaargZombies** [comment]
If you could point me to the files I could probably do it myself, assuming it's one of the generic NAME+placecal ones?

**Comment by aaaaargZombies** [comment]
ok I've completed what's ticked in the plan and am now blocked again, but not much left.

**Comment by undividual** [comment]
Right @aaaaargZombies here they all are, this folder contains the original AIs as well as SVG and PNG, whichever you need! 
https://www.dropbox.com/scl/fo/2hn3ams8atsqfdzxviwfe/h?rlkey=bf72uf8wkokbi3cvrqlfuwi3v&dl=0
I realised I didn't know the colour scheme so I did green as we havne't had that in a while?! But let me know if you need them in another colour!

**Comment by aaaaargZombies** [comment]
cheers Emma they are up https://exeter.placecal.org/

**Comment by kimadactyl** [comment]
Emailed today to sign this off, all done!
