### ISSUE TITLE
Improve partner event listing UX

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#2091]
## From a discord conversation with honor about Norwich Placecal
https://discord.com/channels/534700660327841792/813396103944601630/1158732817044361287

### Needs to be transformed into Acceptance Criteria

In the current state, it's really hard to see what's actually happening. i think this is especially bad for a site with relatively few partners, so one that's just starting up. each partner will want to have one page which shows all their events, splitting by week leaves blank/1 event weeks for that partner which is obscuring the information

having one page they can link to reliably to show what's on was actually a really big selling point for the One successful partner i have managed to convince to join norwich placecal so far!

something that is a big  highlight of trans dimension for me, usability wise, is being able to click one button to just see 'future events'. if i had my way, that would be the default view for all placecal sites.

## Acceptance criteria

- [ ] criteria one
- [ ] criteria two

## Implementation plan

_To be written by the developer_

**Comment by ivan-kocienski-gfsc** [comment]
This sounds like we want to have a partner show action.

Information on the show page:
- address neighbourhood link
- service areas neighbourhood links
- list of events (or a link to a page with a list of events)
- list of sites the partner appears on
- list of calendars importing events to this partner
- any "problems" this partner is having with PC import system

**Comment by kimadactyl** [comment]
I think this is now fixed right @honor-gfsc? If not let's open smaller and more specific tickets

**Comment by honor-gfsc** [comment]
i don't understand this ticket, i don't think this work was done from ivan's comment? but i don't really know what a show action is

**Comment by kimadactyl** [comment]
show action - single event, single partner
index action - all events, all partners

to me this reads as being resolved when we changed the default event index?

but i dont understand it either so would rather close and reopen specific issues

**Comment by honor-gfsc** [comment]
i think this is talking about things which should be more visible in the admin interface. it's unclear to me what parts of this might have been surfaced in the work which was completed in the last cycle(s)

**Comment by katjam** [comment]
I agree with the closing of this. The original conversation was about surfacing future events in the public view if there were no events this week. That work was done - and has been revised in a recent PR.

Ivan's comment https://github.com/geeksforsocialchange/PlaceCal/issues/2091#issuecomment-1776775005 is not related to the original issue and is an admin thing, as honor says.

I think there is a need for an issue around _things which should be more visible in the admin interface_ but this is not that issue... and it should arise naturally at some point in future. @honor-gfsc are you OK with this being closed as is?

**Comment by honor-gfsc** [comment]
sure yep just wanted to check in about what we were actually closing here as the messaging seemed confused!
