### ISSUE TITLE
[Bug]: Birch community calendar is showing "empty slot" in event titles

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#2094]
## Description
Events pulling through from Birch Community calendar are showing as empty slots. We suspect this needs to be fixed by fixing the data their end.

## Steps to reproduce

1. Visit https://manchester.placecal.org/partners/the-birch-community-centre
2. 
## Example image
 
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/8c867ef0-7db9-409d-988f-dfa9ae88dfa7)

**Comment by katjam** [comment]
Kim's suggestion tl;dr
Arrange a 30 min call to establish their situation and then make recommendation of how they can improve the feed.

>> in this case, i think its that the source feed is bad. so we need to have a case study of where we are to date and then a next action for us/them to go through. its the flowchart thing right. maybe a rule of thumb is we want to go as close to the source as possible at all times 
i think fundamentally they just dont quite understand what the feeds are and where theyc ome from and dont know how to ask to get to that. maybe its good to get on a call and step through the exact combos of plugins and stuff and what guides they followed and get that documented as a case study. 
i think theres a google cal feed powering the site and the wordpress plugin is making its own feed
i think our ideal sitch would be to be using the Google feed directly 
but it may also be they just need some help with that e.g. putting bookings on antoher cal
i deffo dont think its anything placecal needs to change
another option would be - maybe what if the widget theyre using is shit and what theyd really like is to make an ical feed that goes into placecal and then we have a palcecal embed widget
i think we just need to write up what these routes are as a first step
does that help
so maybe we need to commit to say - 10 x 30 min calls directly with partners as needed where the PHT team cant fix it themselves. but come out of each of those with something new that the PHT team can follow 
if we can get a testimonial or photo or some notes about what problem theyre tryign to solve at the same time - brilliant
if we can get some of the dev team to do these calls - even better

**Comment by kimadactyl** [comment]
Adding to current milestone as this is litearlly preventing onboarding i think

**Comment by kimadactyl** [comment]
Or let me me more specific: we need to decide what to do in this use case where a calendar feed is provided with bad data in

**Comment by aaaaargZombies** [comment]
todo

- investigate what data is being produced by the feed
- discuss with user
- is there obvious errors we can filter for or warn partners about automatically?

**Comment by aaaaargZombies** [comment]
a  bit of browsing of their site suggests this is an error on their end

https://www.birchcommunitycentre.co.uk/events/page/19/

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/51f57ff2-6ee4-4d54-b7e3-38f87dfa6abb)

Next I'll look at the actual feed and see if there's obvious errors we can filter for.

**Comment by aaaaargZombies** [comment]
It looks like a totally valid `.ics` feed to me, no missing fields that we should obviously filter for.

```ics
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//wp-events-plugin.com//6.3//EN
TZID:Europe/London
X-WR-TIMEZONE:Europe/London
BEGIN:VEVENT
UID:2971@birchcommunitycentre.co.uk
DTSTART;TZID=Europe/London:20231030T093000
DTEND;TZID=Europe/London:20231030T173000
DTSTAMP:20231013T160657Z
URL:https://www.birchcommunitycentre.co.uk/events/empty-slot-28/
SUMMARY:Empty slot
DESCRIPTION:Empty slot (auto created).
CATEGORIES:Open
LOCATION:#_LOCATIONNAME\, #_LOCATIONFULLLINE\, #_LOCATIONCOUNTRY
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS=#_LOCATIONFULLLINE\, #_LOCA
 TIONCOUNTRY;X-APPLE-RADIUS=100;X-TITLE=#_LOCATIONNAME:geo:0,0
END:VEVENT
```

**Comment by aaaaargZombies** [comment]
The are using this to generate the calendar/ feed https://wp-events-plugin.com/

**Comment by aaaaargZombies** [comment]
Looking at some discrepancies between the calendar we import from and whats on their own site

- https://manchester.placecal.org/partners/the-birch-community-centre  is only going up to Nov 5th 2023
- https://www.birchcommunitycentre.co.uk/whats-on/ has events up till end of Dec 2023
- https://www.birchcommunitycentre.co.uk/events/ is paginated and only goes up to Oct 29, 2023

**Comment by katjam** [comment]
Ivan and I had a call with their WP developer and they should be able to fix their end.

- He has already had to modify the plugin
- They use it for their events and booking form and filter the content in those places accordingly
- The empty slots are the ones available in their booking form for the available booking of the hall.
- The events are generated when the slots are filled
- There is no google calendar backing this data 
- They use google caledar for personal stuff, stuff that is provisional and sometimes contains PID so it's not for public
- The iCal feed is generated by the plugin.
- They do not use the iCal feed but as @aaaaargZombies  discovered - it is viewable on a public url which will be helped by this fix also.

We helped him find the right place to alter the code that generates the iCal feed and closeing as it has been left with them. We can assume they will get back to us if they are unable to fix (we asked him to) - so this should be verifiable in a period of time / not yet determined.

**Comment by r-ferrier** [comment]
I've added wontfix so that for the purposes of this release we can check that everything that needs verifying has been verified, and also technically it's something we're not addressing in the code. That being said we should check back on this in the next sprint so I've put a reminder in my calendar to re-verify this then.

**Comment by katjam** [comment]
@r-ferrier I've removed the won't fix because have had confirmation from them that they think the issue is resolved. So we can now verify and then you can tick that off your calendar!

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/3e42c096-dc24-4dac-9e28-3929c19f4476)

**Comment by kimadactyl** [comment]
Great that you did this - for me I think the most important thing is we develop a process for what we do if this happens next time. We don't have to go to quite this length - but maybe what we would do is keep a troubleshooting list other people can follow? What do you think?

**Comment by katjam** [comment]
That's a great idea.
