### ISSUE TITLE
Verify that only public data is exposed on the open API.

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#2097]
https://github.com/geeksforsocialchange/PlaceCal/issues/2065
https://github.com/geeksforsocialchange/PlaceCal/issues/2069

Public controllers:
- application
- calendars
- collections
- events
- (graphql)
- joins
- news
- pages
- partners
- sites

Admin controllers:
- application
- articles
- calendars
- collections
- jobs
- neighbourhoods
- pages
- partners
- sites
- supporters
- tags
- users

**Comment by ivan-kocienski-gfsc** [comment]
I have checked the controllers and they don't seem to leak anything directly.

Checked the GraphQL actions and they seem reasonable but there are two points: the contact type for partners and the address type for partners. Both present all their fields, which may need signposting on the admin partner page.
