### ISSUE TITLE
Only root admins can edit anything about a neighbourhood

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2103]
## Description

Neighbourhoods should not be editable by anyone except root admins.

## Acceptance criteria

- [ ] A root user can edit some parts of a neighbourhood (name, abbreviated name, neighbourhood admin)
- [ ] A neighbourhood admin cannot edit any neighbourhoods
- [ ] A partnership admin cannot edit any neighbourhoods
- [ ] A citizen, editor or site_admin cannot edit any neighbourhoods

## Plan

- Investigate code & UI and find out if anyone else currently can edit neighbourhoods
-  If they can, add in checks to user policy to only permit root to edit neighbourhoods
- If they can see any, remove links to edit neighbourhoods from views accessible by other users

**Comment by r-ferrier** [comment]
This also looks good! Only roots can edit a neighbourhood at all, and all they can edit is name, abbreviated name, and assign/remove admins.

![Screenshot 2023-10-30 at 15 03 09](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/0d52daea-10ad-465a-9672-012b85c915be)

![Screenshot 2023-10-30 at 15 03 52](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/29f2c0f5-d3d4-4e20-bce3-ea9eba43ffc5)

**Comment by ivan-kocienski-gfsc** [comment]
Verifying:

### Root users can update neighbourhoods
![Screenshot_2023-11-08_16-08-16](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/19b06282-1679-46ac-aee0-252520de53d3)
![Screenshot_2023-11-08_16-08-40](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/80c36250-b9ed-40a2-b542-0b8dc21416bf)

### Neighbourhood admins cannot edit neighbourhoods
![Screenshot_2023-11-08_16-10-21](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/fec79457-4022-42fc-bed4-e111f7715886)

### Partnership admins cannot edit neighbourhoods at all
![Screenshot_2023-11-08_16-16-11](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/876a35e3-c0d3-4190-a740-09e1fd861fe8)

### Site admins cannot edit neighbourhoods at all
![Screenshot_2023-11-08_16-20-46](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/c06e75bd-dcd0-4f45-8a1d-51f32674cb8a)
