### ISSUE TITLE
Neighbourhood admins can only assign partners to users (cannot edit other details)

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2105]
Neighbourhood admins cannot edit users details - only whether or not they admin for partners in their neoighbourhood

**Comment by r-ferrier** [comment]
This is definitely handled in my PR if not already - it will just need verifying once #2109 is merged

**Comment by ivan-kocienski-gfsc** [comment]
Verifying

Given NAs can only see users who own partners that fall within their neighbourhood pool.

## NA cannot change any personal details about a user
![Screenshot_2023-11-09_13-33-15](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/5cb2c381-2616-4d98-b140-02c06122e33f)

## NA can add / remove partners from user
![Screenshot_2023-11-09_13-33-45](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/703e0acd-8dac-4e5f-8243-d55336dba1b3)

## UX prompts user if they are about to remove the last partner (that gives the logged in user the ability to modify the viewed users profile)
![Screenshot_2023-11-09_13-37-02](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/1f7fa977-4bb7-4f57-831d-5ce68e6510ef)
