### ISSUE TITLE
[Bug]: A root user should not be able to add a neighbourhood to a site that the site_admin is not also a neighbourhood_admin for

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2115]
## Description

weird behavior, if a root adds another neighbourhood to the site

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/6c456127-a938-4ab9-aa62-489f31872b0c)

but the user is not a neighbourhood_admin for that neighbourhood it shows up incorrectly - presumably because they aren't allowed to see it.

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/6ea0d1f8-e78a-40d1-be67-1c4591e73eaf)

I guess this is the responsibility of the Root to not create a site where the admin is not  neighbourhood_admin for the areas it encompasses

## Steps to reproduce

1. What you did first
1. What you did next

## What you expected to happen

What would you like to happen instead?

## Platform (if relevant)

What device and browser were you using?

**Comment by kimadactyl** [comment]
Good catch - yeah at the moment this is 2 steps you have to do manually and one day it would be good to remove it but for now we are doing this rarely and always by a gfsc team member?

**Comment by r-ferrier** [comment]
we think this *might* be fixed, but needs research - if this is not fixed, we fixed something similar before. Maybe should be displayed as a list rather than a dropdown?

**Comment by r-ferrier** [comment]
ok, site admins can no longer add other neighbourhoods to their site, and the included neighbourhoods shown are the correct ones. Should add in a new feature request: `site admins should be able to add other neighbourhoods to the sites they admin for`? Or do we think site admins being unable to amend sites to include other neighbourhoods is ok for now?

**Comment by katjam** [comment]
My opinion is it's OK for now on the basis that a root user can add neighbourhoods for them. We may eventually want to automate the process - like they can apply to admin a neighbourhood and that request is moderated / automated, but I can't see that as a justified need yet.

Otherwise site admins are effectively controlling their own permissions on the system which doesn't seem right. I think root users need to control the scope of neighbourhoods covered by sites.
