### ISSUE TITLE
[Bug]: Flaky select2 test is stopping CI running reliably

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2116]
## Description

The helper function I have tried to fix unsuccessfully [here](https://github.com/geeksforsocialchange/PlaceCal/pull/2112/files) is failing about 1/3 of the time. You can see the fails in that PR actions tab. This is gumming up renovate and causing a lot of deployment friction.

It looks like there's some helper methods here that might help: https://github.com/Hirurg103/capybara_select2#helpers

Also worth checking that gem is configured properly.

Question: is it actually taking 60 seconds to time out and fail or is something else going wrong?

**Comment by aaaaargZombies** [comment]
might also be worth removing the explicit 10 second waits that are already in the codebase, 

https://github.com/geeksforsocialchange/PlaceCal/blob/main/test/support/select2_helpers.rb#L4

https://github.com/geeksforsocialchange/PlaceCal/blob/main/test/support/select2_helpers.rb#L10

these might be overriding the default of 60 seconds set here https://github.com/geeksforsocialchange/PlaceCal/pull/1573/files

**Comment by ivan-kocienski-gfsc** [comment]
This is essentially unverifiable :( as these tests can develop problems almost spontaneously.

The CI seems more stable now at this point in time:
![Screenshot_2024-02-29_12-52-10](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/44483509-d1ce-48a2-88d5-e49c04c6a53d)
