### ISSUE TITLE
[Bug]: neighborhood_admin service area display inaccurate

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2123]
## Description

only neighborhoods owned by a NA (nieghbourhood_admin)  can be seen by the NA.

If a partner or root user assigns a service area outside of this scope it displays the correct number of service areas to the NA but not the correct neighbourhood

root users view

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/d5cb2e31-e02a-45a0-b115-4de796986720)

NA view

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/479c22c3-8f12-4024-84f6-7ca4576ce261)

Good news, the NA cannot remove the out of bounds neighbourhood.

## Steps to reproduce

1. What you did first
1. What you did next

## What you expected to happen

What would you like to happen instead?

## Platform (if relevant)

What device and browser were you using?

**Comment by aaaaargZombies** [comment]
This could be super confusing if none of the service areas are really one of your service areas

**Comment by r-ferrier** [comment]
Does this also cause the info in the DB to be overwritten? Looks baaaaaad and I think we need to fix this before releasing

**Comment by r-ferrier** [comment]
have added AC and removed verified label - just needs checking against AC again once all PRs are merged

**Comment by aaaaargZombies** [comment]
## verifed 

- [x] A neighbourhood admin (NA) can see all the service area neighbourhoods (SANs) a partner has, including those outside of the NAs remit
- [x] A NA can only edit the SANs a partner has that are within its remit
- [x] A NA can only delete the SANs a partner has that are within its remit


https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/eca7d039-0ece-476b-bb5b-1725b5fcdfcd




re-ticketed

- [ ] #2138
