### ISSUE TITLE
[Bug]: Deleting partners and partner neighbourhoods is still messy

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2124]
Bug surrounding deletion of a partner by a NA. These are the issues:

- I can delete a service area for a partner with no address losing contact with it
- I can change the address to be out of my nieghbourhood then delete a service area for a partner losing contact wit it
- If I try to delete an address by removing all fields it successfully saves but the address is re-instated (should this fail? maybe out of scope)
- deleting a partner sometimes causes an FK violation - need to investigate this

## Acceptance criteria

- [x] NAs can only delete ALL service areas for partners who have an address & that address is in their neighbourhood
- [ ] #2119 
- [ ] #2128
- [ ] #2130

**Comment by aaaaargZombies** [comment]
## verified

a hulme NA can't remove SA without address in hulme


https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/080e8661-215c-4ba6-b4aa-c7d2f652050a

a hulme NA can remove SA with address in hulme


https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/09b2b8aa-fb4f-4002-b701-a8a530c14474

**Comment by aaaaargZombies** [comment]
## verified

- [x] NAs can only delete ALL service areas for partners who have an address & that address is in their neighbourhood

True 

https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/de4ea774-3b06-4742-aa59-7fca2695b66c




- [x] #2119 
- [ ] #2128
- [x] #2130
