### ISSUE TITLE
A neighbourhood admin can see calendars associated with partners they admin for

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2132]
## Description

Currently, NAs can access the calendars of the partners they admin for through those partners, but these calendars do not appear in their calendar index.

## Acceptance criteria

- [ ] A neighbourhood admin can see calendars in the calendars index that belong to partners whose service areas are in the neighbourhood they admin for but whose addresses are not
- [ ] A neighbourhood admin can see calendars in the calendars index that belong to partners whose addresses are in the neighbourhood they admin for but whose service areas are not
- [ ] A neighbourhood admin can see calendars in the calendars index that belong to partners who they are a partner admin for and whose address and service areas are not neighbourhoods they admin for

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/0cba377b-3750-43c0-9831-020b22188b25)
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/e01dbe60-b156-470e-9c6e-0908a1da5d1b)

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/211bdc17-50ec-453b-81b2-022626e019a0)

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/09d097eb-7109-4c5c-913b-8e87fd651c97)

**Comment by aaaaargZombies** [comment]
## verified


- [x] A neighbourhood admin can see calendars in the calendars index that belong to partners whose service areas are in the neighbourhood they admin for but whose addresses are not

set service area to hulme for "Rosie test parner" and added this calendar  [verification calendar](https://admin.placecal-staging.org/calendars/131/edit)


![admin placecal-staging org_calendars](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/aaa19095-c687-4027-b95d-2daf7d2dbb2e)



- [x] A neighbourhood admin can see calendars in the calendars index that belong to partners whose addresses are in the neighbourhood they admin for but whose service areas are not

set "rosie test partner" address to M15 6SY and remove hulme service area

![admin placecal-staging org_calendars (1)](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/da308755-2cfd-4e9f-94e5-2cca11681e10)




- [x] A neighbourhood admin can see calendars in the calendars index that belong to partners who they are a partner admin for and whose address and service areas are not neighbourhoods they admin for


Move verification calendar to "burnt roti" partner which is london based and set my test account to partner admin for them. Calendar still visible

![admin placecal-staging org_calendars (2)](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/859875e4-b485-4a33-8d22-74c981e1d5dc)
