### ISSUE TITLE
[Bug]: invite email has broken image link

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2133]
## Description

found when verifying #803

looks like the link to the image is a relative path

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/0103cceb-4e0a-4544-99a6-bfdf34e623a1)

https://ci4.googleusercontent.com/proxy/2LG3c4PFSUehnIjCJp8f3TLBPah62b4f8NwV65LHXqNbLsNHlk47VRDxGamS1cvuCfnv0hHx5l5QNPC6Tm2UK3HUzharDftX5R8iOKXRCV3bz7zeFzG10ksD19-V_ZS0YFZUJYgDkjWliPc=s0-d-e1-ft#http:///assets/logo-f666f7e08fe6ebe234b6fcc81d2a06565ec7369ee674d4046ec84e03c3b3c459.png

## Steps to reproduce

1. What you did first
1. What you did next

## What you expected to happen

What would you like to happen instead?

## Platform (if relevant)

What device and browser were you using?

**Comment by ivan-kocienski-gfsc** [comment]
I think this has something to do with how the asset pipeline is configured in production environments. 

So in [development](https://github.com/geeksforsocialchange/PlaceCal/blob/main/config/environments/development.rb) we set up the domain rails uses [here](https://github.com/geeksforsocialchange/PlaceCal/blob/154c3374f9f978bcffc600df48db9df9b0c79d68/config/environments/development.rb#L4). And this is then used to configure the [mailer](https://github.com/geeksforsocialchange/PlaceCal/blob/154c3374f9f978bcffc600df48db9df9b0c79d68/config/environments/development.rb#L45) and the [asset pipeline](https://github.com/geeksforsocialchange/PlaceCal/blob/154c3374f9f978bcffc600df48db9df9b0c79d68/config/environments/development.rb#L47).

The [production](https://github.com/geeksforsocialchange/PlaceCal/blob/main/config/environments/production.rb) initializer has similar set up.

BUT it looks like [staging](https://github.com/geeksforsocialchange/PlaceCal/blob/main/config/environments/staging.rb) has its own environment that does not have this configuration.

Should verify that the staging server is loaded its environment from the staging configuration file and fix it as necassery

**Comment by ivan-kocienski-gfsc** [comment]
This can be checked by getting into a rails console on staging/production and:
```ruby
Rails.application.default_url_options
# should return {:host=>"placecal-staging.org", :protocol=>"https"}

Rails.application.config.action_mailer.asset_host
# should return something like "https://placecal-staging.org"
```

**Comment by ivan-kocienski-gfsc** [comment]
I just sent an email to myself and the image is now loaded correctly

![Screenshot_2023-11-09_15-02-43](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/1831d0d4-13b1-4492-9f8e-51382f130270)
