### ISSUE TITLE
[Bug]: Reinstate (and fix) Admin Partner sytem tests

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2139]
## Description

Revert commit 5254b16cafdb3c239b1b895a877ea50c42ab6ce3

**Comment by aaaaargZombies** [comment]
## verified

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/cdfe54a6-940a-404d-b75f-8a4d549e45f7)
