### ISSUE TITLE
[New site]: Care in Common

### ISSUE THREAD

**Issue by undividual** [geeksforsocialchange/PlaceCal#2149]
# New site request

- Name of person: Marcus Duran (representing both Equal Care and Clapton Commons)
- Region covered: N16, E5 & E9 - Upper Clapton, Clapton Common, Springfield and Stamford Hill
- Site name: Care in Common
- Desired colour scheme (pick one): Pink
- [Optional] Interest covered: We are starting on the basis of place over interest but it will be interesting to monitor how this materialises.
- Domain: care-in-common.placecal.org  (Happy to take your steer on this if you think the hyphens are too much!)

## Acceptance criteria

- [x] care-in-common.placecal.org exists!
- [x] care-in-common.placecal.org is not set to public
- [x] care-in-common.placecal.org has an SSL certificate added (see [handbook](https://gfsc.notion.site/Creating-a-new-PlaceCal-Site-bd90494c88e74bfe94c306f714ede8dc))
- [x] Header and footer logos are created (preferably as svg), with transparent background
- [x] Site has logos uploaded in correct places
- [x] Marcus Duran is set as site admin
- [x] Marcus Duran is set as neighbourhood admin for region_name
- [x] Marcus Duran is set as partnership admin for Equal Care/Clapton Commons
- [x] The [handbook](https://gfsc.notion.site/Creating-a-new-PlaceCal-Site-bd90494c88e74bfe94c306f714ede8dc) is accurate (make edits if not clear)
- [x] Marcus Duran is informed their site has been created

**Comment by undividual** [comment]
I attach the neccesary SVGs below! (Maybe later they might add their own logo but these will work for now)
![PlaceCalCareInCommon_Darkbg](https://github.com/geeksforsocialchange/PlaceCal/assets/90701712/1f6f21bf-2663-4766-9252-6367516618d7)
![PlaceCalCareInCommon_Lightbg](https://github.com/geeksforsocialchange/PlaceCal/assets/90701712/805289d1-c0e6-4a34-835b-93326aa005b7)

**Comment by kimadactyl** [comment]
So I think this PlaceCal X logo is a bit cross purposes?

Either we are making "Care in commons" site, which has their particular requirements on it

Or we are making "PlaceCal Clapton" which would be restricted to just Clapton.

It's fine either way - but its not both :)

**Comment by aaaaargZombies** [comment]
## verified

we have an open issue that discusses some of there ongoing needs with curation but the site is up and running

https://care-in-common.placecal.org/partners
