### ISSUE TITLE
[New site]: Infogette

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#2152]
# New site request

- Name of person: Dee
- Region covered: Greater Manchester
- Site name: Infogette
- Desired colour scheme (pick one): orange blue green pink custom
- [Optional] Interest covered: partnership_name
- Domain: infogette.placecal.org

## Acceptance criteria

- [ ] site_name_slug.placecal.org exists!
- [ ] site_name_slug.placecal.org is not set to public
- [ ] site_name_slug.placecal.org has an SSL certificate added (see [handbook](https://gfsc.notion.site/Creating-a-new-PlaceCal-Site-bd90494c88e74bfe94c306f714ede8dc))
- [ ] Header and footer logos are created (preferably as svg), with transparent background
- [ ] Site has logos uploaded in correct places
- [ ] person_name is set as site admin
- [ ] person_name is set as neighbourhood admin for region_name
- [ ] If it's an partership-based site, person_name is set as partnership admin for partnership_name
- [ ] The [handbook](https://gfsc.notion.site/Creating-a-new-PlaceCal-Site-bd90494c88e74bfe94c306f714ede8dc) is accurate (make edits if not clear)
- [ ] person_name is informed their site has been created

**Comment by katjam** [comment]
Yes. Dee from that Flourish meet-up we had. As far as I know we still plan to get her organisations into a PlaceCal when we are ready.

**Comment by kimadactyl** [comment]
Potential action: let's remove from this milestone and suggest she attends a future PlaceCal training course instead and take it from the top with her?
