### ISSUE TITLE
[Bug]: Expiring letsencrypt keys

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2153]
## Description

From Emma on discord: Hey dev team, we just wanted to check — in the info@ email address we keep getting emails from 'lets encrypt expiry bot' about security (?) certificate expiry — apparently they expired on the 16th? (For these domains: 

ardwick.placecal-staging.org 
beeston.placecal-staging.org
 berwickshire.placecal-staging.org 
christchurch.placecal-staging.org 
gmsc.placecal-staging.org 
hulme.placecal-staging.org 
london.placecal-staging.org 
manchester.placecal-staging.org 
moss-side.placecal-staging.org 
mossley.placecal-staging.org 
moston.placecal-staging.org 
norwich.placecal-staging.org 
ol1.placecal-staging.org 
oldham.placecal-staging.org 
placecal-staging.org 
qa-site.placecal-staging.org 
rusholme.placecal-staging.org 
trans-dimension.placecal-staging.org 
westvale.placecal-staging.org 
www.placecal-staging.org

**Comment by katjam** [comment]
I think these auto renew by cron, but we get the reminder anyway. I've checked a couple and they seem to have valid certs. If someone else can also verify this... in case I missed something? I think we can close.

**Comment by ivan-kocienski-gfsc** [comment]
Just checked

- [x] ardwick.placecal-staging.org
- [x] beeston.placecal-staging.org
- [x] berwickshire.placecal-staging.org
- [x] christchurch.placecal-staging.org
- [x] gmsc.placecal-staging.org
- [x] hulme.placecal-staging.org
- [x] london.placecal-staging.org
- [x] manchester.placecal-staging.org
- [x] moss-side.placecal-staging.org
- [x] mossley.placecal-staging.org
- [x] moston.placecal-staging.org
- [x] norwich.placecal-staging.org
- [x] ol1.placecal-staging.org
- [x] oldham.placecal-staging.org
- [x] placecal-staging.org
- [x] (redirects) qa-site.placecal-staging.org
- [x] rusholme.placecal-staging.org
- [x] trans-dimension.placecal-staging.org
- [x] westvale.placecal-staging.org
- [x] www.placecal-staging.org
- [x] admin.placecal-staging.org
