### ISSUE TITLE
Partnership admins can only see partners with a service area or address in their neighbourhood scope, that also have the tag they are partnership admin for

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2168]
## Acceptance criteria

- [ ] Partnership admins can see partners with a service area or address in their neighbourhood scope, that also have the tag they are partnership admin for
- [ ] Partnership admins cannot see partners that are only in their neighbourhood scope
- [ ] Partnership admins cannot see partners that are only in their tag scope
- [ ] Partnership admin can see partners they are directly  partner admin for

**Comment by katjam** [comment]
Verified. When Neighbourhood admin for England:
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/644b05f6-ff6d-40b0-861c-010c3d15daa1)

When only a single ward
