### ISSUE TITLE
Partnership admins can only create users who admin for partners within their scope

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2172]
## Acceptance criteria

- [ ] A partnership admin can create a user who admins for a partner within their scope (a partner whose neighbourhood and partnership tag they admin for)
- [ ] A partnership admin cannot create a user who admins for a partner outside of their scope
- [ ] A partnership admin cannot create a user who does not admin for a partner

**Comment by r-ferrier** [comment]
blocked by #2171 - needs reverifying after this is complete

**Comment by ivan-kocienski-gfsc** [comment]
i am going to check this. can't tell if it is supposed to be blocked or if github has had a snafu

**Comment by r-ferrier** [comment]
it's blocked by #2168, work done in there will contribute to this

**Comment by aaaaargZombies** [comment]
closing as AC are met by work elsewhere but have found #2211 and #2212 which don't relate to this AC but are issues we should address.
