### ISSUE TITLE
[Bug]: When trying to subscribe to one site's combined ical feed, I end up subscribing to the ENTIRETY OF PLACECAL

### ISSUE THREAD

**Issue by honor-gfsc** [geeksforsocialchange/PlaceCal#2178]
## Description

I wanted to subscribe to see all events on PlaceCal Norwich in my calendar as an .ical feed. I went to the Events page of PlaceCal Norwich and clicked 'Subscribe to with iCal', like I would if subscribing to the feed of any individual partner. I then loaded this into my calendar and it pulled in every event from every PlaceCal site, not just PlaceCal Norwich. 

Screenshot below of what it did to my calendar, lol

<img width="746" alt="Screenshot 2024-01-16 at 12 08 01" src="https://github.com/geeksforsocialchange/PlaceCal/assets/127757676/b7240f9c-d68a-4929-862d-8e12df7aaedc">

**Comment by katjam** [comment]
:scream: Nice find!

**Comment by r-ferrier** [comment]
yikes! But also, kind of love it 😆

**Comment by katjam** [comment]
I'm adding to milestone because it will probably affect the wordpress plugin work & may come up for Exeter too because they were interested in how to get feed out of their PlaceCal too.

**Comment by ivan-kocienski-gfsc** [comment]
Verified on staging by importing the placecal feed into my google calendar

![Screenshot_2024-04-04_15-05-28](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/ad2583a7-dcec-431b-b563-22400320fc79)
