### ISSUE TITLE
Admins need to be able to clear a partner's address

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2208]
In support of

- #1219 
- #2128 

## User story

As admin editing a partner, I would like to be able to clear its address

## Acceptance criteria

- [ ] be able to set address of partner
- [ ] be able to see what address is set
- [ ] be able to remove/clear the address

## Implementation notes & questions

The way the system works currently addresses can be assigned but never removed (from the UI). Will probabbly need a `POST /partners/:id/remove_address` route/action.

Would also be an idea to check the relation between partners and addresses is `dependent: :destroy` as the address system was designed for a whole other use case where partners shared addresses.

Bonus points for making a rake task to clear up orphaned addresses.

**Comment by r-ferrier** [comment]
closing as a dup
