### ISSUE TITLE
Amend 'areas' for Care in Common PlaceCal

### ISSUE THREAD

**Issue by undividual** [geeksforsocialchange/PlaceCal#2221]
## User story

The Care in Common team need their site to reflect a smaller number of wards in Hackney, as this is the area they want to focus on. Those areas are: Cazenove, Springfield, Stamford Hill West

## Acceptance criteria

- [ ] https://care-in-common.placecal.org/ now only serves Cazenove, Springfield and Stamford Hill West
- [ ] Emma has been informed so she can let the client know

## Implementation notes & questions
This may involve deleting and remaking the site, this may involve just amending it, TBC for you guys I guess, but please let me know out of curiosity!

## Implementation plan

_To be written by the developer_

**Comment by aaaaargZombies** [comment]
@undividual are you sure they only want those areas covering or is the area OK if they have the ability to filter partners by a tag they control? ie, nothing from TransDim will come in unless they want it to - just like nothing goes on the TrandDim unless it has the TrandDim tag.

**Comment by undividual** [comment]
tbh I didn't realise this would be a possibility any time soon — but I think we should probably still set it up in this way, as they are keen to be quite specific to these neighbourhoods, very much NOT the whole of Hackney. So kind of a point of principle for them

**Comment by r-ferrier** [comment]
on hold until after the release

**Comment by r-ferrier** [comment]
> tbh I didn't realise this would be a possibility any time soon — but I think we should probably still set it up in this way, as they are keen to be quite specific to these neighbourhoods, very much NOT the whole of Hackney. So kind of a point of principle for them

are we sure we're sure on this - i feel like it might be good to hop on a call to explain how this might work in future - because restricting their neighbourhoods in this way will mean that if one of their partners offers a service that stretches into another area even a tiny bit, they won't be able to add that as a service area. But giving them a partnership tag will allow them to specifically curate their own partners within their neighbourhoods. And apologies if they definitely do want this, I will stop asking!

**Comment by undividual** [comment]
I really did try and convince them to expand their area just _slightly_, but I think as much as not wanting TD events in there, they also, like I say, kind of as a point of principle want to be hyperlocal. Also I know it's a lil bit of hassle buuuut if they learn this the hard way we can always change it later, right? I don't think it'll be an issue for a while.

**Comment by r-ferrier** [comment]
that's absolutely fine, I just didn't want to take power away from them that they might want to keep! we can do that no problem. As for giving them and their partners a partnership tag - if that's something they want, if you let us know which are their partners, and what the tag should be called, we can arrange that at the same time.

**Comment by undividual** [comment]
As far as I can't tell, they haven't added any partners yet, but once they have, yes, we can discuss, and I will let them know when we next speak so they can decide what tag they want!

**Comment by r-ferrier** [comment]
Hey @undividual , this is now done - but in a sort of reversable way - I'll try to explain!

What I've done is update the neighbourhoods that the user can admin for - now they are restricted to those three neighbourhoods(Cazenove, Springfield, Stamford Hill West) and this means that these are the only locations they'll be allowed to apply their partnership tag to, and the only neighbourhoods that they will be able to create and admin partners in. 

The site scope is a bit wider - it still covers all of hackney - but this doesn't mean events in all of hackney will be shown here, only events with the Care in Common tag will show up here, and these can only be created in the wards assigned to this user. 

Does that sound alright? Let me know if you want to chat about this, it's really hard for me to describe it properly in text!

**Comment by undividual** [comment]
This all makes total sense to ME — but I will need to brief THEM on it. Can I check, is it absolutely crystal clear to them how to add the tag in the UI?

**Comment by r-ferrier** [comment]
Yes - they can only create partners that will fall inside their wards, & with their partnership tag.

Their partnership tag will be applied automatically in the create partner form and the UI will tell them to put it back on again if they remove it!

**Comment by undividual** [comment]
Brill, I have let them know all of this now, so it's probably safe to close this issue now if you are happy with it.
