### ISSUE TITLE
partnership admins should be able to remove tags they admin for (but if they do this, they should be warned that they will no longer be able to see the partner)

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2224]

**Comment by r-ferrier** [comment]
Tried this while verifying for a partner by removing the partnership tag from the partner, the warning is not firing for me.

**Comment by aaaaargZombies** [comment]
ok fiddly but I think I found the state where it doesn't work

1. create a new partner
2. fill in details wrong to trigger validation error
3. removing partnership tag doesn't generate a warning

**Comment by r-ferrier** [comment]
verified - works as expected, including following the above steps:

![Screenshot 2024-02-01 at 15 52 25](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/c363d3d4-bf0b-428d-a6f8-ef682c637741)
