### ISSUE TITLE
[Bug]: If I cannot add a user, I should not be able to see the add user button or POST to create endpoint

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#2227]
## Description
Trying to add a new user without admin rights to any partrner

## Steps to reproduce

1. Log in as a partnership admin with no partners
1. Click add user
2. Unable to save the new user because I cannot add partner to them

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/83b3ee9d-f03d-4787-8294-76e998a5114b)

## What you expected to happen

Intended behaviour: you shouldn't be able to create users with no purpose, only users who admin for something you can see so, if there are no partners in your scope, you need to create one first

## Acceptance Criteria
- [ ] Logged in user must be admin of a partner be root to add a user

**Comment by aaaaargZombies** [comment]
## verified

**`neighbourhood_admin` with no partners**

![admin lvh me_3000_](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/31d59144-aa43-4729-8ecb-6e47b2dc9e95)

cannot access new user UI via the url either

**`neighbourhood_admin` with one partner**

![admin lvh me_3000_partners (2)](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/833348f8-0aca-4b15-b786-6483cfac99e4)

Can create users
