### ISSUE TITLE
Release checklist for partnership admin improvements (Cycle 25)

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#2228]
## Some of these should be converted to issues. Listing here for time saving.

- [ ] Verify that all root users should have that level of access
- [ ] Verify all partnership admins also have neighbourhood admin rights over an area that covers ALL of their partnerships

**Comment by aaaaargZombies** [comment]
```
irb(main):001:0> User.where(role: "root").count
D, [2024-02-01T16:04:34.408851 #15] DEBUG -- :    (9.2ms)  SELECT COUNT(*) FROM "users" WHERE "users"."role" = $1  [["role", "root"]]
=> 25
```

I've made list here so it's not public with users names https://www.notion.so/gfsc/PlaceCal-roots-2024-02-01-4ce4e227b4834f28b643293207469dab

**Comment by kimadactyl** [comment]
I think this is done @katjam? At least it's in "reopen if it's an issue" territory? Closing but do re-open if you disagree

**Comment by katjam** [comment]
Agree. Done.
