### ISSUE TITLE
[Bug]: select2 input on tags breaks for partner if validation fails

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2229]
## Description

see #2217 

![admin placecal-staging org_partners_new (1)](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/f58b37fe-0c39-4cc6-8442-864bfa23cc6f)

**Comment by ivan-kocienski-gfsc** [comment]
Verified this seems to be fixed on staging now

![FireShot Capture 001 - Editing - PlaceCal Admin - admin placecal-staging org](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/b97899e4-3aeb-417c-bcbd-0a4af221c5fa)
