### ISSUE TITLE
Change over to new cache format

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2241]
## Description

During the rails 7 update (issue #1110, PR #2240) there is an extra step for updating the rails cache where this warning appears in the console during run/test:

```
DEPRECATION WARNING: Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2.
```

After that PR has been deployed to production someone needs to go into `/config/application.rb` and remove the line `config.active_support.cache_format_version = 6.1` so the new cache format will be used.

**Comment by r-ferrier** [comment]
Verified - Builds now running on staging without the error.

<img width="1083" alt="Screenshot 2024-02-27 at 16 41 29" src="https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/4a6346d1-afc4-4bc8-8659-6801b9564aa5">
