### ISSUE TITLE
Host fonts ourselves 

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2248]
We don't want to have a cookie notif if poss and i think this is the only thing. Removes nasty google tracking!

**Comment by kimadactyl** [comment]
We should prob make a bigger deal of our platform being privacy protecting too!

**Comment by r-ferrier** [comment]
fonts all loading from assets

<img width="1173" alt="Screenshot 2024-02-27 at 16 37 54" src="https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/7bcdfdca-1084-4126-bcab-d4ff75d92793">
