### ISSUE TITLE
Remove places tables

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2258]
As part of #1950 

## A/C
- [ ] `places` table is removed
- [ ] `partner_places` is removed
- [ ] verify these tables are no longer referenced in code

**Comment by r-ferrier** [comment]
verified - No longer existing.

[erd.pdf](https://github.com/geeksforsocialchange/PlaceCal/files/14422892/erd.pdf)
