### ISSUE TITLE
[Bug]: select2_rails - is this gem still maintained?

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2260]
## Description

Do we want to investigate removing this or is it too big a task? https://github.com/argerim/select2-rails

This came out of https://github.com/geeksforsocialchange/PlaceCal/issues/2159

**Comment by kimadactyl** [comment]
I think sometimes the reason things are not updated is they just work!

**Comment by r-ferrier** [comment]
I agree. I'm closing this and if it ever becomes a problem we can come back to it.
