### ISSUE TITLE
Add spam protection to contact form

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2265]
## User story

GFSC staff are getting 20-40 spams a week. We should have some basic spam protection to cut this down.

## Acceptance criteria

- [ ] Install invisible_captcha

## Implementation notes & questions

Kim previously implemented this to good effect on tai chi school: https://github.com/markets/invisible_captcha

## Implementation plan

_To be written by the developer_

**Comment by ivan-kocienski-gfsc** [comment]
Verifying in code that this has been set up in the code.

We shall see if this solves the spam problem going forward and review if any further action needs to be taken.
