### ISSUE TITLE
Merge security fixes directly onto prod as they are released

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2276]
## User story

Currently, security fixes to our gems are packaged in with the rest of the release process, meaning that vulnerabilities can go weeks or months unpactched.

We should update our Renovate configuration so that passing security fixes get merged onto both servers, and review our processes to make sure non-passing ones do to.

Potentially we should then do this for all our Rails sites.

## Acceptance criteria

- [ ] criteria one
- [ ] criteria two

## Implementation plan

_To be written by the developer_

**Comment by katjam** [comment]
Won't fix as it seems like a risk eliminate the human checks.

**Comment by kimadactyl** [comment]
Do you not think its safer than no checks?

**Comment by katjam** [comment]
I think it's best to do regular monitored updates batched with other work. 

We obviously won't be doing that so the next best thing is to have these automated PRs generated and a person to push them live under supervision. I think it's not sensible to have something that is updating itself unmonitored.

**Comment by kimadactyl** [comment]
I understand, you're prob right, I guess for me this is a big area of uncertainty/anxiety and I'm looking for a magic bullet that doesnt exist
