### ISSUE TITLE
[Bug]: stop cryptominer running on staging/production

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2280]
## Description

Looks like we have a cryptominer running on staging/production. 

`kdevtmpfsi` which is part of kinsing

The suggestion seems to be to nuke staging/production and rebuild from scratch.

https://www.reddit.com/r/sysadmin/comments/qpbbu6/kdevtmpfsi_is_taking_the_whole_cpu/

https://medium.anands.me/kdevtmpfsi-using-100-of-cpu-here-is-how-you-can-fix-that-89c247a24442

https://stackoverflow.com/questions/60151640/kdevtmpfsi-using-the-entire-cpu

**Comment by ivan-kocienski-gfsc** [comment]
Having investigated further it turned out to be a compromised [metabase](https://github.com/metabase/metabase) container.

I have stopped metabase (both the app and database containers) on both staging and production.

So far it looks like only the containers were the problem and nothing seems to be restarting the malware on the droplet itself.

Going to leave it there for now and we can have a all hands team meeting about this but I'd recommend:
- rebuilding / updating droplet
- removing / not using metabase (or any unecassery tools)

**Comment by katjam** [comment]
Done.
