### ISSUE TITLE
[Bug]: We should avoid sharing personal details unless absolutely necessary

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2286]
## Description

Following some GDPR research https://www.notion.so/gfsc/027-e8f8fc29f1a144e29e29e171d9830843?p=fbad6df6a99e4071b5053007c3df18d1&pm=s & a discussion me and Katja had, we think it's best to err on the side of caution and prevent the sharing of personal email details between users when avoidable. 

## Acceptance criteria

- [ ] On hiding a user, an email is sent to the user containing advice to email support@placecal.org
- [ ] On hiding a user, an email is sent to support@placecal.org containing details about who hid the user and the text sent to them
- [ ] Copy relating to taking this action explains what will happen

**Comment by katjam** [comment]
@r-ferrier Did this get done?

**Comment by r-ferrier** [comment]
it did! Phew!

**Comment by r-ferrier** [comment]
fixed in https://github.com/geeksforsocialchange/PlaceCal/pull/2289
