### ISSUE TITLE
[Bug]: address scrubbing rake task still references obsolete places table

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2295]
`FIXME`: Remove [this bit](https://github.com/geeksforsocialchange/PlaceCal/blob/293bd56b348f5e3291d8c2ec44112936e7d4d710/lib/tasks/db.rake#L274).

**Comment by katjam** [comment]
@ivan-kocienski-gfsc Please add acceptance Criteria for verification.
