### ISSUE TITLE
[Bug]: Reaching our email sending limit?

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2297]
## Description

See [rollbar](https://app.rollbar.com/a/gfsc/fix/item/placecal-production/399).

`Net::SMTPServerBusy 450 Your account reached its email quota limit. Contact support to increase it. #MS42204 Your account reached its email quota limit. Contact support to increase it. #MS42204`

**Comment by kimadactyl** [comment]
OK our limit was 100 without inputting card details and we reached it because of the spam - after putting in a card it's 3,000 but obviously we now need to be careful about getting a big spam attack.

**Comment by kimadactyl** [comment]
Also noting Mailersend has an SMS gateway if that's ever a thing we want.
