### ISSUE TITLE
[Bug]: calendar import event address database FK violation

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2298]
## Description

The Calendar importer is having a lot of problems of `"Internal database error for calendar Broadhurst Community Centre (id 49): PG::ForeignKeyViolation: ERROR: update or delete on table "addresses" violates foreign key constraint "fk_rails_2a2c9250e8" on table "events" DETAIL: Key (id)=(132) is still referenced from table "events". "`

See [49](https://admin.placecal.org/calendars/49/edit) as of 11-MAR-24

**Comment by aaaaargZombies** [comment]
## verified

Any calendars showing this issue are fixed by re-importing :confetti_ball:
