### ISSUE TITLE
Improve UI for adding a calendar by explaining the importer is running in the background

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2304]
## Acceptance Criteria

- [ ] When I update a calendar, it automatically queues for import
- [ ] I will see a confirmation message telling me the calendar is being imported and that I should check back in a few minutes

https://www.notion.so/gfsc/Kim-s-timeline-for-completion-12-3-24-d0e8ef7a03c44ba08e56d4477e3fea5d?pvs=4#92b415e5ca5d440f8840401d7dc94d1f

Maybe we can improve the UI here by letting the user know something like:
"The importer is now running, check back in 10 minutes to see if your calendar has been imported" 

Or maybe we could change the display names for the labels to something more informative than 'in worker'?

**Comment by kimadactyl** [comment]
i made some tickets before for these if at all useful

https://github.com/geeksforsocialchange/PlaceCal/issues/1124

https://github.com/geeksforsocialchange/PlaceCal/issues/1122

**Comment by ivan-kocienski-gfsc** [comment]
Maybe just a spinner animation at the top of the page when the calendar is in worker?

**Comment by kimadactyl** [comment]
Is there any way to get it to try and run straight away? I think the wait is a bit of a killer for people.

Perhaps another option would be to email after run completion so they can at least not have to sit looking at the screen?

**Comment by katjam** [comment]
@r-ferrier Do you have AC for this? It feels very related to: #2305

**Comment by ivan-kocienski-gfsc** [comment]
Can't be verified until #2430 is merged as you cannot see importer status on new calendars

**Comment by aaaaargZombies** [comment]
## verified


https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/1a5ebe04-a4e5-41d8-b483-708355229852



![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/622b3386-b44c-4a43-ae80-d27253462af2)
