### ISSUE TITLE
Confirm all import options are working as expected, make table of what sources support what features

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2306]
https://www.notion.so/gfsc/Kim-s-timeline-for-completion-12-3-24-d0e8ef7a03c44ba08e56d4477e3fea5d?pvs=4#866368f2339f483fa02cb409a1303e6e

**Comment by kimadactyl** [comment]
q from honor today was "what happens to the url field in ical?" just to record this

**Comment by ivan-kocienski-gfsc** [comment]
Having gone through all our supported sources I have mapped which fields we are pulling for each and how they map on to our event model.

↓ field name ↓ | Eventbrite | ical | meetup | squarespace | ticketsolve | ld+json | xml (manchester uni)
-- | -- | -- | -- | -- | -- | -- | --
uid | id | uid | id | id | id | url | ns:id
summary | name.text | summary | name | title | name | name | ns:title
description | description.text | description | description | body | description | description | ns:description
dtstart | start.local | dtstart | Time + utc_offset | startDate | opening_time_iso | start_date | (yes)
dtend | end.local | dtend | Dtstart + duration | endDate |   | end_date | (yes)
address | venue | location | venue |   |   | location.address |  
are_spaces_available |   |   |   |   | status |   |  
footer |   |   |   |   | url |   |  
publisher_url | url |   | link | url |   |   |  
online_address | url | x_google_conference | link |   |   |   |

**Comment by kimadactyl** [comment]
fantastic work ivan!

immediate thoughts:

- can we fill in any more blanks? (for e.g. is there really no address field for squarespace? does ticketsolve have no end date?)
- should room number be a sep field on our event model? (feel this is the one thing not clearly represented here)
- how can we maintain this going forwards? (can it be autogenerated or do we need a note to update it every time we tweak it somewhere?)

**Comment by kimadactyl** [comment]
oh and also does this answer honor's q, e.g. what happens to the URL field here?

<img width="283" alt="Screenshot_2024-03-25_at_13 56 54" src="https://github.com/geeksforsocialchange/PlaceCal/assets/511734/ed0f4e3e-e1f0-4736-9762-55b83d73fa66">

**Comment by ivan-kocienski-gfsc** [comment]
> fantastic work ivan!
> 
> immediate thoughts:
> 
> * can we fill in any more blanks? (for e.g. is there really no address field for squarespace? does ticketsolve have no end date?)

I think that'd be a fair chunk of work: we'd have to go through each source and figure out which fields best matches up with our columns.

> * should room number be a sep field on our event model? (feel this is the one thing not clearly represented here)

Maybe but do all the sources support room numbers? The code doesn't really have a concept of a room number and when such a strategy is selected on the calendar it just jiggles around the fields in the address model.

> * how can we maintain this going forwards? (can it be autogenerated or do we need a note to update it every time we tweak it somewhere?)

Has to be manually done.

> * the idea of "footer" was to give more context about where the event is coming from and link to it if appropriate - is this still the most appropriate place to give that info and the right name for the field?

Can't really say but it feels like this was put in for some specific source at some point but is rarely used. Just checked on my local prod snapshot and it is never used. As no one is using it I would drop it.

> * small note rows and cols are back to front on this (columns should be metadata, rows are data)

done.

> 
> perhaps a new ticket, but on my mind:
> 
> * is event image a thing we can support if the source has it?

Yes but how do we display that on the front end?

**Comment by kimadactyl** [comment]
> Maybe but do all the sources support room numbers? The code doesn't really have a concept of a room number and when such a strategy is selected on the calendar it just jiggles around the fields in the address model.

No so the idea of the option is that people can use the location field to _store_ a room number. This is for places like community centres who have a Outlook calendar and just want to put "big meeting room" in the location field for example.

Answers are all reasonable and need spinning into new tickets I think?

**Comment by katjam** [comment]
Closing as research part is done.
