### ISSUE TITLE
Make online events display more clearly or drop them

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2307]
https://www.notion.so/gfsc/Kim-s-timeline-for-completion-12-3-24-d0e8ef7a03c44ba08e56d4477e3fea5d?pvs=4#580a9c9b11a3496e93322aa48fed59ac

## AC

- [ ] assess if we have online events
- [ ] if we do mark them visibly on the index view and show view

## Implementation plan

Reference Marks designs for TransDim (in comments) and add an icon and words indicating if the event is online.

We do not have a way to check where the event is ie zoom and it would be a large job to cover all possible providers. Opt for "online" so as not to promote as specific brand over others.

## out of scope for this ticket but related
- [ ] #2331
- [ ] #2332

**Comment by studiosquid** [comment]
@kimadactyl we did explore this I think — there were lots of options done with lots of different grades of departures from the default event listing (nothing we ended up using I don't think) — I could dig out some of the better ones it's all in Trans Dim styling though?

**Comment by kimadactyl** [comment]
if you're able to drop a screenshot in here that would be amazing 🙏

**Comment by studiosquid** [comment]
I think these are the bulk of them — hopefully something useful :) 

<img width="938" alt="Screenshot 2024-03-18 at 15 38 30" src="https://github.com/geeksforsocialchange/PlaceCal/assets/9461465/fbc5d7fc-d8fd-4c7c-a48a-bac833fe8949">
<img width="951" alt="Screenshot 2024-03-18 at 15 38 36" src="https://github.com/geeksforsocialchange/PlaceCal/assets/9461465/e3b1c843-fe39-4ea7-aef6-b9bb1792328f">
<img width="923" alt="Screenshot 2024-03-18 at 15 39 07" src="https://github.com/geeksforsocialchange/PlaceCal/assets/9461465/dfa42104-d43a-4bbc-8942-f84b790a5c9c">

**Comment by r-ferrier** [comment]
```
irb(main):001> Event.where.not(online_address_id: nil).count
  Event Count (2.4ms)  SELECT COUNT(*) FROM "events" WHERE "events"."online_address_id" IS NOT NULL
=> 922
```

**Comment by ivan-kocienski-gfsc** [comment]
Verified on staging:

## Event show page
![Screenshot_2024-04-04_14-50-03](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/a7cbf34e-03e1-4cc1-acdc-0b68b4b76ea4)

## Event index page (on partner show page)
![Screenshot_2024-04-04_14-50-24](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/53035550-8659-4aa2-b25c-c37a7d65e8a5)
