### ISSUE TITLE
[Bug]: Fix list of calendars a site is importing

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2308]
https://www.notion.so/gfsc/Kim-s-timeline-for-completion-12-3-24-d0e8ef7a03c44ba08e56d4477e3fea5d?pvs=4#8560a17442944c39962e6ced22a42ba5

**Comment by ivan-kocienski-gfsc** [comment]
@kimadactyl what is the problem here? 

There is a list of Calendars on a Site 'show' page that is somehow broken?

**Comment by r-ferrier** [comment]
think this might be a dup of this @ivan-kocienski-gfsc https://github.com/geeksforsocialchange/PlaceCal/issues/2312

**Comment by kimadactyl** [comment]
yep - its a dupe of the other one
