### ISSUE TITLE
[Bug]: Fix openstruct error

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2309]
see rollbar for more in depth info:

https://app.rollbar.com/a/gfsc/fix/item/placecal-production/400

## A/C

- [ ] MountainView styleguide (i.e. [here](https://placecal.org/styleguide/styleguide/event)) doesn't exist (can't crash)

**Comment by katjam** [comment]
@ivan-kocienski-gfsc can you please add Acceptance Criteria for verification here?

**Comment by aaaaargZombies** [comment]
looks like it's still effecting staging https://placecal-staging.org/styleguide/styleguide/event

**Comment by ivan-kocienski-gfsc** [comment]
Did some digging in to this and it's not MountainView!

Somehow something is breaking when requesting any route that the app doesn't know about!?

I will make a new issue to dig in to this so this can be closed, again

**Comment by ivan-kocienski-gfsc** [comment]
Update: The problem this is flagging will be fixed by #2367

**Comment by aaaaargZombies** [comment]
## this is half verified

We no longer serve that problem page (does not exist as per AC) but Ivan has opened a new issue above which highlights the real underlying issues.
