### ISSUE TITLE
[Bug]: It is not clear when creating a partner that you can make one with just a service area

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2310]
## Description

It's not clear from the ui that you can create a partner with just a service area and not an address - we need to fix this in the hint text and in the validation. At the moment it makes it look like postcode is required.

It should be clear that a partner needs to provide *either* an address or a service area, but that a street address is not required. 

## Acceptance Criteria

- [ ] There is a clear description showing that your partner Address or Service Area (or both)
- [ ] There is no asterisk indicating that post code field is required
- [ ] There is no asterisk on the first line of address field.

**Comment by aaaaargZombies** [comment]
I think this would be resolved by #2301 if we decide to implement something that does live validation.

**Comment by kimadactyl** [comment]
Probably we need to workshop the help text here as this isn't the simplest thing to understand for new people.

**Comment by ivan-kocienski-gfsc** [comment]
Not verifying!

The error message when creating a partner with neither address or service area needs better wording (there are three suggestions)
![Screenshot_2024-04-04_14-12-34](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/2f3aac39-7c3e-4b43-aed8-33d1f0f4ba20)

But this message text is acceptable
![Screenshot_2024-04-04_14-13-00](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/df8cf69a-2f59-4310-b013-36c26eee3534)

**Comment by ivan-kocienski-gfsc** [comment]
See #2364

**Comment by katjam** [comment]
Re-opened because we need to get rid of the asterisk too.

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/773e088d-f62d-425c-af01-b9010315f685)

**Comment by katjam** [comment]
@honor-gfsc Do the Acceptance Criteria look right for your problem?

**Comment by ivan-kocienski-gfsc** [comment]
Verified on staging

## Partner admin form
Hint text is correct, no "mandatory field" asterisks on postcode field

![Screenshot_2024-04-24_10-54-11](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/e76ee8d6-59d4-4446-a80e-fe7a18dce323)

## Feedback when no address or service area is set up

![Screenshot_2024-04-24_10-55-19](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/6cd7e57f-3472-46f0-a46b-d4988ffa4609)
