### ISSUE TITLE
[Bug]: Calendar listing for partnership site (seems to) include all calendars for geographical area

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#2312]
## Description
Viewing the listing for a partnership based site's calendars

## Steps to reproduce (on staging - not verified in production)

1. view https://admin.placecal-staging.org/sites/consciouscollectivemcr

## What you expected to happen
I expected to only see calendars for the 4 partners in Conscious Collective but this list seems much too long for that

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/92bbe8e7-91a5-44b7-8a72-2ab3b3a777f3)

**Comment by ivan-kocienski-gfsc** [comment]
Verified on staging

![Screenshot_2024-04-04_14-54-49](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/9b80db0c-a264-4aca-a30f-e61d3cba324b)
