### ISSUE TITLE
[Bug]: Events can appear on a site that a partner does not belong to

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2324]
## Description

This may or may not be a bug, but it is an oversight in the current system design and presents some security questions so we may want to think about this:

- Currently, an event can appear on a place-based site if:
  - it belongs to a partner that is shown on that site OR
  - it has an address that is within that site's neighbourhood scope

A neighbourhood's admins can view (and therefore moderate) partners only if they are based in their neighbourhood. If a partner started creating events outside of their neighbourhood that should not be displayed on the site, the neighbourhood admin responsible for that neighbourhood would have no available actions to take to prevent their display.

Do we need to open up the scope for neighbourhood admins, so that they can also see all partners who have events in their neighbourhood? If we do this, do we also need to take the steps required at this stage to remove all other partner data from neighbourhood/partnership admins' views?

**Comment by aaaaargZombies** [comment]
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/1e484f09-42b4-40ee-86d8-932ab61ef002)

**Comment by aaaaargZombies** [comment]
probably related #1722

**Comment by r-ferrier** [comment]
We've decided that because we're going to allow partners to decide whether or not events can be connected to them, we don't need to worry about whether or not admins can see alll the partners who have listed events in their area because they can switch automatic event matching off as a handbrake if this becomes a problem.
