### ISSUE TITLE
replace all the instance hero images with the untreated ones

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2325]
No need for color treated background images on instance homepages as they are not text background but an image in their own right.

Should wait for next release.

## list of sites

- [ ] https://mossley.placecal.org,
- [ ] https://moss-side.placecal.org
- [ ] https://ardwick.placecal.org
- [ ] https://rusholme.placecal.org
- [ ] https://beeston.placecal.org
- [ ] https://christchurch.placecal.org
- [ ] https://westvale.placecal.org
- [ ] https://moston.placecal.org
- [ ] https://ol1.placecal.org
- [ ] https://london.placecal.org
- [ ] https://berwickshire.placecal.org
- [ ] https://trans-dimension.placecal.org
- [ ] https://climatejustice.placecal.org
- [ ] https://c2.placecal.org
- [ ] https://gmsc.placecal.org
- [ ] https://flourish.placecal.org
- [ ] https://oldham.placecal.org
- [ ] https://care-in-common.placecal.org
- [ ] https://exeter.placecal.org
- [ ] https://torbay.placecal.org
- [ ] https://norwich.placecal.org
- [ ] https://consciouscollectivemcr.placecal.org
- [ ] https://musicvenuetrust.placecal.org
- [ ] https://hulme.placecal.org
- [ ] https://manchester.placecal.org

**Comment by kimadactyl** [comment]
had a peek and i think it actually looks fine as is! 

the only thing that doesnt is not having one set - will ticket it

**Comment by aaaaargZombies** [comment]
closing, site admins can decide if they want to upgrade their image themselves.
