### ISSUE TITLE
[Bug]: Menu items move up due to underline on mouseover in firefox

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#2326]
## Description

https://github.com/geeksforsocialchange/PlaceCal/assets/861172/e828bb37-5226-4c76-97f6-d13681f6eb41

## Steps to reproduce

1. Hover over a menu item

## Platform (if relevant)

In firefox, reported by honor.

**Comment by kimadactyl** [comment]
I can't reproduce this and have a suspicion its a repeat of this:

https://github.com/geeksforsocialchange/PlaceCal/issues/1545

@honor-gfsc, can you check this in an incognito window or with your extensions turned off?

**Comment by kimadactyl** [comment]
will close, do reopen if it happens again
