### ISSUE TITLE
[Bug]: Calendar 150 is 501ing on admin view

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2328]
## Description

Browsing recent calendars

## Steps to reproduce

1.  Go here: https://admin.placecal.org/calendars/150/edit
2. Click "view this calendar"
3. https://admin.placecal.org/calendars/150
4. "We're sorry, but something went wrong."

Looks like [this](https://app.rollbar.com/a/gfsc/fix/item/placecal-production/409) is the captured problem on rollbar.

**Comment by aaaaargZombies** [comment]
issue fixed by issue kim linked

**Comment by ivan-kocienski-gfsc** [comment]
Nope, looks like this is a different problem from #2342

**Comment by ivan-kocienski-gfsc** [comment]
Research notes:

This is coming from [here](https://github.com/geeksforsocialchange/PlaceCal/blob/2f6bce843423c9fc44651e22c7a9dbd1b50d2c1d/app/views/admin/calendars/show.html.erb#L43)

It looks like this `notices` field is just a plain string when what this code needs is a struct with those specific fields.

What I believe is happening is that the calendar importer is trapping some legit errors but logging those errors into the calendar object `notices` field not in the correct way.
