### ISSUE TITLE
Deal with making new partners with the same name as an existing partner better

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2341]
## User story

As an organiser, I want to know if a new partner I am adding already exists before I fill in the entire new partner form, in order that I don't waste my time filling in info that already exists.

Motivation: the new partner form is very long, and organisers can't see every partner in the database, or might not look properly. It's currently frustrating to fill in that entire form to be told that {partner name} already exists. We should attempt to mitigate this much sooner.

<img width="420" alt="Screenshot_2024-03-08_at_11 58 04" src="https://github.com/geeksforsocialchange/PlaceCal/assets/511734/1023da4b-e638-472a-acb8-cbd4b81b0925">

## Acceptance criteria

- [ ] Partner name field gives much quicker validation OR appears as a separate first step

## Implementation notes & questions

Do we want to retain the uniqueness constraint on partner names? Not too unbelievable to think there would be more than one org with the same name -- but it would signficantly complicate this dupe detecting.

## Implementation plan

_To be written by the developer_

**Comment by katjam** [comment]
@ivan-kocienski-gfsc Can you please clarify acceptance criteria in terms of what was decided?

**Comment by aaaaargZombies** [comment]
## verified


https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/70644e68-85fd-4fc8-9367-c6d759df3ea3
