### ISSUE TITLE
[Bug]: 500 error if saving a calendar with a bad/missing source url value

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2342]
## Description

On admin calendar form, if the source URL is blank when saving, it crashes out with a `500` page.

See [rollbar](https://app.rollbar.com/a/gfsc/fix/item/placecal-production/411)

This is also the case if the URL is malformed (from [comment](https://github.com/geeksforsocialchange/PlaceCal/pull/2345#pullrequestreview-1966544359)):

![2024-03-28-15:21:26-screenshot](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/76148761-66af-49ec-9e46-889fd53b1c28)

**Comment by kimadactyl** [comment]
Is that the same as this? https://github.com/geeksforsocialchange/PlaceCal/issues/2328

**Comment by ivan-kocienski-gfsc** [comment]
I don't think so as that calendar has a source url set

**Comment by ivan-kocienski-gfsc** [comment]
Sorry kim, but yes it looks like it is!

**Comment by aaaaargZombies** [comment]
## verified

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/56729f59-ec81-4d3d-bcce-5ed06d876665)
