### ISSUE TITLE
[Bug]: Events are being matched up to partners through their address incorrectly

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2348]
## Description
See #1511 for context

The following event has been matched to a partner whose location is different from the event address.

 https://climatejustice.placecal.org/events/378308

They share a street address but have different postcodes, so we think there may be a bug in how this is resolving.

**Comment by r-ferrier** [comment]
blocked until we've decided what to do with addresses/partners/events

**Comment by r-ferrier** [comment]
no longer blocked because we have decided to keep the address matching logic but just make it optional

**Comment by ivan-kocienski-gfsc** [comment]
Verified on staging

## On production the wrong event appears on the partner
This partner has no events
![Screenshot_2024-04-24_15-27-23](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/bfe4c007-9ca3-4a44-88bb-202bcd54d60b)

## On staging it works
The event is matched to the correct partner
![Screenshot_2024-04-24_15-25-48](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/aff5c10c-0f64-4005-8c41-d0205feb55ba)
