### ISSUE TITLE
Should events be assigned to partners if their addresses 'match' ?

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2349]
## Description

See #1511 for context

At the moment, if a calendar is set to derive an event's address from the source calendar and not from the partner, the event can be assigned to a different partner if the event resolver determines there is an address match.

Some problems we see with this approach:

- partners have no control over which events are said to be hosted by them
- determining an address match is tricky. Do we require an exact string match on a street address and postcode? Some partners may operate out of the same location? 
- users of the system may not currently be aware of this behaviour and seeing events assigned automatically to your partner that you did not add yourself could erode trust

A related bug

- [ ] https://github.com/geeksforsocialchange/PlaceCal/issues/2348
- [ ] https://github.com/geeksforsocialchange/PlaceCal/issues/2324
- [ ] https://github.com/geeksforsocialchange/PlaceCal/issues/2372

**Comment by r-ferrier** [comment]
Read #833 as background context to this problem - we think the problem outlined here possibly clashes with privacy concerns and so may just need removing

**Comment by r-ferrier** [comment]
This ticket needs a bit of research to see where the events/addresses matching is happening and see how feasible it would be to unpick this. It also needs all the user stories writing out for why this is currently a problem and how this would be an improvement, so we can decide if this is the right path to take.

**Comment by ivan-kocienski-gfsc** [comment]
Going through the Calendar Importer: the (basic) steps for resolving addresses are described


When calendar is set to `event` strategy

Two things to be looked for: *Address* and *Place*

Given an event location value pulled from the remote source
strip out the country and postcode from that location, if present

1. Try looking up the location as a partner name, use this address if partner and address exist
2. Try finding the address based on `street_address`
3. Try finding the address based on postcode
4. Build a new address (which will do a postcode lookup)

Ignore place if no place found

Add a warning notice to the calendar if no address found and 'event' strategy is used.

## Proposed solution

Just do what we did with partners by having each Event having its own Address.

But the question arises: do we want to allow events to have an address anywhere or should they be constrained somehow? (like how users are constrained to their assigned neighbourhoods).

**Comment by katjam** [comment]
I think we 'could' constrain events to the partner's service area. In
theory a service area is a geographical location where you run services /
hold events. It may mean some clarification / alert that tells partners if
they have listed events outside their service area and prompt them to amend
it?

**Comment by r-ferrier** [comment]
One of the issues with this approach is that some events get their addresses from the input in the calendar and we have no way of constraining this at input level, so there would be some intermediary code that would need to then decide what to do with these events - do they get hidden? (sounds unhelpful) does their address get overridden with the partners' address? (also not helpful)

**Comment by r-ferrier** [comment]
reticketed under #2381

**Comment by ivan-kocienski-gfsc** [comment]
This may be helpful: How events are shown on the public site

 Note that it is impossible for an event to appear on a site without a partner (or place) - so at no time do we query `events` through `addresses` by themselves.


## Site `/events`
Given a `@site` we pull out its `owned_neighbourhood_ids` and use that to map on to addresses and service areas.

![how-events-are-mapped-to-site-index](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/6d752e75-198d-4a37-b2c2-da9c9b31a90f)

## Partner `/partners/:id`
![how-events-are-mapped-to-partern-show](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/b25a2d41-e521-4c5d-bbbc-604c4c4a3b3c)

## Also

I have left out how events are matched to sites via tags
