### ISSUE TITLE
connected entities alignment on partner form

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2351]
## description

apols to shoehorn in a tiny layout thing but it never seems worth making a sep ticket for!

could we use this opportunity to fix the whitespace to the left of "Connected entities" please? this got knocked out of whack at some point and would be nice to have it put back, it should be flush left with the save partner button.

if this is really annoying lmk and i will make a sep ticket

<img width="1288" alt="Screenshot 2024-03-28 at 11 56 47" src="https://github.com/geeksforsocialchange/PlaceCal/assets/511734/dcbb5ac4-ae25-44ee-bc84-88e263b99eca">

_Originally posted by @kimadactyl in https://github.com/geeksforsocialchange/PlaceCal/issues/2345#issuecomment-2025011046_
            
            
## AC

- [ ] left hand of connected entities section aligns with rest of form.

**Comment by ivan-kocienski-gfsc** [comment]
Verified on staging

![Screenshot_2024-04-04_15-08-50](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/2405baa6-2972-4b6f-a38d-2c34f325095e)
