### ISSUE TITLE
[Bug]: event date change causing failiure

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2355]
## Description

> I noticed when I changed the date of an event that PlaceCal didn’t update, and this was the message that greeted me when I went onto the back end

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/7cc2e024-e3f9-4bdc-b3ea-277441f1bb74)

https://norwich.placecal.org/partners/queer-norfolk

https://norwich.placecal.org/partners/norfolk-lgbt-history-club

## Steps to reproduce

1. What you did first
1. What you did next

## What you expected to happen

What would you like to happen instead?

## Platform (if relevant)

What device and browser were you using?

**Comment by ivan-kocienski-gfsc** [comment]
This looks like the same [problem](https://github.com/geeksforsocialchange/PlaceCal/pull/2299) that has been fixed and will be deployed next prod roll out
