### ISSUE TITLE
[New site]: Trans Dimension Manchester

### ISSUE THREAD

**Issue by honor-gfsc** [geeksforsocialchange/PlaceCal#2361]
# New site request

- Name of person: Sid
- Region covered: Greater Manchester
- Site name: Trans Dimension Manchester
- Desired colour scheme (pick one): pink
- [Optional] Interest covered: Trans Dimension [IMPORTANT: Will this add partners to transdimension.uk? For the moment we *do not want* that behaviour. If it will, can we use a placeholder Partnership Tag (of 'Trans Dimension Manchester') and bulk-add to the existing Trans Dimension tag later?]
- Domain: transdimensionmanchester.placecal.org

Info in responses here: https://docs.google.com/forms/d/15zYaKcKU56HeyjiCAvvO4vGk333ZNwpKUiF0V4m9nio/edit#responses including site admin contact info. 

## Acceptance criteria

- [x] site_name_slug.placecal.org exists!
- [ ] site_name_slug.placecal.org is not set to public
- [ ] site_name_slug.placecal.org has an SSL certificate added (see [handbook](https://gfsc.notion.site/Creating-a-new-PlaceCal-Site-bd90494c88e74bfe94c306f714ede8dc))
- [ ] Header and footer logos are created (preferably as svg), with transparent background
- [ ] Site has logos uploaded in correct places
- [ ] person_name is set as site admin
- [ ] person_name is set as neighbourhood admin for region_name
- [ ] If it's an partership-based site, person_name is set as partnership admin for partnership_name
- [ ] The [handbook](https://gfsc.notion.site/Creating-a-new-PlaceCal-Site-bd90494c88e74bfe94c306f714ede8dc) is accurate (make edits if not clear)
- [ ] person_name is informed their site has been created

**Comment by aaaaargZombies** [comment]
I'm going to change the url from `transdimensionmanchesrer.placecal.org` to  `trans-dimension-manchester.placecal.org` so screen readers (and humans) don't read it as a single word. I'm also assuming the end of the subdomain is a typo.

We could do with assets though we can create without.

- Logo header
- Logo footer
- instance homepage image

Sid will need a user account and they might want to set it up with a fresh email that they are happy to share with other users of placecal / be  displayed publicly.

**Comment by aaaaargZombies** [comment]
ok we're up and running at https://trans-dimension-manchester.placecal.org/ needs details adding but I think @honor-gfsc  you should be able to do everything with your root account, I've done SSH bits.

**Comment by r-ferrier** [comment]
closing as ticketed up in notion
