### ISSUE TITLE
[Bug]: fix text on partner missing location error message

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2364]
## Description

![Screenshot_2024-04-04_14-12-34](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/2f3aac39-7c3e-4b43-aed8-33d1f0f4ba20)

"...This usually means one of *two* things:"

**Comment by aaaaargZombies** [comment]
## verified

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/d755baba-5dec-45ac-81f2-0945774ad6de)
