### ISSUE TITLE
[Bug]: partnership sites showing partners not affiliated in the wifi / computer access part of instance homepage

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2365]
## Description

If you visit  https://consciouscollectivemcr.placecal.org/ you can see the partners on the homepage are not tagged with the relevant partnership.

**Comment by katjam** [comment]
We've also had multiple confirmations that Conscious Collective is defunct and has been for a long time, so we should remove as featured from our sales site (placecal.org) and consider removing affiliated data?

This is probably another issue, but maybe this one could be repurposed?

**Comment by aaaaargZombies** [comment]
it's effecting all placecal sites eg. https://trans-dimension-manchester.placecal.org/

I'll open a new issue for Concious Collective / site teardown

**Comment by kimadactyl** [comment]
oof this seems kinda serious, we should fix this i think

**Comment by kimadactyl** [comment]
Started having a look at this but this logic is a bit beyond me today:

https://github.com/geeksforsocialchange/PlaceCal/blob/70d46861a4d51a242f1550cc297b42df61a85966/app/models/partner.rb#L140

Also have very quickly discovered the test suite spaghetti. Maybe one we need to look at together @katjam?
