### ISSUE TITLE
Error reporting on Partner model could be useful to users

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2366]
The partner model has a number of custom validations that add flag up errors

- https://github.com/geeksforsocialchange/PlaceCal/blob/6b34264ee85b29cba33cae558a8f0ca137d26284/app/models/partner.rb#L502
- https://github.com/geeksforsocialchange/PlaceCal/blob/6b34264ee85b29cba33cae558a8f0ca137d26284/app/models/partner.rb#L509
- https://github.com/geeksforsocialchange/PlaceCal/blob/6b34264ee85b29cba33cae558a8f0ca137d26284/app/models/partner.rb#L516

Also:

The service area / address fields code could have an additional check after that checks if there are any errors on these fields and print them out (next to the input fields) so users can more easily identify the problem and fix it? Something like

```ruby
<% if @partner.errors[:address].any? %>
  <%= f.full_error :address %>
<% end %>
```

**Comment by kimadactyl** [comment]
This feels very speculative and not really like an issue to me - closing as wontfix but do reopen if you disagree.
