### ISSUE TITLE
[Bug]: 404 pages crash

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2367]
## Description

When visiting a page like https://placecal-staging.com/foofooofoo we are not shown the "404 page not found"

Digging in to this on local host, if you remove the static html pages from the `public/` folder and hit that path the dev server just haults. So something is very wrong deep inside rails (probably because of our code?).

It's also not being logged in rollbar (on staging)

## A/C
- [ ] Visiting an unrecognised path serves the standard 404 page.

**Comment by katjam** [comment]
Adding to Cycle 30 hotfix milestone as escaped validation

**Comment by katjam** [comment]
Verified on staging. I'm not sure I like that we don't have a themed `404` but this is clear message and not crash:
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/93f75a3e-9fcf-4010-a0e1-b5fe916a0ed2)

**Comment by katjam** [comment]
Moved back to cycle it was completed in following verification.
