### ISSUE TITLE
[New site]: Trans Dimension Wales

### ISSUE THREAD

**Issue by honor-gfsc** [geeksforsocialchange/PlaceCal#2377]
# New site request

- Name of person: Genevieve
- Region covered: Wales
- Site name: Trans Dimension Wales
- Desired colour scheme (pick one): pink
- [Optional] Interest covered: Trans Dimension Wales
- Domain: trans-dimension-wales.placecal.org

## Acceptance criteria

- [x] site_name_slug.placecal.org exists!
- [x] site_name_slug.placecal.org is not set to public
- [x] site_name_slug.placecal.org has an SSL certificate added (see [handbook](https://gfsc.notion.site/Creating-a-new-PlaceCal-Site-bd90494c88e74bfe94c306f714ede8dc))
- [ ] Header and footer logos are created (preferably as svg), with transparent background
- [ ] Site has logos uploaded in correct places
- [x] person_name is set as site admin
- [x] person_name is set as neighbourhood admin for region_name
- [x] If it's an partership-based site, person_name is set as partnership admin for partnership_name
- [ ] The [handbook](https://gfsc.notion.site/Creating-a-new-PlaceCal-Site-bd90494c88e74bfe94c306f714ede8dc) is accurate (make edits if not clear)
- [x] person_name is informed their site has been created

**Comment by kimadactyl** [comment]
@honor-gfsc i think this is done right?

@undividual do you think you could maybe make logos for transdim london, wales and manchester respectively just so my brain doesnt short circuit when im looking at them? and upload them?

https://trans-dimension.placecal.org/
https://trans-dimension-wales.placecal.org/
https://trans-dimension-manchester.placecal.org/

**Comment by honor-gfsc** [comment]
Have ticked everything that's done as far as I know. Not sure about Handbook edits mentioned here? Otherwise just the graphics

**Comment by aaaaargZombies** [comment]
> Have ticked everything that's done as far as I know. Not sure about Handbook edits mentioned here? Otherwise just the graphics

the handbook bit just means to update it if the guide is confusing and you need to do something different so probably not needed.

**Comment by aaaaargZombies** [comment]
## verified

Could do with graphics but those are optional and can be left to the organizer to choose, it is up and running,

**Comment by undividual** [comment]
Might be too late now but would people still like me to look at this tomorrow? Will they get used if I do? I have no idea why Github didn't notify me about this last week when Kim originally @'d me

**Comment by kimadactyl** [comment]
i think its a nice detail but its far from a priority so up to you - and yes theyll get used but do just upload them yourself :)

**Comment by undividual** [comment]
This is now complete FYI.
