### ISSUE TITLE
Give partners control over third party event listings

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2381]
## Description

From conversations with Rakesh: Having an events grouped by partner is useful, having events grouped by place is not useful. The link between partner and event should be based on who created the event, not where the event is based.

## Acceptance criteria
- [ ] as a partner admin I can decide whether or not my partner displays events from other partners' calendars
- [ ] If a partner allows 3rd party events to be listed under them and there is an Event from another partner with their address, public can see the event under both partners
- [ ] As a partner admin, it is clear to me from the UI that I can toggle on and off 3rd party events listings for all partners, not individual partners
- [ ] As a partner admin, when I toggle on and off 3rd party event listing allowed, the events appear and disappear immediately (i.e. the relationship of the event with my partner is not determined on what my setting is at the time of import)
- [ ] The calendar importer only parses the raw event data into the database. e.g. It does not make links between entities.
- [ ] In the case that an event is additionally listed by a "host venue" partner outside the geographical area of the partnership/neighborhood admin, the admin will not be able to see the partner in their admin interface (though obviously they can see the listing on the public site)

## Related
- [ ] #2403

## Plan
- [ ] A partner has a field `can_be_assigned_events` with a description `Events that have the same address as this partner will be assigned to this partner on PlaceCal` (copy tbc)
- [ ] If `partner.can_be_assigned_events` then when the calendar importer runs, it is allowed to make connections between partners and events if they share the same address
- [ ] The calendar importer matches addresses from events to partners, and not to conceptual places
- [ ] Addresses are not shared but are matched on the fly by the code

## Blocked by this/ should be fixed as part of this
- [ ] https://github.com/geeksforsocialchange/PlaceCal/issues/2348
- [ ]  #2372

**Comment by katjam** [comment]
@r-ferrier @ivan-kocienski-gfsc as agreed earlier, I've expanded on these acceptance criteria. They could use a sanity check, linking out to other existing issues that are related and maybe additional criteria that spring to your mind on reading mine.

**Comment by ivan-kocienski-gfsc** [comment]
Verified on staging

## Form input on partner edit
![Screenshot_2024-04-24_15-47-57](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/7e307269-3491-4448-ba8a-adae1c37470b)
