### ISSUE TITLE
[Bug]: Site homepages have default PlaceCal boilerplate text even if other fields are set

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2384]
## Description

I feel like the "PlaceCal is working to make Greater Manchester a better connected neighbourhood" text shouldn't be here if the other text is set - its kinda confusing?

It also says "We're working with [local organisations](https://trans-dimension-manchester.placecal.org/partners) and [places](https://trans-dimension-manchester.placecal.org/places) to create a great calendar of everything that's on in Greater Manchester.". But the places link isn't a thing any more.

I think this section of the page needs a rework? Right now from a content perspective this feels like a hot mess.

<img width="1124" alt="Screenshot 2024-04-10 at 17 17 21" src="https://github.com/geeksforsocialchange/PlaceCal/assets/511734/4f09308c-3426-4ce9-9ac3-4bd229421c87">

## AC

- [ ] Remove "Placecal is working to make..." text
- [ ] Remove outdated  `Place` link

## Steps to reproduce

1. Set hero text and description in the admin interface: https://admin.placecal.org/sites/trans-dimension-manchester/edit
2. Text I can't control that seems out of context is coming up higher than the text I can control

## What you expected to happen

1. Remove this: 

> "PlaceCal is working to make Greater Manchester a better connected neighbourhood.
> 
> We're working with [local organisations](https://trans-dimension-manchester.placecal.org/partners) and [places](https://trans-dimension-manchester.placecal.org/places) to create a great calendar of everything that's on in Greater Manchester."

2. Get rid of "about us" subheading

3. Move "see whats on" text below "We collate news, events and services by and for trans people."

## Platform (if relevant)

What device and browser were you using?

**Comment by r-ferrier** [comment]
verified:

![Screenshot 2024-04-24 at 13 30 06](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/0054eb2a-8f52-4172-ae3b-43de1db82eda)
