### ISSUE TITLE
Decommision Conscious Collective site

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2394]
## Description

We've also had multiple confirmations that Conscious Collective is defunct and has been for a long time, so we should remove as featured from our sales site (placecal.org) and consider removing affiliated data?

_Originally posted by @katjam in https://github.com/geeksforsocialchange/PlaceCal/issues/2365#issuecomment-2039725411_

Should we think about a similar template / process that is the mirror of setting up a site?

**Comment by kimadactyl** [comment]
Deffo remove from the public site. Can maybe replcae with Tipping Point if we can get an OK from them sooner than later.

**Comment by kimadactyl** [comment]
Closing as this is a content q not a code one and it's been de-listed from the main site
