### ISSUE TITLE
Add terms of use policy

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2396]
Draft here: https://www.notion.so/gfsc/PlaceCal-Terms-of-Use-f05370f644dd45358e9e9a0afa9630d5?pvs=4

## Prerequisites
- [x] Dev team sign off draft
- [x] Content team sign off draft
- [x] Final version

## Acceptance criteria
- [x] A link in footer that says "Terms of use"
- [x] Add new page for it (i.e. `/terms-of-use`)
- [x] There is a reference to term-of-use in the email that goes to new users so people signing up for accounts are aware they are agreeing to them
- [x] There is a reference to terms-of-use in the new user form so admins are aware they are asking folks they sign up to adhere to them

## Post merge A/C
- [ ] There is a reference to the terms-of-use in the handbook

**Comment by katjam** [comment]
@ivan-kocienski-gfsc I added a couple more AC which can be sharded to a new issue about linking to the terms from user sugnup process. If another place occurs to you, please add there too.

**Comment by kimadactyl** [comment]
@katjam / @honor-gfsc coming back to this i am a bit confused still what AC you want me to put here - could someone please update? right now my PR does fulfill these so just checking if I've missed something or not.

**Comment by katjam** [comment]
That's perfect then! Not sure who ticked the AC as they'd normally be ticked when verified on staging - but this looks good now.

**Comment by kimadactyl** [comment]
I ticket them to keep track, oops :)

I mean they've been there all along jsyk from before I started working on it - I'm a bit confused? Are we good then?

**Comment by katjam** [comment]
I've not actually reviewed that code - which is mostly Ivan's work, right? The last 2 AC were the one's outstanding I think when he went because we hadn't had time to have the conversation with you before putting up the PR. So if they are covered then I think we are OK in terms of a baseline of consent to the terms.

**Comment by kimadactyl** [comment]
OK! I will double check they're all met, then. Yes, they were covered already tho - this is why I've been so confused!

**Comment by katjam** [comment]
Ah, I see... maybe it is literally then that we were waiting to hear if you agreed with the strategy! Also confused... sorry for adding to it.

I'm at hours this week, but probably will make time to get through rest of these PRs later today.
