### ISSUE TITLE
[Bug]: Calendar 153 is erroring when viewing in the admin interface

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2401]
## Description

Browing recent calendars

## Steps to reproduce

1. Go here: https://admin.placecal.org/calendars/153/edit
2. Click "view"
3. Links to here: https://admin.placecal.org/calendars/153
4. "We're sorry, but something went wrong."

See [this](https://app.rollbar.com/a/gfsc/fix/item/placecal-production/409) rollbar log.

## What you expected to happen

What would you like to happen instead?

## Platform (if relevant)

What device and browser were you using?

**Comment by ivan-kocienski-gfsc** [comment]
@kimadactyl this has been fixed but not yet deployed to production.

PR: https://github.com/geeksforsocialchange/PlaceCal/pull/2375

This now works -> https://admin.placecal-staging.org/calendars/16

(The problem was how notices get displayed.)

**Comment by r-ferrier** [comment]
I can't verify this because we have nothing with notices in it and now that we allow users to import calendars without addresses it's almost impossible to create one! Closing as verified because I can see it works locally.
