### ISSUE TITLE
UI updates to make clearer how the calendar importer works

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2403]
## AC

- [ ] It is clear in the Calendar importer UI (under Location strategy section) that a Partner can opt for their events located at 3rd party venues to be listed on that venues PlaceCal (as well as their own), but only in the instance that 1- that venue exists as a partner on PlaceCal and 2- that partner has allowed it (for everyone)
- [ ] It is clear in the Calendar importer UI (under Location strategy section) how to construct an Event address so that it gets matched with a partner & that the partner has to be open to including 3rd party events.
 - [ ] It is clear in the Calendar importer UI what is meant by event Location strategy and what the consequences of each choice are
 - [ ] It is clear that an event can be listed in a PlaceCal in a different geographical location to that of the Partner who's calendar it is in

## Copy document

https://www.notion.so/gfsc/Calendar-Importer-Strategy-text-d18d96f0212a46349d9c11974b7ad91e

**Comment by ivan-kocienski-gfsc** [comment]
requires [cCc] content until copy written

**Comment by ivan-kocienski-gfsc** [comment]
- Calendar importer UI
  - Under location strategy section
    - [ ] that a Partner can opt for their events located at 3rd party venues to be listed on that venues PlaceCal (as well as their own), but only in the instance that 
      1. that venue exists as a partner on PlaceCal
      2. that partner has allowed it (for everyone)
    - [ ] how to construct an Event address so that it gets matched with a partner & that the partner has to be open to including 3rd party events.
  - [ ] what is meant by event Location strategy and what the consequences of each choice are
- [ ] It is clear that an event can be listed in a PlaceCal in a different geographical location to that of the Partner who's calendar it is in

**Comment by katjam** [comment]
Someone from dev team should work with @honor-gfsc to get this drafted and added.

**Comment by ivan-kocienski-gfsc** [comment]
Verified on staging

![Screenshot_2024-04-24_16-02-00](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/47f6481b-c877-4152-93eb-a34cce3123e8)
