### ISSUE TITLE
[Bug]: "show all" doesn't show all events if date range in url

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2410]
## Description

This might be desired behaviour but I think it's confusing.

If you select a date using the pagination then change to `future` / "show all" in the form, it shows you the future from that date. This may be no events even though events exist on the system.

Should probably change from to future or have date reset.

https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/9234169e-001c-4bf4-814c-38bd3059972d

## Acceptance Criteria

- [ ] When I select all events it shows me from today even if I have been browsing by dates in the future

**Comment by r-ferrier** [comment]
Verified. Date before selecting future:

![Screenshot 2024-04-24 at 12 48 43](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/97b91d41-71a6-402f-aca2-a7757cd6e6a8)

Date afterwards:

![Screenshot 2024-04-24 at 12 50 22](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/a4710832-b161-4284-adf2-75238965cde5)
