### ISSUE TITLE
[Bug]: URL fields from non-Google calendars are not imported 

### ISSUE THREAD

**Issue by honor-gfsc** [geeksforsocialchange/PlaceCal#2417]
## Description

When adding URL information to a non-google .ics feed this is not picked up by the PlaceCal importer

## Platform (if relevant)

Example non-Google .ics feed https://ambition.rip/public_calendar.ics
PlaceCal event which has not pulled through the URL https://norwich.placecal.org/events/380062

## A/C

- [ ] events imported from an ical feed containing a `URL` field have the information from this field imported and stored
- [ ] events with online information are flagged as such in the events index
- [ ]  change "stream" to "button" on button on Rosie's screenshot in comment below

**Comment by ivan-kocienski-gfsc** [comment]
So as it stands it looks like we only accept URLs from
- meet.jit.si
- meet.google.com
- zoom.us
- facebook.com

There is a chunk of logic to determine if these are 'direct' (i.e. a zoom link) or 'indirect' (i.e. a facebook link).

Unfortunately because of how it works even if we can find a URL *only* URLs from those domains will be allowed.

I think maybe we should just not have the "link type" and just give them a per-event URL if it is present in the remote data.

**Comment by ivan-kocienski-gfsc** [comment]
So the simplest solution here is to keep all the logic about "direct" links in place and then make any URL that is not a direct link in to an indirect link and just store it as before

**Comment by r-ferrier** [comment]
I'm not sure if this is quite working how we want it to. An event with a URL in its address imported with the 'online_only' strategy looks like:
![Screenshot 2024-04-24 at 14 49 34](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/649b9eaf-118a-44e2-b044-38791f2829c5)

An event with a URL in its URL box (could only find this on an ical) looks like:
![Screenshot 2024-04-24 at 14 49 48](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/748209bc-f5c4-4ff0-804a-9829c6f0a239)

I feel like the button saying 'visit webpage for this stream' is a bit confusing, and adding the URL in the address field has produced a more understandable event, but I'm not sure why it has saved this info but not saved it as being `online`. Maybe something for us to have a bit of a look at again?

**Comment by aaaaargZombies** [comment]
## verified

closing as verified will reticket button thing
