### ISSUE TITLE
If partners are set to invisible, make this really clear at the top of the partner page

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#2419]
## Acceptance Criteria

- [ ] If a moderator has hidden a partner, the edit form should make that clear
- [ ] Fix same time? https://github.com/geeksforsocialchange/PlaceCal/issues/2364

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/f3909312-6d13-45b7-b209-cf96f6c61139)

## Note

It looks lie there is a box that shows up if the partner is hidden. [here is the code](https://github.com/geeksforsocialchange/PlaceCal/blob/5a286f69e9d197fa5a5b92be65a96c130be19856/app/views/admin/partners/_form.html.erb#L4-L16) but for some reason it is not triggered.

**Comment by ivan-kocienski-gfsc** [comment]
Should this just be a box that says something like
```
This partner is `hidden` and cannot be seen on the public site.
```

And if the hidden message is present then should we not show the warning box highlighted in red in the image above?

**Comment by aaaaargZombies** [comment]
Pulling out of the milestone as we seem to be in the habit of "making more clear" by moving what ever the current issue highlights to the top of the form.

We think the form generally needs some design work to decide what is important and how how it should be displayed.

**Comment by katjam** [comment]
Verified. Could be better n that not appear message appears on it's own for partnership admins which means it's not immediately obvious the cause is that they have hidden the partner.

Partner admin view
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/2b592e7b-fd95-4499-afc9-ed96ba2035eb)

Partnership admin view
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/9d3c128a-3bc4-4acb-bcb4-23437e336903)
