### ISSUE TITLE
Every event has a listed partner creator/owner

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#2426]
## Acceptance criteria

- [ ] On an event show page I can see contact info, its address, any linked partner and the organiser

## Design suggestion for event where whole event is shown

![Screenshot 2024-04-17 at 17 35 57](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/449bc9bc-49e7-4621-bfa1-346a4d6cc69b)

**Comment by ivan-kocienski-gfsc** [comment]
Verified on staging

## Events index
![Screenshot_2024-04-25_09-34-26](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/523b49a4-2b44-4d6b-b375-75b53dff2cac)

## Event show
![Screenshot_2024-04-25_09-35-16](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/29c9a029-394a-4a67-b808-e4f0368dc8c9)
