### ISSUE TITLE
[Bug]: In `Event.for_site` scope on event model

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2431]
## Description

[This line](https://github.com/geeksforsocialchange/PlaceCal/blob/ebbc5aea94015457f6ff15dbd549ca4691973932/app/models/event.rb#L84) assumes every partner has an address, and they do not

Found on staging and 78 partners have no address

**Comment by ivan-kocienski-gfsc** [comment]
This line will fix it:
```ruby
  partner_postcodes: partners.map(&:address).keep_if(&:present?).map { |a| a.postcode.downcase }
```

**Comment by katjam** [comment]
Adding to Cycle 30 hotfix milestone as escaped validation

**Comment by katjam** [comment]
Move to cycle 29 following verification. Made assumption that we'd get a 500 if this was still broken as there are lots of partners on staging without addresses.
