### ISSUE TITLE
Event location URLs

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2437]
## User story

As a user who has set up a calendar with events that have URLs as their location, I want these URLs to be links on the event / partner pages

## A/C
- [ ] any event that has a URL location should have a link to that URL and be marked as "online" (regardless of PlaceCal calendar strategy).

**Comment by katjam** [comment]
Adding to hotfix milestone because this did not get verified with Cycle 30 release.
