### ISSUE TITLE
[Bug]: Home page has redundant link

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#2441]
## Description

Visiting homepage of site. Now that Places is deprecated as a concept, the link to Partners shows the same view. We might want to revisit this copy.

## Steps to reproduce
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/bb78de03-16cd-49e5-90fa-39b18442c344)

**Comment by kimadactyl** [comment]
<img width="1135" alt="Screenshot 2024-04-29 at 15 53 16" src="https://github.com/geeksforsocialchange/PlaceCal/assets/511734/b58546f0-f808-4334-a902-ce1ea78baa3c">

looks like this was fixed somewhere along the line!
