### ISSUE TITLE
[Bug]: Remove white space around partner name

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2450]
## Description

We have one "The Proud Trust" and one "The Proud Trust ". This has allowed it to be duped. Suggest we trim whitespace from before and after partner names.

<img width="1222" alt="Screenshot 2024-04-29 at 15 47 23" src="https://github.com/geeksforsocialchange/PlaceCal/assets/511734/06659e16-8c0f-405c-9032-4f2e493b9b79">

## What you expected to happen

Partner names can't have white space before or after them.

**Comment by katjam** [comment]
Verified on staging:

input:
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/8ee9112d-c8ea-40df-b7c7-2d587b6a769f)

after save:
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/7abc3ea5-ac59-4104-b40e-6a1644b95f55)

**Comment by katjam** [comment]
As noted in #2452 we might want to revisit this if we were expecting it to strips double spacing within the name as implied in this  conversation: https://discord.com/channels/534700660327841792/903369904860839946/1235545927683670117
