### ISSUE TITLE
[Bug]: Trim whitespace around address lines

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2452]
## Description

Noting there's some whitespace issues here on partner addresses

<img width="585" alt="Screenshot 2024-04-30 at 11 28 26" src="https://github.com/geeksforsocialchange/PlaceCal/assets/511734/cc31a9e7-e988-4d26-943d-77070550e1fd">

<img width="415" alt="Screenshot 2024-04-30 at 11 31 21" src="https://github.com/geeksforsocialchange/PlaceCal/assets/511734/6579a148-3801-470e-9b04-348d91363464">

## Steps to reproduce

1. What you did first
1. What you did next

## What you expected to happen

Address lines are stripped of whitespace

**Comment by katjam** [comment]
Verified top and tail trim - but I thought the point of using gem was for more nuanced treatment. Awaiting sign off to clarify expected behaviour.

**Comment by kimadactyl** [comment]
Ooops - I didn't read the docs properly. It can do this but needs extra params passing!

https://github.com/holli/auto_strip_attributes?tab=readme-ov-file#howto--examples

**Comment by katjam** [comment]
> Ooops - I didn't read the docs properly. It can do this but needs extra params passing!
> 
> https://github.com/holli/auto_strip_attributes?tab=readme-ov-file#howto--examples

Do we care enough to re-open?

**Comment by kimadactyl** [comment]
I think if we make a new ticket it should prob be a bit of a thorough review of all our validations. Things like double spaces in the middle of partner names sounds niche enough if we are going that route let's do it properly with some proper IRL use cases. So up to you?

Or maybe that's overcomplicating and we should just add the extra flags, who knows lol. I'm happy to leave closed for now.

**Comment by katjam** [comment]
Me too. I think we've covered the most likely error by trimming.
