### ISSUE TITLE
[Bug]: Partnership admins cannot create new partners

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2454]
## Description

trying to create a new partner. 2 things seem to be going wrong:

1. Partnership is not auto-filled
2. Partner can't be saved - see error

<img width="1152" alt="Screenshot 2024-05-01 at 11 41 20" src="https://github.com/geeksforsocialchange/PlaceCal/assets/511734/7f438c3e-815f-4aaa-bdb4-bf2cc7988c16">

## Steps to reproduce

1. Logged in as a partnership admin (sid)
2. Created a new partner
3. Pressed save

## What you expected to happen

1. Partnership is auto-filled
2. Partner can be saved

## Platform (if relevant)

What device and browser were you using?

**Comment by kimadactyl** [comment]
Code where this changed here: https://github.com/geeksforsocialchange/PlaceCal/pull/2412/files#diff-a237b43fed12cdc9f36a97cc055dea3c60cdac1da5779da7cb0861fa75f81564

**Comment by katjam** [comment]
Verified on staging:
