### ISSUE TITLE
[Bug]: Ugly unicode glyph showing for online events on iOS and firefox mobile

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2458]
## Description

**Reported by someone using iOS safari**

visible here: https://london.placecal.org/events

![IMG_5945](https://github.com/geeksforsocialchange/PlaceCal/assets/511734/45399bba-9026-4350-9f84-0a2cf057b131)

**This is also happening on firefox mobile**

![signal-2024-05-16-132506](https://github.com/geeksforsocialchange/PlaceCal/assets/511734/706436db-9e79-4a91-a401-8acad796ab5a)

## What you expected to happen

Replace with Mark's nice icon so we have platform standardisation

https://github.com/geeksforsocialchange/PlaceCal/pull/2327#issuecomment-2018464258

## Platform (if relevant)

iOS Safari, Firefox mobile

**Comment by kimadactyl** [comment]
We could consider using this: https://github.com/fontello/fontello/wiki/How-to-save-and-load-projects#ruby-way---use-fontello_rails_converter-gem

**Comment by studiosquid** [comment]
@kimadactyl heya, I think they were provided differently (I can't actually find the original SVGs — so I suspect they went straight from Sketch back in the day maybe?) I wasn't expecting them to go into a font — anyway reexported the full set with the clearance I gave them all when I created them but now as SVGs — they should all balance out as they were created in the original file as shown in the screenshot below. I quickly tested and I think it works ok now.

<img width="1451" alt="Screenshot 2024-05-23 at 14 56 16" src="https://github.com/geeksforsocialchange/PlaceCal/assets/9461465/02cb3eac-33da-430e-800e-3a49f531b016">

![PlaceCal_Icons-01](https://github.com/geeksforsocialchange/PlaceCal/assets/9461465/5f457760-81cd-4150-879b-93e4cc635a4c)
![PlaceCal_Icons-02](https://github.com/geeksforsocialchange/PlaceCal/assets/9461465/2d6b48c5-683d-4047-83cf-f18e21409f1e)
![PlaceCal_Icons-03](https://github.com/geeksforsocialchange/PlaceCal/assets/9461465/c120c161-0d56-4c1f-9fa4-59994d17b280)
![PlaceCal_Icons-04](https://github.com/geeksforsocialchange/PlaceCal/assets/9461465/f5404933-6a10-42b6-9bab-4d05e4e89e8f)
![PlaceCal_Icons-05](https://github.com/geeksforsocialchange/PlaceCal/assets/9461465/c9d7a1cd-2760-4999-a566-568a94cea291)
![PlaceCal_Icons-06](https://github.com/geeksforsocialchange/PlaceCal/assets/9461465/8dd2aace-6893-4599-8107-48dbefb0e21b)
[zipoficons.zip](https://github.com/geeksforsocialchange/PlaceCal/files/15418099/zipoficons.zip)

**Comment by kimadactyl** [comment]
Cheers, looks great :)
