### ISSUE TITLE
[Bug]: Contact information data is not always feeding through to graphql

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#2474]
## Description

View contact details on Trans Dimension for Material Grrrlz

There are more notes in the TransDim repo. Don't have time to write out here now, but basically need to chack what data is coming out of the graph QL so we know whether it's a fornt or backend issue

**Comment by kimadactyl** [comment]
Looks like having blank entries for contact info is erroring out the whole object.

```sh
curl -v -X POST -H "Content-Type: application/json" -d '{"query": "query { partner(id: 289) { id summary url contact { name email telephone } } }" }' https://placecal.org/api/v1/graphql
```

Returns

```json
{"data":{"partner":{"id":"289","summary":"Material Grrrlz is a community of fiber artists dedicated to celebrating the work of young women \u0026 queer people💗","url":"https://www.materialgrrrlz.com/about-us","contact":null}},"errors":[{"message":"Cannot return null for non-nullable field Contact.telephone"}]}%
```

If you set `email` to blank it does the same.
