### ISSUE TITLE
Review which sites we are linking to from https://placecal.org

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#2480]
Some of them are out of date and we have at least 2 new active ones.

## Acceptance Criteria

- [x] Conscious Collective does not appear on https://placecal.org
- [ ] Manchester Trans Dimension appears on https://placecal.org
- [x] Climate & Migrant Justice North East appears on https://placecal.org
- [x] Mossley appears on https://placecal.org
- [ ] Hulme appears on https://placecal.org
- [ ] More place based changes...
- [ ] More interest changes tbc...

**Comment by kimadactyl** [comment]
Related to https://github.com/geeksforsocialchange/PlaceCal/issues/2394

**Comment by kimadactyl** [comment]
Confirmed working! Have made a few changes.

**Comment by katjam** [comment]
Nice. Should we close this then? Or are there related code changes you want to make? @kimadactyl

**Comment by kimadactyl** [comment]
Sure, we can say anything to do with this is now a content issue not a technical one. It would be nice to have better sorting I think, right now it is ordered by site ID, but that's a new ticket.
