### ISSUE TITLE
[Bug]: Upgrade heroku in buildpack to support Ruby 3.3.1

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#2483]
## Description
Renovate upgraded Ruby from 3.1.x to 3.3.x - Our buildpack does not support that so deploy is currently broken.

https://github.com/geeksforsocialchange/PlaceCal/actions/runs/9187309397/job/25268127334

If it's not a quick fix, we will roll back that PR so that we can get our partner event listing bugfix released

Docs:
https://dokku.com/docs/deployment/builders/herokuish-buildpacks/

**Comment by katjam** [comment]
slight tinkering:

dokku buildpacks:add placecal heroku-22
 !     Invalid buildpack specified: heroku-22

 dokku ps:rebuild placecal -> takes ages and doesnt change anything
according to the docs, apt should be upgrading dokku

dokku buildpacks:list placecal
-----> placecal buildpack urls
       https://github.com/heroku/heroku-buildpack-nodejs.git
       https://github.com/heroku/heroku-buildpack-ruby.git

bit odd
maybe i have the wrong name for it
i think its changed a bit since i worked on it, it used to be in a config file and now i think its in some docker config maybe?
Kim
 — 
Yesterday at 12:58

dokku buildpacks:report placecal
=====> placecal buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-18
       Buildpacks global stack:       gliderlabs/herokuish:latest
       Buildpacks list:               https://github.com/heroku/heroku-buildpack-nodejs.git,https://github.com/heroku/heroku-buildpack-ruby.git
       Buildpacks stack:              gliderlabs/herokuish:latest-18


yeah this is the issue. that latest-18 url i cant work out how to upgrade, i think thats 2018 so very old and should be latest-22
i give up now tho
can try agan later
truly hope our 2020 ubuntu isnt blocking the dokku upgrade wiht apt 😬
Katja
 — 
Yesterday at 14:04
I'm sure it'll be fine. I made an issue earlier which has a link to the docs about ways to specify buildpacks. I think probably worth adding in config, If you want to work on it before tomorrow take me off the issue so I know. I'm a little in transit.
Kim
 — 
Yesterday at 14:07
yeah i saw we could specify a .buildpacks config but im not 100% convinced its wrong im worried its not grabbing latest version
Katja
 — 
Today at 09:38
It does seem like something in our stack is making it not go above 18 - which makes me wary. This is the kind of thing that happens when packages get out of sync and it's usually better to upgrade everything at the same time... at least I find that in my own system.
I think we could force it to upgrade just that buildpack https://dokku.com/docs/deployment/builders/herokuish-buildpacks/#customizing-the-buildpack-stack-builder but also if we are on ubuntu 20 we ought to be able to get heroku-20 which is in active support for another year.
Katja
 — 
Today at 09:45
That's normal. I think only even years are LTS. 20.04.4 is from Feb 2022, so maybe if we update to 20.04.6 which is from Mar 2023, we'll get the new buildpack? https://wiki.ubuntu.com/Releases

**Comment by kimadactyl** [comment]
just noticed this today - the buildpack is there its just not being refd

```sh
$ docker image ls
REPOSITORY             TAG         IMAGE ID       CREATED         SIZE
dokku/placecal         latest      e4fff60743b1   2 days ago      1.31GB
<none>                 <none>      f271ead9cdf5   4 days ago      2.1GB
gliderlabs/herokuish   latest-20   5b8865c0c1ef   2 months ago    1.51GB
gliderlabs/herokuish   latest-22   1d47097ce2fb   2 months ago    1.05GB
gliderlabs/herokuish   v0.9.1-22   1d47097ce2fb   2 months ago    1.05GB
dokku/metabase         latest      0ca28bb26b5f   9 months ago    1.61GB
gliderlabs/herokuish   latest-18   acde76e134d5   12 months ago   1.26GB
postgres               13.4        d3ae557d4662   2 years ago     371MB
goacme/lego            v4.3.1      81cdaf04adc3   3 years ago     54.9MB
```

**Comment by kimadactyl** [comment]
This might be good to go now: https://github.com/heroku/heroku-buildpack-ruby/issues/1465

**Comment by kimadactyl** [comment]
OK, worked out how to update the buildpack. This should work now after the following command has been run, but I don't want to delay this release any longer:

```
dokku buildpacks:set-property placecal stack gliderlabs/herokuish:latest-22
```
