### ISSUE TITLE
Add a PR template

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2501]
## Description

We should prob have a PR template that prompts the author and reviewers to do some sanity checks including:

- [ ] Removing console.logs and prints and things
- [ ] Moving strings into locale files as we go
- [ ] Moving mountain_view components into view_components as we go
- [ ] Making sure code is in the right place  (e.g. separation of concerns)
- [ ] Making sure tests are in the right place
- [ ] Adding inline documentation to non-trivial methods
- [ ] A statement about what is tested for and what isn't and why
- [ ] Prompt to consider method and field naming before merge
- [ ] Prompt to consider refactoring and DRY considerations

## Motivation

Let's just do housekeeping as we go.

**Comment by katjam** [comment]
There are some notes around improving templates: https://www.notion.so/gfsc/Update-our-repo-docs-especially-Issue-PR-templates-a81771e1b7414397b45068319c7e738b?pvs=4

Common knowledge has [one](https://github.com/commonknowledge/.github/blob/f024732fbcc65613c7d3187c2d4b9ef2693331fa/.github/pull_request_template.md) - which is a little onerous to fill in and especially annoying that one checklist item is duplicated...but also helpful.

I agree that a couple prompts is useful especially if our contributor's become more ad hoc, but danger if it's too prescriptive that it will be ignored.

**Comment by kimadactyl** [comment]
CK one looks nice but perhaps more designed around contexts where you're not doing most of the feature spec in the issue ticket?

agree it shouldn't be too long!

**Comment by kimadactyl** [comment]
Also just noting that the checklist for the contributor and for the person doing the review might be slightly different.
