### ISSUE TITLE
[Bug]: Some Instagram handles don't work

### ISSUE THREAD

**Issue by honor-gfsc** [geeksforsocialchange/PlaceCal#2506]
## Description

When entering an Instagram handle, was faced with an error saying the account name is invalid despite it being an active Instagram account 

![Screenshot showing queerasf.ck and the error PlaceCal gave](https://github.com/geeksforsocialchange/PlaceCal/assets/127757676/04405895-22d4-4422-8f18-f6688fb2fedb)

**Comment by kimadactyl** [comment]
Nice catch with an easy fix
