### ISSUE TITLE
[Bug]: Handbook link in calendar interface is broken

### ISSUE THREAD

**Issue by honor-gfsc** [geeksforsocialchange/PlaceCal#2536]
<img width="529" alt="Screenshot 2024-07-12 at 15 31 55" src="https://github.com/user-attachments/assets/129c9e50-ba35-47f4-a1e2-126049292c74">
The link in the screenshot 404s

**Comment by kimadactyl** [comment]
<img width="570" alt="Screenshot 2024-09-03 at 13 01 46" src="https://github.com/user-attachments/assets/44ef5b2e-2ac5-4750-a916-f3c7286f1d19">

verified
