### ISSUE TITLE
[New site]: Fruit Salad Events

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#2545]
# New site request

- Name of person: James Walker
- Region covered: London
- Site name: Fruit Salad Events
- Desired colour scheme (pick one): Blue
- [Optional] Interest covered: (Not sure - need to ask James and maybe add to form). If this is easy to change, I suggest use "Fruit Salad Events Collective" or something like that.
- Domain: fruitsaladevents.placecal.org

## Acceptance criteria

- [ ] fruitsaladevents.placecal.org exists!
- [ ] fruitsaladevents.placecal.org is not set to public
- [x] fruitsaladevents.placecal.org has an SSL certificate added (see [handbook](https://gfsc.notion.site/Creating-a-new-PlaceCal-Site-bd90494c88e74bfe94c306f714ede8dc))
- [ ] Header and footer logos are created (preferably as svg), with transparent background
- [ ] Site has logos uploaded in correct places
- [ ] James Walker is set as site admin
- [ ] James Walker is set as neighbourhood admin for London
- [ ] James Walker is set as partnership admin for Fruit Salad Events Collective
- [ ] The [handbook](https://gfsc.notion.site/Creating-a-new-PlaceCal-Site-bd90494c88e74bfe94c306f714ede8dc) is accurate (make edits if not clear)
- [ ] James Walker is informed their site has been created

**Comment by kimadactyl** [comment]
Closing this as we don't need to manage new sites in GitHub any more
