### ISSUE TITLE
Some characters are not being imported correctly

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#527]
- [ ] https://hulme.placecal.org/events/158981

**Comment by alexandria-gfsc** [comment]
I'm leaning towards "This is not a placecal error". AFAICT the event came from an XML feed from Manchester University, and we just rip the content from there with no post-processing of symbolic information except to strip newlines. The current feed does not process symbols at all and yet the event data we have stored contains these raw question mark symbols. i.e. If these were special symbols like the pound sign it would exist in the raw event as such, which it doesn't. So I'm closing this issue unless there's a more general problem with the parser and we have other/more examples of munging happening on our side.
