### ISSUE TITLE
Reclaim some space on the server and make sure it doesn't keep filling up again

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#750]
**Describe the bug**
We are using Dokku on Digital Ocean. We have a staging and live environment. The droplets keep filling up. We've tried a bunch and not sure what's going wrong. The steps we took to set them up are pretty well documented in INSTALL.md

## Acceptance Criteria

- [ ] The droplet continues to have disk space over time

## Plan for fixing

- [x] Deploy production to a new droplet

**Comment by katjam** [comment]
@alexandria-gfsc I made up some stuff in terms of plan - feel free to change to what you are actually doing & paste any notes you have so far here - or link to them at least.

**Comment by alexandria-gfsc** [comment]
Yeah, today I'm working a little bit on setting up a cronjob+email that'll allow us to track disk space and alert us if it grows rapidly or something seems awry :)
