### ISSUE TITLE
Fix automated deployment to staging & production

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#751]
**Is your feature request related to a problem? Please describe.**
We are using Travis CI. When a build completes, master pushes to staging (would be great to rename this to main but think it'll break everything), and production pushes to production. This may or may not be broken currently.

## Acceptance Criteria
 
- [x] The staging branch is `main` not `master`
- [x] When I merge code into main & the build completes with passing tests, some automated system should release that build to staging
- [x] When I merge code into production & the build completes with passing tests, some automated system should release that build to production

## Plan

- [x] Make branch `main`and designate it as staging default with same protections as current `master`
- [x] Fix intermittent failure of sassc+sprockets causing a runtime segmentation fault
- [x] #774

**Comment by katjam** [comment]
@alexandria-gfsc This is yours and I know you've done some thinking. Feel free to edit the description at will. I've not assigned it to you as I don't think you have started work on it yet.

**Comment by alexandria-gfsc** [comment]
Updated `master` -> `main` with https://github.com/geeksforsocialchange/PlaceCal/pull/775

**Comment by alexandria-gfsc** [comment]
GH Actions works now :)
