### ISSUE TITLE
Emails not sending from production app

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#752]
**Describe the bug**
Emails are not sending at the moment, stopping us adding new users

## Acceptance Criteria

- [ ] When I set up a new user on the site, they get an email
- [ ] tbc... check if we want to confirm more conditions that cause emails to send

## Plan
- [x] Check logs to see if emails are attempting to send
- [ ] #773

## Notes
 This might be solved by #750 
- currently the sending user emails is done with mailgun (maybe sendgrid), and the 'join placecal' webform is done with mailerlite. i would like to transition it all to mailerlite / mailersend (same company cant remember which we used) but theres no real hurry just you know. if its the sending service thats an issue lets update it (edited)

- mailersend / mailerlite is really good and well priced
- Sendgrid and mailgun got kinda sketchy

**Comment by katjam** [comment]
Blocked because need to test in production by setting up an account

**Comment by alexandria-gfsc** [comment]
Confirmed as fixed by adding `SENDGRID_API_KEY` to production and making a new user.
