### ISSUE TITLE
PlaceCal.org home page rework

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#756]
## Acceptance Criteria

- [ ] I can send a single link to people asking about PlaceCal that takes them to a place explaining how it works
- [ ] TBC - there might be more but that seemed the core priority for redesign

Design is here: https://drive.google.com/drive/folders/12hzZxgy5cWPutPanw3vhcZJKRaPIr34O?usp=sharing

Basically there is a page for each of the audience segments (under "how we can help"). The copy for these isn't finalised.

Where we got to with copy: https://docs.google.com/document/d/1FvaFvjQncchemrYxfz7NPp0-sF0m3-T1iJL-A1HIZlE/edit

**Comment by kimadactyl** [comment]
Let's close this and open new tickets when the designs are ready?

**Comment by erbridge** [comment]
Yup. I'll do that when I'm ready to open new ones. This remains an issue until then.

**Comment by kimadactyl** [comment]
Closing this as we have newer tickets for this now
