### ISSUE TITLE
More flexibility in which geographical level we put events into

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#783]
**Is your feature request related to a problem? Please describe.**
1. London is organised into boroughs rather than wards, so we need to introduce a defined hierarchy for 'location' of event that is more flexible thank the current 'ward' based system.
1. Political boundaries change so we need a way to keep out data up to date
1. We might consider including events in 'neighbouring' areas

**Describe the solution you'd like**
Bug: list of wards that each site shows - 1) You currently have to set a primary ward, but we want to remove this requirement, 2) If you set a secondary ward the same as the primary ward bad things happen 3) Secondary wards are obviously a pain right now to configure. These prob need some kind of nice hierarchical select thingy.

**Use case:** Gendered Intelligence coordinator should start with a blank slate and not what you can see if you're a root/superadmin user. They should be free to add partners and calendars for all of London.

Use postcodes.io API to get meta info from postcode
Use a rail hierarchy library for multi-select interface (like https://github.com/stefankroes/ancestry?)

**Describe alternatives you've considered**

**Additional context**
https://trello.com/c/UL4u2xBP/245-bugs-and-urgent-issues-from-kims-email-to-quinn

### Acceptance

- [ ] As a community admin for London, I can add have my events listed by borough, rather than ward
- [ ] more TBC...

**Comment by katjam** [comment]
@kimadactyl @alexandria-gfsc I know you've had loads of discord conversations around this.

Can you please add conclusions/ plans here? The scope of this issue is pretty broad and will likely want breaking down into subtasks.

**Comment by katjam** [comment]
@kimadactyl Good idea for this to be it's own milestone. I wasn't sure which of the existing ones to stick it in.

**Comment by kimadactyl** [comment]
Here's where I got to sketching out the new database architecture. This will allow us to retain as much as possible of the existing codebase too.

I'll convert what needs to happen to tickets on Monday.

![Proposed new Neighbourhood architecture](https://cdn.discordapp.com/attachments/903369904860839946/908376889238896680/Untitled_Artwork.png)

**Comment by kimadactyl** [comment]
Replaced by #790
