### ISSUE TITLE
Add new tests and fix logic for admins with different levels of area access

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#792]
- [ ] Add some more admins using `factory_bot` - users with region and ward level permission (make with just region, region & couple wards, 2 regions, one ward, a few wards)
- [ ] Create some tests so that admins assigned to `region`s can pass all the tests that admins assigned to the individual `ward`s in that region can
- [ ] Make the tests pass (probably by editing policies about neighbourhood admins and functions that return wards for an admin)

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/144452672-8369ad37-ed21-41ba-b08c-33a194f64d3e.png)
