### ISSUE TITLE
`is_working` and `critical_error` fields should be combined into single error field

### ISSUE THREAD

**Issue by alexandria-gfsc** [geeksforsocialchange/PlaceCal#795]
**Problem:**

The Calendar model uses two fields to indicate whether or not there has been an error, these must be kept in sync across any changes or additions to the codebase, and describe the same property from different perspectives. This means that they must be kept in sync across refactors of that section of the codebase.

**Resolution:**

Merge the two fields into a single item called `has_error` (or another name that is more descriptive), presence of a map field containing error data indicates an error, otherwise if the property is empty then no errors have occurred.

**Comment by ivankocienski** [comment]
@kimadactyl @katjam @alexandria-gfsc this is now obsolete as calendars use a state machine
