### ISSUE TITLE
Placecal does not fully support custom domains or domain aliasing

### ISSUE THREAD

**Issue by lexiwitch** [geeksforsocialchange/PlaceCal#797]
Domains like `marvellousmossley.org` are currently hardcoded in (See [here]). Ideally it should be possible to alias a subdomain to a full domain, or somesuch

[here]: https://github.com/geeksforsocialchange/PlaceCal/blob/neighbourhoods_791/app/models/site.rb#L100

**Comment by r-ferrier** [comment]
closing as we think this is no longer a business requirement
