### ISSUE TITLE
Improve visibility on "Overwrite with ward info" component

### ISSUE THREAD

**Issue by lexiwitch** [geeksforsocialchange/PlaceCal#798]
The current styling is not very visible / accessible. It should ideally be changed to something with greater contrast.

See the below image

![Screenshot from 2021-11-23 18-41-00](https://user-images.githubusercontent.com/92374839/143085711-f5b38649-3827-4dec-9ab0-d115468accf7.png)

**Comment by r-ferrier** [comment]
closing as this is a permission we are most likely removing anyway
