### ISSUE TITLE
Fix alignment on Calendar buttons in the Admin interface

### ISSUE THREAD

**Issue by alexandria-gfsc** [geeksforsocialchange/PlaceCal#799]
The Calendar buttons are misaligned and requires a fixup. Probably only on some monitors -- it would be useful to check that using the browser's Responsive Design Mode.

![Screenshot from 2021-11-23 19-26-08](https://user-images.githubusercontent.com/92374839/143090589-1190e58c-85e4-4f06-9bd0-ab838d427cd1.png)

**Comment by kimadactyl** [comment]
Closing as #819 will supercede
