### ISSUE TITLE
Remove /partners and /events pages from main domain (google indexing)

### ISSUE THREAD

**Issue by lexiwitch** [geeksforsocialchange/PlaceCal#800]
The text contrast on the /partners page is such that the text is invisible.

![Screenshot from 2021-11-24 11-29-29](https://user-images.githubusercontent.com/92374839/143230381-3713dbb7-07ab-4ce6-b4bc-93ddccb23885.png)

**Comment by alexandria-gfsc** [comment]
Note that the text is still there and shows 
![Screenshot from 2021-11-24 11-31-15](https://user-images.githubusercontent.com/92374839/143230585-ede4a161-7deb-45ee-89b2-0ca976ed8bff.png)
when highlighted
