### ISSUE TITLE
Events API reporting "NoMethodError: undefined method `location' for #<Event:0x0000561fa4a9c008>"

### ISSUE THREAD

**Issue by alexandria-gfsc** [geeksforsocialchange/PlaceCal#801]
Link: https://rollbar.com/gfsc/placecal-production/items/10/?item_page=0&item_count=100&#instances

This is locally replicable and so needs to be dealt with.

**Comment by kimadactyl** [comment]
Sucking up our rollbar allowance so labelling `vv`

**Comment by ivan-kocienski-gfsc** [comment]
obsolete - superseded by newer code
