### ISSUE TITLE
Give site emails some TLC

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#803]
**Describe the bug**
The emails from the site could do with some branding & making sure markup and data templating is correct

e.g. invitation to admin account email
![image](https://user-images.githubusercontent.com/861172/143909006-a3c8c772-8977-4a3d-bc0c-163f4ef91465.png)

**Consider**
- Adding logo
- Make sure sender email is correct
- Review copy
- Review use of data (like name) in email
- Think about legal/ privacy / footer information

**Comment by kimadactyl** [comment]
Promoting this a bit as i think it falls under new user experience first impressions

**Comment by ivan-kocienski-gfsc** [comment]
I am just going to check that this has been partially fixed. It's such an old issue it is proving tricky to match up the screenshot to a part of the code (!)

**Comment by aaaaargZombies** [comment]
## verififcation

looks like the link to the image is a relative path

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/0103cceb-4e0a-4544-99a6-bfdf34e623a1)

https://ci4.googleusercontent.com/proxy/2LG3c4PFSUehnIjCJp8f3TLBPah62b4f8NwV65LHXqNbLsNHlk47VRDxGamS1cvuCfnv0hHx5l5QNPC6Tm2UK3HUzharDftX5R8iOKXRCV3bz7zeFzG10ksD19-V_ZS0YFZUJYgDkjWliPc=s0-d-e1-ft#http:///assets/logo-f666f7e08fe6ebe234b6fcc81d2a06565ec7369ee674d4046ec84e03c3b3c459.png

names and html look a lot better

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/1328c414-573c-4ae6-80d5-cf3b275e5a1f)

will open new issue about the link
