### ISSUE TITLE
Update policy for calendar will return true for all partner admins

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#805]
**Describe the bug**

```
  def index?
    user.root? || user.neighbourhood_admin? || user.partner_admin?
  end

def update?
    return true if user.root?
    return true if user.partner_admin? && user.partner_ids.include?(record.partner_id)
    # return true if user.neighbourhood_admin? && user.neighbourhoods.include?(record.address.neighbourhood)
    index?
  end
```

Write tests first.

**Comment by kimadactyl** [comment]
This is correct I think. The `Scope` at the bottom limits which partners can be updated. Leaving open in case you think this just needs better test coverage.

**Comment by katjam** [comment]
We thought it was a bug because on line 22 there is an explicit check for partner id matching that record
https://github.com/geeksforsocialchange/PlaceCal/blob/1544b80fa4ec513ed9f499a8a3d5e80d07cd065e/app/policies/calendar_policy.rb#L22

But then it returns true for all partners anyway if that fails... so I guess either delete line 22 or return false if they don't match?

**Comment by katjam** [comment]
> OK yeah so this is less a bug, more a refactor to make the obfuscated code clearer. Do we have a tag for that?

Now we do. :)

**Comment by r-ferrier** [comment]
We're closing this based on recent work on neighbourhood admins & this code has now changed.

**Comment by ivan-kocienski-gfsc** [comment]
Verified in code (this is no longer the specified logic)
