### ISSUE TITLE
Redo edit neighbourhood view

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#806]
Neighbourhood edit screen is currently in need of a redesign as most of the fields in it are deprecated

![image](https://user-images.githubusercontent.com/861172/144459888-a07a4921-4e68-4cdc-a1fd-8117360607d4.png)

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/144459888-a07a4921-4e68-4cdc-a1fd-8117360607d4.png)

**Comment by kimadactyl** [comment]
All you need to do is define a `to_s` (string) method on the Neighbourhood model to fix the first screenshot.

**Comment by kimadactyl** [comment]
This ticket got bugged out for me somehow
