### ISSUE TITLE
Making a new user in the localhost testing environment gives 500 "No route matches [GET] "/users""

### ISSUE THREAD

**Issue by alexandria-gfsc** [geeksforsocialchange/PlaceCal#807]
Flow:
- http://admin.lvh.me:3000/users -> Add New User
- Submit, get the localhost signup page (Incorrectly redirects to localhost rather than lvh.me:3000 - maybe root cause)
- Click on the link in the signup page, get the error

**Comment by kimadactyl** [comment]
Duplicate of another issue which is now resolved
