### ISSUE TITLE
Improve admin by adding data tables

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#821]
**Is your feature request related to a problem? Please describe.**
Consider: https://aarvy.me/blog/2019/09/21/datatables-with-bootstrap-4-minimal-setup-in-rails-6/ 

**Describe the solution you'd like**
- [ ] Add search (on name) to neighbourhood admin screens and pagination

**Steps**
- [x] Update yarn depends
- [x] Add relevant js library (probably a more up to date one than in that post)
- [x] Update `/app/components/admin_index/_admin_index.html.erb`
- [x] Possibly need to ensure that controllers have a javascript option in `respond_to` or it won't work
- [x] strip out unwanted changes re. users
- [x] Make datatables javascript work for Neightbourhood admins
- [x] Make sure tests still pass

**Further work to be done**
- [x] In `app/datatables/neightbourhood_datatable.rb` return sql for Neightbourhoods scoped by permission - right now only `Neighbourhoods.all` works
- [ ] #860
- [x] #861
- [ ] #862

**Comment by alexandria-gfsc** [comment]
This fixes #793 also, doesn't it?

**Comment by kimadactyl** [comment]
> This fixes #793 also, doesn't it?

it doens't fix it no - #793 would be an improvement, but this is perfectly adequate for now :)
