### ISSUE TITLE
Legal messages (Privacy and T&C etc)

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#822]
**Is your feature request related to a problem? Please describe.**

## Acceptance criteria

Add the following:

- [ ] #2396
- [ ] #2398
- [ ] #2397
- [ ] Partner agreement

see also https://github.com/geeksforsocialchange/PlaceCal/issues/2291

## Plan

- revisit the notion doc linked below and step through tasks to make sure all the info is ready to write the privacy policy

**Comment by katjam** [comment]
David has some text - we can add to site when approved.

**Comment by david-gfsc** [comment]
https://www.notion.so/disabledjess/PlaceCal-Research-404f13171f2c4dde847a55e08ce714ea?pvs=4

**Comment by katjam** [comment]
> Can anyone except me and Jess see this?
> 
> https://www.notion.so/disabledjess/PlaceCal-Research-404f13171f2c4dde847a55e08ce714ea?pvs=4

I can see it but not comment on it. I was wondering when it says "I" is that Jess? Did we hire them to consult on this?

**Comment by david-gfsc** [comment]
Yes, PHT hired them

**Comment by r-ferrier** [comment]
https://www.notion.so/gfsc/5039f6f34ab946fbbaea112bc7249d82?v=31006dd1957f4ee1ac4e8e795aec82a9&p=6b9481a5eb1340b89ff636c4058df7f1&pm=s

**Comment by r-ferrier** [comment]
@kimadactyl is taking a first pass at this in notion

**Comment by kimadactyl** [comment]
lets do this in sep tickets, 4 documents is a lot of documents

**Comment by r-ferrier** [comment]
closing as dup

**Comment by kimadactyl** [comment]
The only one I didn't open a ticket for is partner agreement - but deffo one for another day anyway
