### ISSUE TITLE
Review default site template

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#825]
## User Story
As a person viewing a PlaceCal subdomain, I need to copy and information to be relevant to me so that I am not confused.

## Context
Now PlaceCal places can be non-geographical - e.g. Trans Dimension, some of the copy and layout in the template does not make sense. We need to review this and generate tickets.

## Example
 - for e.g. the text is out of date now (places)

**Comment by kimadactyl** [comment]
This is now part of a longer restructure @erbridge has started so closing in lieu of that.
