### ISSUE TITLE
Failed email delivery doesn't 501

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#830]
Double check that the interface doesn't return 501 or otherwise crash when an email fails to send to an address

**Comment by kimadactyl** [comment]
Actually did you do this @alexandria-gfsc?

**Comment by alexandria-gfsc** [comment]
I don't remember, I do remember noticing something similar as an issue but
whether that was before or after it was fixed is another thing. It's worth
sticking on the "code smells" list or whatever small item sweep-through
list is appropriate, I think.

**Comment by r-ferrier** [comment]
closing as not seen in action in rollbar

**Comment by kimadactyl** [comment]
To test this we would need to make a test which is a deliberately bad email request and ensure it doesn't crash the app. We can revisit when we do the email love tickets?

**Comment by r-ferrier** [comment]
We have just tested it and it does not crash anything!

**Comment by kimadactyl** [comment]
awesome!!
