### ISSUE TITLE
Advanced search & event viewer component

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#832]
Display of events is by day or by partner or by week
- maybe a little js app
- Needs to be responsive to when next event is since sometimes there is nothing happening soon
- Filter / search controls
- Empty state
- loading spinner

### Variables:
- time period
- partner/ neighbourhood
- site
- tag
- if repeating event or not

## Smart Filter

Set a number of thresholds (numbers given as examples)

- Below 10 events per week, show all events
- Below 30 events per week, show week view
- Otherwise, show day view

Allow override in Partner/Place setting.

Paginator needs updating for each one.

**Comment by katjam** [comment]
https://trello.com/c/Lj0FM7OJ/48-refactor-and-improve-the-paginator-filter-using-vuejs

**Comment by kimadactyl** [comment]
Dragging this one out of obscurity, this is a good think to think about now we have our js unclogged

**Comment by r-ferrier** [comment]
we're not making the advanced version of this but the 'smart filter' part is duplicated in another ticket, so closing for now and if this comes up again a new ticket can be made.
