### ISSUE TITLE
Make search work on ancestry columns (currently can only search by name because it's data column has same name)

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#860]

**Comment by alexandria-gfsc** [comment]
Likewise for this -- is this covered by Kim's PR?

**Comment by katjam** [comment]
Also, please verify and  close. I think you are right.

**Comment by kimadactyl** [comment]
Ditto other ticket. I don't think this is done no, for me we would have a proper little advanced search area with tests, leaving this open as a "we need to tidy this up later" ticket. It's good enough for now but not exactly release quality imo.

**Comment by katjam** [comment]
Closing because is a couple years old and not sure if it is a current priority. Will leave 1137 open as ref.
