### ISSUE TITLE
Add sort to datatable columns in neighbourhood admin

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#862]

**Comment by alexandria-gfsc** [comment]
This is fixed as of kim's datatables PR, right?

**Comment by katjam** [comment]
Yes I am pretty sure you are right. Can you verify quickly and close?

**Comment by kimadactyl** [comment]
I don't think this is done no, for me we would have a proper little advanced search area with tests, leaving this open as a "we need to tidy this up later" ticket. It's good enough for now but not exactly release quality imo.

**Comment by kimadactyl** [comment]
Now a dupe of #1137
