### ISSUE TITLE
Allow datatables columns for neighbourhood ancestry relations

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#866]
Currently this is hard to do because Ancestry doesn't allow eager loading.

[Probably need something from here](https://github.com/jbox-web/ajax-datatables-rails#associated-and-nested-models)

**Comment by alexandria-gfsc** [comment]
Fixed the first part of this with #887, it just needs a frontend fix now I think

**Comment by katjam** [comment]
Closing as a won't fix but leaving #1137 which hopefully will prompt these thoughts
