### ISSUE TITLE
Investigate why users index is loading tags

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#869]
When loading the admin users index, it's loading tags for all users for some reason

**Comment by ivankocienski** [comment]
The reason is that the column "admin roles" tests to see if user is a `tag_admin` which involves looking into the tag table. This was sped up in the controller by 'including' the `users.tags` in the base query.

**Comment by ivan-kocienski-gfsc** [comment]
Verified in code - admin users index does query tags for each user (to determine if user is tag admin)
