### ISSUE TITLE
Consolidate migrations

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#876]
We have a lot of migrations mounting up. We might want to consolidate these before a 1.0 release.

- [ ] #954 
- [ ] Ensure data migrations are separate from schema migrations
- [ ] Simplify migrations as far as possible

**Comment by alexandria-gfsc** [comment]
Edited to add #954

**Comment by katjam** [comment]
We did some work on this recently. Closing. https://github.com/geeksforsocialchange/PlaceCal/commit/240b566bd29c70355e5f680f14ac9953bf14b9b1
