### ISSUE TITLE
Show who to contact if event information is wrong

### ISSUE THREAD

**Issue by lexiwitch** [geeksforsocialchange/PlaceCal#882]
https://github.com/geeksforsocialchange/PlaceCal/blob/main/app/models/event.rb#L96

**Comment by aaaaargZombies** [comment]
https://github.com/geeksforsocialchange/PlaceCal/blob/main/app/models/event.rb#L151C1-L151C58

>  # TODO: plan this out on paper, currently half finished
>  # Who to contact if the event is wrong

**Comment by aaaaargZombies** [comment]
I think there is another issue about contacting users when their events/calendars are broken

**Comment by katjam** [comment]
Probably superceded.
