### ISSUE TITLE
Event permalinks go to an obsolete URL on the root domain

### ISSUE THREAD

**Issue by lexiwitch** [geeksforsocialchange/PlaceCal#883]
https://github.com/geeksforsocialchange/PlaceCal/blob/main/app/models/event.rb#L86

**Comment by kimadactyl** [comment]
I'm not sure if it should use the subdomain, or if we need a good redirect rule. There's an argument that the permalink should be as simple as possible and not tied to the current name of the neighbourhood?

**Comment by aaaaargZombies** [comment]
solved by redirecting 404 to find your placecal
