### ISSUE TITLE
Create workflow to sync staging server DB with production

### ISSUE THREAD

**Issue by alexandria-gfsc** [geeksforsocialchange/PlaceCal#891]
Currently, staging and production have the same database, however, in the future we will have the production database being edited by people. We should ensure that not only is there a way for the current staging to become production (Covered by #890), but also that there is a way for staging to have the most "up to date" database from production, otherwise we can not be _completely_ assured that any given change will not needlessly, or recklessly disrupt production.

While this is handled largely by automated testing, the function of staging should, IMHO, grant us complete assurance against accidental data munging or marring on during data migration or input/output. It should be the place where we can preview how updates will affect production, without actually touching production data.

This however should probably be part of a larger conversation and taken in relation to how this process will affect user data, how we handle user data in general (We have already talked about this but it would be good to have some formal process :smile:), etc. ad infinitum

**Comment by kimadactyl** [comment]
Think this is done now
