### ISSUE TITLE
Make addresses and service areas togglable but always require at least one

### ISSUE THREAD

**Issue by ivankocienski** [geeksforsocialchange/PlaceCal#895]
Partner model needs to validate that there is at least one of: service_areas or address. Some nice feedback should be given to the admin if both of these are blank.

## Acceptance criteria

- [x] #958
- [x] If both are present, show address's service area in the location lozenge
- [x] Edge case: lots of service areas, no address - what to do?
- [x] Put service area information on the partner show page

**Comment by kimadactyl** [comment]
A note that the "required" indicator is a bit misleading at the moment
