### ISSUE TITLE
Update user edit screen to use cocoon

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#902]
`http://admin.lvh.me:3000/users/:id/edit` need to use new cocoon inputs too

try to get select2 to have a search bar

try and get the label to be contextual_name

**Comment by ivankocienski** [comment]
Things to do

- [ ] Neighbourhood selector
- [ ] Partner selector

**Comment by alexandria-gfsc** [comment]
- Search box already exists
You start typing, and it searches through the listed entries. This perhaps is not very user-visible but I'm not sure how to make it _more_ user visible. 

- Neighbourhood inputs now use `contextual_name` on the User's screen

- Select2 inputs look fine as-is IMHO, is there any specific reasoning for having them over select2 inputs? IMHO It'd be better to focus on doing some work with disabling / enabling association fields based on if someone is able to edit the component in `permitted_attributes`, like the edit page with tags does, but that is/should be a separate ticket.

Based on the fact the criteria are either already implemented, or need a discussion around em :wink:, I'm closing this :smiling_imp:
