### ISSUE TITLE
Fix Calendar Import Errors on Production, also find a better strategy for failing calendars

### ISSUE THREAD

**Issue by alexandria-gfsc** [geeksforsocialchange/PlaceCal#920]
Two calendars are causing 26 thousand errors in production, they are:
- Marvellous Mossley (id: 31)
- Mosston Miner's Community Arts And Music Center (id: 48)

For the reason: "Partner cannot be blank".

The partner seems to be blank in the first case because it is linked to the Mossley region, rather than a specific Mossley partner. This is eating into a **significant** part of our Rollbar error logging capacity, leaving less space for salient errors that might occur later on.

- [ ] Fix these errors by adding a partner to each of them (Partner might already exist for Mosston)
- [ ] Figure out and implement a better strategy for failing calendars than consistently reporting each time (e.g. "After 5 consecutive import failures, we deactivate the calendar and show it as failing on the calendars page")

See also:
https://github.com/geeksforsocialchange/PlaceCal/issues/828
https://github.com/geeksforsocialchange/PlaceCal/issues/757

**Comment by kimadactyl** [comment]
Suggestion

Is your feature request related to a problem? Please describe.

Importing dead calendars is killing our rollbar allowance and slowing down our cron job

Describe the solution you'd like

Add an "is_enabled" boolean to Calendars
If a calendar returns a valid error code, set this boolean to false
Disabled calendars don't import

**Comment by kimadactyl** [comment]
Pretty sure this is fixed now partner is mandatory
