### ISSUE TITLE
Ensure that behaviour around a Secondary Neighbourhood being a duplicate of the Primary Neighbourhood is formalized and tested

### ISSUE THREAD

**Issue by lexiwitch** [geeksforsocialchange/PlaceCal#925]
- [ ] Decide whether we want to ignore or handle a secondary neighbourhood being a duplicate of the primary neighbourhood
- [ ] Either way, add testing to ensure that the behaviour is consistent
- [ ] If we decide this is something we want to disallow (or for e.g. silently filter it out), then write code to ensure the tests pass

Formerly:
~~Investigate 501 on adding Secondary Neighbourhood that is also the Primary Neighbourhood~~
~~- [ ] If cause is complex, then add an error screen to the admin page to state that this is disallowed behaviour~~

**Comment by alexandria-gfsc** [comment]
Verified as no longer present on `main` as of 2022-02-09T15:48 (Commit: 94049d0b86f38a3e0bbaf26099a775c9d72e614c).

**Comment by alexandria-gfsc** [comment]
Reopened to add testing

**Comment by aaaaargZombies** [comment]
This relates to `Sites`. 

Sites are now defined by a `partnershiop` `tag`  does that mean neighborhoods are redundant on Sites?

**Comment by katjam** [comment]
Closing as verified previously
