### ISSUE TITLE
Clicking an "accept invite" link while already logged in gives a 501

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#939]
**Describe the bug**
If you are already logged in, clicking an 'accept invite' link from a new user registeration link goes to `/users` which then 501s.

**To Reproduce**

1. Log into PlaceCal as a root
2. Create a new user
3. Click the activation link
4. Error shows up

**Expected behavior**

PlaceCal shows a useful error message like "You are already logged in, would you like to logout?"

**Comment by aaaaargZombies** [comment]
looks like someone has fixed this!

I ran through the steps and got redirected admin root and a flash told me I was already logged in.

Also why would this happen if you already have a root account?
