### ISSUE TITLE
Can't select "United Kingdom" in service areas

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#940]
**Describe the bug**

"Nationwide" partners don't have a suitable option and need to pick each country separately.

**Comment by kimadactyl** [comment]
Tricker than it looks and probably has some bigger issues to worry about. People can add countries manually for now.

**Comment by katjam** [comment]
Making the decision to "won't fix" unless it comes up specifically. It seems sensible that providers can add each country individually and it's not too much effort if they happen to cover all 4.
