### ISSUE TITLE
Make "invite new user" messages friendlier

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#942]
**Is your feature request related to a problem? Please describe.**

New user invites are very impersonal at the moment.

**Describe the solution you'd like**

Add information to the email about who invited you, and allow a space for a welcome message from the invitee.

**Comment by kimadactyl** [comment]
oops wrong ticket

**Comment by katjam** [comment]
Added as consideration when fixing this: https://github.com/geeksforsocialchange/PlaceCal/issues/1308
