### ISSUE TITLE
Automatically provision ssl certificate when creating new sites

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#946]
Be neat if we can do this automatically but very very low priority

**Comment by r-ferrier** [comment]
We've discussed this, and think that this is easy to do right now but would take us a really long time to research how to automate and then automate. It's something that happens only a few times a year and we think this frequency is unlikely to increase enough to make this worthwhile in the near future, so we're closing this for now.

**Comment by aaaaargZombies** [comment]
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/2a6c744c-19e4-4490-a541-5e2de91b5df1)

**Comment by ivan-kocienski-gfsc** [comment]
verified as wont fix
