### ISSUE TITLE
Pull importing of neighbourhoods into rake task

### ISSUE THREAD

**Issue by lexiwitch** [geeksforsocialchange/PlaceCal#954]
While this is part of the data migration consolidation, it can / should be considered a separate task

- [ ] I can clone placecal, and run a rake task, and have the full Neighbourhoods dataset in my local database

**Comment by katjam** [comment]
@geeksforsocialchange/developers given the new neighbourhood set-up, is this still an issue or can we close as a won't fix?

**Comment by ivan-kocienski-gfsc** [comment]
Think this is covered by [this work](https://github.com/geeksforsocialchange/PlaceCal/commit/ecc7ecb1e6f27e86c3010d605405e66e94b2ce7d).
