### ISSUE TITLE
Make the create partner form more user friendly

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#970]
## Description

The create partner process is very long. It's currently possible to spend a lot of time entering data before finding that you can't create a partner in that area, or that one exists with the same name.

Some of this has been addressed by: #2352, #2350

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/58059ab7-1534-4072-9da9-9952193ff138)

## Acceptance criteria

- [ ] The new partner form has only required fields: Name, Place & Partnership (if permitted)
- [ ] The Create partner re-directs to edit for that new partner

## Future considerations (TBC)
- [ ] There are 2 save buttons on new partner form (save & create another partner) (save & edit this partner) or does that complicate things
- [ ] #2408

**Comment by katjam** [comment]
Dream Yard until it becomes a priority. We might want a milestone if we scale.

**Comment by r-ferrier** [comment]
needs AC

**Comment by kimadactyl** [comment]
i had a crack at some AC / making the current ticket less vague but its probably really over featured. feels like a bit of a ball of string to untangle whats going on here

**Comment by katjam** [comment]
@kimadactyl I figured the simplest way to address this is a minimal create form. What do you think? If we forward to edit form on save then I don't think we'll lose much for folks who want to fill in everything in one sitting. It's kind of like having multi-step form that way. The name taken thing has also been resolved & validation on edit is much improved, so overall the experience will already be better.

I moved your suggestions to #2408 and will work up some AC there too.

**Comment by kimadactyl** [comment]
> @kimadactyl I figured the simplest way to address this is a minimal create form. What do you think? If we forward to edit form on save then I don't think we'll lose much for folks who want to fill in everything in one sitting. It's kind of like having multi-step form that way. The name taken thing has also been resolved & validation on edit is much improved, so overall the experience will already be better.
> 
> I moved your suggestions to #2408 and will work up some AC there too.

yeah absolutely, this is what i've been trying to advocate all along, glad we are now aligned :D

**Comment by ivan-kocienski-gfsc** [comment]
Verified on staging

![Screenshot_2024-04-23_15-12-14](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/67a0caab-8a94-4a23-8588-73df02f19954)
