### ISSUE TITLE
[bug]: Fields that are not editable by user should be greyed out or not shown

### ISSUE THREAD

**Issue by lexiwitch** [geeksforsocialchange/PlaceCal#991]
While this requires confirmation, I believe there are a handful of pages where a user can see fields that they cannot edit, but the fields are visible and look editable (They will just not be saved). These fields should be greyed out to avoid giving the user the false impression that they *should* be able to edit those fields, and that they are broken. In addition, I believe that #990 might be broader than just the users page, and will apply to any `f.association` elements.

- [ ] Confirm for each level of admin below `root`, for each `/edit` page that I can see, that any fields I cannot edit, either are broadly missing from the page, or are greyed out and do not display as interactive.

Example from #990
![image](https://user-images.githubusercontent.com/92374839/155330994-e9fd90ff-414f-4120-a997-f1f7740aa12d.png)

These should be rendered as inactive otherwise the page looks weird.

- [ ] If I am not a `neighbourhood_admin`, I should be able to see a greyed out field in place of the neighbourhood admin field
- [ ] If I am not root, I should either not be able to see Role, or it should have a greyed out field

## Acceptance criteria

- [ ] If a field is not editable it is greyed out
- [ ] #2233

**Comment by aaaaargZombies** [comment]
just adding this here as a prompt for tomorow

---

## looking for bad fields

### neighbourhood admin

### partnership admin

### partner admin

### citizen

**Comment by aaaaargZombies** [comment]
## verfied

closing as verified, looks like we have solved this in our work on permissions elsewhere

**Comment by katjam** [comment]
Re-opening as I came across this in creating a new user. I didn't actually have rights to any of the fields:
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/a9f57166-9a9e-4dc7-897a-9db7a8bb0c98)

**Comment by r-ferrier** [comment]
Verified - accessing create/edit user pages in admin is not possible on a non root user unless they can see at least one partner. This is mandated in the user policy & not just the UI.

![Screenshot 2024-02-01 at 15 20 51](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/5b27cc7a-e58e-43c5-8021-6b65e60973a6)

Creating a partner without attaching a user is not possible for non root users.

![Screenshot 2024-02-01 at 15 23 44](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/a7b194ac-c118-4a8b-8345-8b36c7f18b8d)

![Screenshot 2024-02-01 at 15 23 52](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/153af274-1184-4ea8-9d81-42dc2a454668)
