### ISSUE TITLE
Move developer PlaceCal handbook files into docs/ folder

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#997]
**Is your feature request related to a problem? Please describe.**

As the codebase develops it gets more and more important to have properly documented static code analysis-based documentation. We should self-host this so it can be accessed on for e.g. developers.placecal.org or placecal.org/developers

**Describe the solution you'd like**

Use yard documentation system which is the default Ruby generator

**Describe alternatives you've considered**

I've had a look for other doc gens and yard seems by far the most mature

## Steps to implement

- [ ] Create a git hook or the like to make sure the docs regenerate on each push
- [ ] Set up an endpoint in Rails to browse them 
- [ ] Set up a subdomain to see them on
- [ ] Migrate over relevant docs pages

**Comment by r-ferrier** [comment]
We going to close this because everything we need as devs for now is covered in the readme, releasing.md, and the new site issue template. We will open individual tickets for things we find are not covered as we need them.
